### ISSUE TITLE
Get available payment methods returns empty response.

### ISSUE THREAD

**Issue by sergy-gzh** [Adyen/adyen-magento2#545] opened 2019-10-15 09:28 UTC
**Magento version**: 2.3.3
**Plugin version**: 4.5.4
**Description**
**Configuration part:**
I have installed latest version of Adyen magento module.
Configured the adyen account number and test API key.
Enabled Adyen Credit Card.
Tested payment method on frontend - works as expected.
**Testing the REST API according to this documentation:** 
https://docs.adyen.com/plugins/magento-2/magento-pwa-storefront#get-payment-methods

Both endpoint for `guest` shopper and `customer` shopper return empty response.
At least Adyen Credit Card expected.

**Comment by rkewlani** [comment] 2019-12-31 08:52
Hi @sergy-gzh, This forum is only for code related issues and bug reporting. You may contact our support team for configuration related issues. Our tech support team will definitely help you.

Regards,
Rajni

**Comment by sergy-gzh** [comment] 2020-01-01 15:48
Hi @rkewlani !
The issue is code related.
Please take a look at the description one more time.
Perhaps I can make it more clear, please let me know what can be done.

**Comment by craigew** [comment] 2020-01-07 11:27
Hi,

I am experiencing the same issue.
Magento 2.3.3
Extension version 5.0.2

I can see the response from Adyen in the logs, but the Magento endpoint returns nothing.

Regards,

Craig

**Comment by cyattilakiss** [comment] 2020-01-13 09:01
Hi @sergy-gzh and @craigew ,

Thank you for raising the issue, we are going to validate the docs and the endpoint asap.
Can you maybe provide us the request object you send to the endpoint just to see if maybe the issue is there?

Thank you in advance,
Attila
Adyen

**Comment by cyattilakiss** [comment] 2020-01-16 11:30
Hi @sergy-gzh ,

I just tested it with a dev instance of mine and it works well for me for both guest and logged in users for the version **5.1.0**.
I checked the differences between the version 5.1.0 and 5.0.2  (the one that you mentioned in the issue report) and found that in the pull request we made some changes regarding filtering some payment methods on the frontend instead of on the backend for example the credit card payment method which you mentioned: https://github.com/Adyen/adyen-magento2/pull/591 

If you upgrade to the 5.1.0 version this issue should be solved.

I will close this ticket now and tag it as already solved but please feel free to reopen it if you have more questions.

Have a great day!
Best,
Attila
Adyen

**Closed by cyattilakiss** 2020-01-16 11:30 UTC
