### ISSUE TITLE
lost focus on credit card input when it's virtual product only order or the shipto address different from billto address 

### ISSUE THREAD

**Issue by lyvia-chung** [Adyen/adyen-magento2#962] opened 2021-02-10 03:24 UTC
**Describe the bug**
If this order is virtual product only order(only billto address is required)  or  shipto address different from billto address  and select the credit card as payment method.   it's very difficult to full-in all the credit card information.  it's always lost the focus on the fields

**To Reproduce**
1. Purchase virtual product only in the cart   or  have physical product but enter different  bill-to/ship-to address 
2. Select the "Credit Card" as payment method
3. enter the card number,  you will see it  the difficulty to input all info.  it seems it continue lost focus on the fields.

**Expected behavior**
Only exit the field then do the validation of that field

**Magento version**
[e.g. 2.3.4-p2]

**Plugin version**
[6.6.5]

**Screenshots**
see the video how the checkout  behave

[Checkout _ Acer Store Deutschland Offizielle Website - Google Chrome 2021-02-08 13-36-56.zip](https://github.com/Adyen/adyen-magento2/files/5955669/Checkout._.Acer.Store.Deutschland.Offizielle.Website.-.Google.Chrome.2021-02-08.13-36-56.zip)

**Desktop (please complete the following information):**
 OS: [Win10]
Browser [chrome]
Version 87.0.4280.141 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AlexandrosMor** [comment] 2021-02-12 09:12
Hello @lyvia-chung,

Thank you fo raising this issue, testing the issue we could not reproduce it. 
In the checkout page I select credit card, uncheck the `My billing and shipping address are the same` and click `update` so it can update the billing address. Next step entering the credit card and complete the purchase. 
I would like to ask you if we are missing any step and if you have any customisations on the plugin.

kind regards,
Alexandros
Adyen

**Comment by lyvia-chung** [comment] 2021-02-15 00:52
Thanks.  Alex. 

Do you have difficulty to enter the credit card information?  you can still complete the process, but it just keeping kick you out from the field.   
is that anyway I can setup call or testing with you (I am base on GMT+8) ?   we do have some customization but the issue was before we did the customization.      

regards, 
Lyvia

**Comment by lyvia-chung** [comment] 2021-02-18 07:37
@AlexandrosMor   
The checkout page that you have is  different from us.   The billlto address in your testing site is under  payment method.  but our checkout page is have shipping address and billing address before the payment method.  
it's nothing connect to payment method.       i think this could be the main reason that you are not able to reproduce the issue. 
regards, 
Lyvia

**Comment by lyvia-chung** [comment] 2021-02-19 18:30
@AlexandrosMor 

Today we remove our customization code and testing it again.  The issue is still same. 

Regards 
Lyvia

**Comment by acampos1916** [comment] 2021-06-09 13:13
Hello @lyvia-chung, I was also not able to reproduce this issue in the Magento default checkout. From the video I gather that you're using a one step checkout plugin.

>Today we remove our customization code and testing it again. The issue is still same.

Does this mean that you tried without the one step checkout plugin?

We have also released a new major version of the plugin that you might want to try to check if the issue persists. I'll be closing this issue now since it is not really related to the plugin but if you give us the following information we could be able to check the compatibility:

- Vendor and version of the checkout plugin.
- Is it reproducible with Adyen Payment >v7?

**Closed by acampos1916** 2021-06-09 13:13 UTC
Labels: Bug report, Issue: Cannot Reproduce, Issue: Needs more info, Issue: Waiting for response
