### ISSUE TITLE
[PW-8484] ApplePayPaymentMethod doesn't support storing of payment method

### ISSUE THREAD

**Issue by fahu** [Adyen/adyen-magento2#2087] opened 2023-06-12 20:41 UTC
**Description**
The class `ApplePayPaymentMethod` returns false for the methods
* `supportsCardOnFile`
* `supportsSubscription`
* `supportsUnscheduledCardOnFile`.

However, according to the Adyen documentation all three types of stored payment methods should be supported (https://docs.adyen.com/payment-methods/apple-pay).

<img width="993" alt="image" src="https://github.com/Adyen/adyen-magento2/assets/2507037/e867a317-a00b-47ec-bfc1-c79545b17802">

**Comment by candemiralp** [comment] 2023-06-22 13:02
Hello @fahu,

Thank you for raising this issue. We created an internal testing ticket. We are going to update you after testing the behaviour of Apple Pay recurring payments.

Best Regards,
Can

**Comment by candemiralp** [comment] 2024-01-15 12:55
Closing this issue since a fix has been released already. Please re-open the issue if the issue is persistent.

Best Regards,
Can

**Closed by candemiralp** 2024-01-15 12:55 UTC
Labels: Bug report
