### ISSUE TITLE
Creating an customer order on PWA with alternative payment methods returns the same quote 

### ISSUE THREAD

**Issue by mtytula** [Adyen/adyen-magento2#1586] opened 2022-06-27 13:40 UTC
**Describe the bug**
There is an observer `\Adyen\Payment\Observer\SubmitQuoteObserver` attached to the `sales_model_service_quote_submit_success` event. If there is no valid result code met, the rest of the observer logic will set the cart status back on true. When I complete my payment and go back to the success page, there is a request made to the ```\Adyen\Payment\Controller\Process\Result::execute``` method and there my quote should deactivated ```app/magento/vendor/adyen/module-payment/Controller/Process/Result.php:193``` but the quote is still active.

**To Reproduce**
1. Log in to your account.
2. Create an order using alternative payment methods. 
3. Make a successful payment on PWA website and go back to main page.
3. You will see the same cart page as before placing an order. (GraphQL query returns the same cartId identifier)

**Expected behavior**
It should close my quote after making a payment.

**Magento version**
PWA Studio 12.3.0
Adobe Commerce 2.4.4
PHP 8.1

**Plugin version**
8.2.5

**Additional context**
Issue recreated on all devices. I've tested some changes and commenting the ```app/magento/vendor/adyen/module-payment/Observer/SubmitQuoteObserver.php:32``` line resolves my issue without any side effects.

**Comment by mtytula** [comment] 2022-06-27 14:09
I did some debug and I've something interesting. When the SubmitQuoteObserver sets the cart status back on true, it saves for quote ID e.g. 169, but when Adyen is sending a request to the Process/Result controller, the quote id from session is not the same.

**Comment by mtytula** [comment] 2022-07-01 10:43
@RokPopov , the problem occurs when I use adyen_hpp (Alternative payment methods) with custom success redirect path

**Comment by Morerice** [comment] 2022-07-01 12:20
Hi @mtytula,

Thanks for your quick response.
I have attempted to replicate the issue with my graphQl integration (not a PWA one) and I was unable to reproduce it. However in my case both the `quoteId` in the observer and then in the `Result.php` were identical so it seems like what you mentioned in your comment is definitely related to this.

We don't think this is causing the issue, but could you send the `resultCode` from the response of the first payments request that you are doing? (Before the user is redirected)

Thanks,
Jean
Adyen

**Comment by mtytula** [comment] 2022-07-01 12:24
@Morerice 
I'm getting "RedirectShopper" result code using adyen_hpp in \Adyen\Payment\Observer\SubmitQuoteObserver

**Comment by mtytula** [comment] 2022-07-01 12:47
@Morerice 
There is a new quote created after returning the website with the same products in it like the previous one.
`getQuote` method from line https://github.com/Adyen/adyen-magento2/blob/develop/Controller/Process/Result.php#L195

**Comment by Morerice** [comment] 2022-07-01 13:02
> @Morerice There is a new quote created after returning to the website with the same products in it like the previous one. `getQuote` method from line https://github.com/Adyen/adyen-magento2/blob/develop/Controller/Process/Result.php#L195

Could you also check the resultCode you're getting in the `/payments/details` response that is triggered in the `Result.php` file? (More specifically this line: `$service->paymentsDetails($request)`)?

Thanks,
Jean
Adyen

**Comment by mtytula** [comment] 2022-07-01 13:10
@Morerice 
```payment details ===== >>> {"pspReference":"XXXXXXXXXX","resultCode":"Authorised","merchantReference":"00000423"} [] []```

**Comment by Morerice** [comment] 2022-07-01 13:19
> @Morerice `payment details ===== >>> {"pspReference":"XXXXXXXXXX","resultCode":"Authorised","merchantReference":"00000423"} [] []`

That also seems correct. Since up to this point all the responses seem correct and because we may require some further sensitive data to debug this issue, could you please open a ticket with our support team, by sending an email to magento@adyen.com? Please also include a link to this github issue so that our support team will contact me directly and we can try and figure out this issue together.

I will close this issue for now. However if it turns out that there is an issue with the plugin, I will reopen it and will provide more details here.

Thanks,
Jean
Adyen

**Closed by Morerice** 2022-07-01 13:19 UTC
Labels: Bug report, To be investigated
