### ISSUE TITLE
[PW-2230] Recurring payment run by cron expects browser info

### ISSUE THREAD

**Issue by janhemmingsson** [Adyen/adyen-magento2#673] opened 2020-03-25 08:59 UTC
**Describe the bug**
When cron makes a recurring payment, it is expected that HTTP_USER_AGENT has a value, and the payment is stopped.
We receive this:
ERROR: Notice: Undefined index: HTTP_USER_AGENT in /var/www/ordnad.se/vendor/adyen/module-payment/Helper/Requests.php on line 292

**To Reproduce**
The problem with reproducing this bug, is that subscription is not built into Magento 2. We are using the subscription module from Paradox Labs, but others have had the same problem (https://github.com/Adyen/adyen-magento2/issues/259), and so far, we have not seen that it has been fixed.

**Expected behavior**
The recurring order is placed without error.

**Additional context**
When asking Paradox Labs about this issue, I got this opinion/suggestion:
The proper fix in my opinion would be for them to move the 
<item name="browserinfo" xsi:type="string">Adyen\Payment\Gateway\Request\BrowserInfoDataBuilder</item>
parts in https://github.com/Adyen/adyen-magento2/blob/develop/etc/di.xml out of etc/di.xml and into etc/frontend/di.xml and etc/webapi_rest/di.xml.

**Comment by cyattilakiss** [comment] 2020-03-26 11:24
Hi @janhemmingsson ,

Thank you for raising this issue. I think this is a potential bug. Since this is a recurring payment started by the cronjob the HTTP_USER_AGENT won't have a value and we should not include that int the call. To verify that could you please send the relevant logs (filtered for 1 recurring payment started from the cron which failed) from the adyen folder and send it to the support@adyen.com email address?
Please include the github ticket and my name in the ticket so support will know to reach out to me when they get the logs.

Best,
Attila
Adyen

**Comment by janhemmingsson** [comment] 2020-03-30 14:08
Hi @cyattilakiss,
thank you for the answer.
Now, the execution doesn't seem to even get that far, since there is no entry in the Adyen logs at all. The error (cited above) occurs in the log for the subscription module in the db. 
Before I submitted this issue here, I reached out to Adyen support, but they considered it a 3rd party problem (but I do not agree).
How can we move this one forward? Could I test this in some other way?
Best regards,
Jan

**Comment by cyattilakiss** [comment] 2020-03-31 11:13
Hi @janhemmingsson ,

Do you see the /payments request for the recurring payment in your info.log?
The fastest way to check it is to archive (or just put all the log files from the adyen folder into a backup folder) so you see only the new log files generated with the latest logs. Then you can start the subscription module's cron job to trigger the recurring payments.

If yes could you please check the browserInfo object and see if none of the values are null?
If any of them are null then just to confirm that this is the issue you can use postman to send the request to the Adyen /payments endpoint on test while modifying the request (removing the fields with the value null) 
In case if this solves the issue I assume this is a bug on our (the plugin) end.

To verify it further could you please check this commit I just pushed: https://github.com/Adyen/adyen-magento2/commit/affd49c073cecb077fdbc8d1191d7fb3758843db and see if this solves your issue? If yes then we have already found the root cause. :) If not then we need to investigate it further. If we need that, could you please send me the ticket number you have for the issue you opened at our support?

I hope this helps and looking forward to your findings.

Best,
Attila
Adyen

**Comment by janhemmingsson** [comment] 2020-04-01 10:54
Hi @cyattilakiss ,
excellent - thank you very much! I tried the code, and now everything works as it should.
And as far as I can see from my tests, there are no side effects.
Best regards,
Jan

**Comment by cyattilakiss** [comment] 2020-04-01 11:38
Hi @janhemmingsson ,

Thank you for checking it for me. I'm going to create a ticket to create a permanent solution for this based on the changes I made in the commit.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment] 2020-05-15 14:02
Hi @janhemmingsson ,

We have just released the fix for this issue. Thank you again for you input.
I will close this thread for now, but feel free to reopen it if necessary!

Best,
Attila
Adyen

**Closed by cyattilakiss** 2020-05-15 14:02 UTC
Labels: Bug
