### ISSUE TITLE
[PW-7015] adyen_bankTransfer_IBAN payment method doesn't work

### ISSUE THREAD

**Issue by atty31** [Adyen/adyen-magento2#1641] opened 2022-08-03 07:10 UTC
**Describe the bug**
Nothing happens when I select adyen_bankTransfer_IBAN as a payment method and press the 'Place order' button.  I am not redirected either to adyen page or checkout success or the cart page with an error message. 
Would you please have a look? 

**To Reproduce**
1. Go to Checkout
2. Select `adyen_bankTransfer_IBAN` as a payment method
3. Submit or Place the order
4. Nothing happens

**Expected behavior**
adyen_bankTransfer_IBAN should work, same as iDeal or CC etc. 

**Magento version**
[2.4.2-p1]

**Plugin version**
[8.3.3]

**Comment by RokPopov** [comment] 2022-08-03 07:47
Hi @atty31,

Thank you for opening this issue with us.
Indeed, placing the order with bank transfer doesn't seem to be doing anything at this time.
I have opened a ticket internally and we will be looking into this.

Kind regards,
Rok,
Adyen

**Comment by RokPopov** [comment] 2022-08-09 15:54
Hi @atty31,

I hope you are doing well.
I wanted to give you an update regarding this issue, as we have been investigating on the cause behind it.
We've learned the underlying issue is related to the version of the Web Component that our plugin is using. The good news is that the fix will be introduced in the new release of the Web Component. After that, we will be able to update the version of the Web Component that the plugin uses, which should solve the issue.

Kind regards,
Rok,
Adyen

**Comment by atty31** [comment] 2022-08-11 14:07
Hi @RokPopov ,
Thank you for keeping me updated for this issue. Appreciate it !

**Comment by Morerice** [comment] 2022-08-22 08:21
Hi @atty31,

Fix will be out in the next release, which is due this week.

Thanks,
Jean
Adyen

**Closed by Morerice** 2022-08-22 08:22 UTC
Labels: Bug report, Confirmed
