### ISSUE TITLE
Call to a member function getAdditionalInformation() on null

### ISSUE THREAD

**Issue by JeroenVanLeusden** [Adyen/adyen-magento2#465] opened 2019-06-20 07:01 UTC
**Magento version**: 2.3.1
**Plugin version**: 4.1.1
**Description**

Not sure what triggers it exactly but see this error popping up every now and then:
```
Error: Uncaught exception 'Error' with message 'Call to a member function getAdditionalInformation() on null' in /home/***/deployment/releases/20190619092032/vendor/adyen/module-payment/Controller/Process/Result.php:380
```

Maybe this check can be improved to prevent this?
https://github.com/Adyen/adyen-magento2/blob/develop/Controller/Process/Result.php#L385-L387

**Comment by cyattilakiss** [comment] 2019-06-20 08:12
Hi @JeroenVanLeusden ,

Indeed you are right, if the order or the payment is missing this piece of code will fail. Thank you for raising the issue.

If you already have an improvement for this, can you also create the pull request?
Otherwise we are going to pick up this ticket in our next sprint.

Best,
Attila
Adyen

**Comment by JeroenVanLeusden** [comment] 2019-06-20 08:21
No fix developed yet, we'll wait till it's fixed in a new release. Doesn't seems to really break anything as far as I can see.

**Comment by cyattilakiss** [comment] 2019-06-20 09:00
@JeroenVanLeusden 
Okay I will include the issue number in the branch with the fix and also in the release so you will be notified.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment] 2019-07-02 09:41
Hi @JeroenVanLeusden ,

I've created the fix for this, although I was not able to reproduce this issue. Can you please help me when do you see this happening? If you maybe have the info.log logs for these specific payments, could you please send it to me to the address support@adyen.com? (Please tag me - Attila Kiss - in the email so the support will know to forward it to me :) )
Thank you for your help in advance,
Attila
Adyen

**Comment by JeroenVanLeusden** [comment] 2019-07-03 15:01
@cyattilakiss,

I'll see if I can find any useful logs regarding this issue and will let you know.

**Comment by cyattilakiss** [comment] 2019-07-04 06:49
@JeroenVanLeusden Thank you it will help a lot :)

**Comment by cyattilakiss** [comment] 2019-07-09 08:48
Hi @JeroenVanLeusden we are going to release the changes this week.

Best,
Attila

**Closed by cyattilakiss** 2019-07-09 08:48 UTC
