### ISSUE TITLE
Wrong magento/module-paypal require version?

### ISSUE THREAD

**Issue by olivermontes** [Adyen/adyen-magento2#658] opened 2020-03-04 13:01 UTC
**Describe the bug**
in last version https://github.com/Adyen/adyen-magento2/blob/5.4.0/composer.json#L20 upgrade version require **magento/module-paypal 100.3.X** this can mean last version is compatible only Magento 2.3.X and higher.

Magento 2.3.0 upgrade paypal module version to 100.3.0 https://github.com/magento/magento2/blob/2.3.0/app/code/Magento/Paypal/composer.json#L44 

**Expected behavior**
Continue support 2.8.X requirements from Readme: 

> This plugin supports Magento2 version 2.2.8 and higher.

**Additional context**
Is very important communication about drop support from different Magento versions like https://docs.adyen.com/plugins/magento-2

**Comment by cyattilakiss** [comment] 2020-03-05 09:24
Hi @olivermontes ,

Thank you for raising this issue.
Indeed, you are right. We are going to create a pull request to lower the minimum required version of the magento/module-paypal to ">=100.2.6" so it will be still compatible with 2.2.8

Best,
Attila
Adyen

**Comment by olivermontes** [comment] 2020-03-05 11:43
@cyattilakiss thanks!

**Comment by mrodespin** [comment] 2020-03-30 08:05
@cyattilakiss Are you going to merge this bug fix on master branch?

**Comment by cyattilakiss** [comment] 2020-04-01 08:27
Hi @olivermontes , @mrodespin ,

Thank you for the patience, the fix has just been released in the version 6.0.0

Please note that this is a major release including breaking changes for backwards compatibility. (You can read more in the release notes and the related pull requests)

I will close this issue for now but feel free to reopen it if you still experience it.

Best,
Attila
Adyen

**Closed by cyattilakiss** 2020-04-01 08:27 UTC
Labels: Bug

**Comment by sgonzalezme** [comment] 2020-04-02 11:08
Hello @cyattilakiss .
Are you sure that 6.0.0 is compatible with Magento 2.2.8? Some (*) of our credit cards are still having that weird  3DSecure redirect behaviour which we had on Adyen 4.5, while our projects with Magento 2.3.1 are working as expected now.

(* Not all of them, only a few have this problem).

**Comment by cyattilakiss** [comment] 2020-04-02 11:27
Hi @sgonzalezme ,

This issue was regarding a composer required version for the magento/module-paypal package. If you were able to upgrade to 6.0.0 on a Magento instance which is on the version 2.2.8 then yes this is compatible.

The weird 3DS behaviour you are referring to, is maybe the 3DS1 issue which we have with the Google Chrome browser v80? If yes then the issue should be the following:
You place the order with a test card from here: https://docs.adyen.com/development-resources/test-cards/test-card-numbers/#test-3d-secure-authentication 
You authenticate yourself on the 3DS1 redirect page and when you are redirected you are redirected to an empty cart. Is this the issue you are experiencing?
If yes please reach out to our support via email: support@adyen.com and they are happy to give you the necessary steps to fix this issue.

If not, but the issue is not related to this ticket could you please open another issue with the description of the problem you are experiencing and code related?

If you are not sure you can contact our support as well, then they can help if it is a configuration related issue or code related one.

I hope this helps.

Best,
Attila
Adyen

**Comment by sgonzalezme** [comment] 2020-04-02 11:37
Wow, it's exactly that case. My boss is reaching your support team as I write this! Thank you so so much!
Sorry for ask here, i thought it could be related to Magento version...

**Comment by cyattilakiss** [comment] 2020-04-02 11:38
@sgonzalezme that's all right :)
Have a nice day!

**Comment by cyattilakiss** [comment] 2020-04-02 11:41
@sgonzalezme sorry, I just asked around and it turned out that we already have an FAQ page for this issue, which you can find here: https://support.adyen.com/hc/en-us/articles/360012863940-How-can-the-new-Chrome-Cookie-Policy-version-80-impact-my-Magento-environment-

It's easier and faster this way 👍
