### ISSUE TITLE
[PW-6448] Adyen DropIn doesn't support some icons from paymentMethodsExtraDetails

### ISSUE THREAD

**Issue by Fifciu** [Adyen/adyen-magento2#1298] opened 2021-12-21 13:37 UTC
**Describe the bug**
`paymentMethodsExtraDetails` property from POST `/V1/carts/mine/retrieve-adyen-payment-methods`'s response has wrong icons which prevents Adyen DropIn component from showing them.

For example, for `paypal` object, we have `icon` field with the value equal (response.paymentMethodsExtraDetails.paypal.icon):
```js
{
   height: 41,
   url: "https://magento2.test/static/version1634899746/frontend/Magento/luma/en_US/Adyen_Payment/images/logos/paypal.png",
   width: 65
}
```

Unfortunately, then dropin tries to use the whole object as a `src` for `img` tag (paypal, paywithgoogle). What's interesting, it isn't happening for every payment method (scheme).

```html
<img class="adyen-checkout__payment-method__image DropinComponent-module_adyen-checkout__payment-method__image__Fg2uw adyen-checkout__image" src="[object Object]" alt="PayPal" focusable="false">
```

**To Reproduce**
1. Send POST `/V1/carts/mine/retrieve-adyen-payment-methods` or POST `/V1/guest-carts/${cartId}/retrieve-adyen-payment-methods` request.
2. Use `response.paymentMethodsExtraDetails` as a configuration for the dropin component.
3. Mount the Adyen Dropin Component
4. Make sure there are paypal & paywithgoogle methods - look for their icons - they are missing

**Expected behavior**
Response contains format expected by Adyen's DropIn

**Magento version**
2.4.3

**Plugin version**
7.3.0

**Adyen Dropin version**
4.9.0

**Screenshots**
![image](https://user-images.githubusercontent.com/30155292/146939075-0d49dc1a-0ebb-419f-8646-012861c8dc01.png)

**Additional context**
It's happening in my headless integration.

**Comment by tnaber** [comment] 2022-03-23 10:33
Hi @Fifciu,

My apologies for the slow response. I have investigated this issue and have not been able to recreate the bug so far. I have inspected the differences in response for the different payment methods, for both v7 and v8 I could not find any differences between, for example, creditcard and paypal.
This might indicate that the problem lies with the drop-in component itself. In order to verify this, could you tell me whether the issue also occurs for version 8 and/or if you are seeing differences in the format of the 'icon' field for the different payment methods?

Cheers,
Titus

**Comment by Fifciu** [comment] 2022-04-01 07:58
I've just tried with 8.1.0 version and I have the same. Could you please put there your response from `POST /V1/guest-carts/${cartId}/retrieve-adyen-payment-methods`?

Below is mine. As you see `icon` is an object but Adyen Drop-in 4.9.0 expects a string.
![image](https://user-images.githubusercontent.com/30155292/161220763-9f51fcfb-0fc3-4723-a29f-214b7fefa161.png)

**Comment by tnaber** [comment] 2022-04-04 09:17
The response I get is (pretty cluttered):

"{\"paymentMethodsResponse\":{\"paymentMethods\":[{\"issuers\":[{\"id\":\"1121\",\"name\":\"Test Issuer\"},{\"id\":\"1154\",\"name\":\"Test Issuer 5\"},{\"id\":\"1153\",\"name\":\"Test Issuer 4\"},{\"id\":\"1152\",\"name\":\"Test Issuer 3\"},{\"id\":\"1163\",\"name\":\"Ideal bridge test issuer\"},{\"id\":\"1151\",\"name\":\"Test Issuer 2\"},{\"id\":\"1162\",\"name\":\"Test Issuer Cancelled\"},{\"id\":\"1161\",\"name\":\"Test Issuer Pending\"},{\"id\":\"1160\",\"name\":\"Test Issuer Refused\"},{\"id\":\"1159\",\"name\":\"Test Issuer 10\"},{\"id\":\"1158\",\"name\":\"Test Issuer 9\"},{\"id\":\"1157\",\"name\":\"Test Issuer 8\"},{\"id\":\"1156\",\"name\":\"Test Issuer 7\"},{\"id\":\"1155\",\"name\":\"Test Issuer 6\"}],\"name\":\"iDEAL\",\"type\":\"ideal\"},{\"brands\":[\"mc\",\"visa\"],\"name\":\"Credit Card\",\"type\":\"scheme\"},{\"configuration\":{\"intent\":\"capture\"},\"name\":\"PayPal\",\"type\":\"paypal\"},{\"name\":\"Pay later with Klarna.\",\"type\":\"klarna\"},{\"name\":\"SEPA Direct Debit\",\"type\":\"sepadirectdebit\"},{\"name\":\"Pay now with Klarna.\",\"type\":\"klarna_paynow\"}],\"storedPaymentMethods\":[{\"iban\":\"NL26TEST0336169116\",\"id\":\"X5R9P9RXS2M84H82\",\"name\":\"SEPA Direct Debit\",\"ownerName\":\"C. Klaassen\",\"supportedShopperInteractions\":[\"ContAuth\",\"Ecommerce\"],\"type\":\"sepadirectdebit\"},{\"iban\":\"NL36TEST0236169114\",\"id\":\"841637673459212A\",\"name\":\"SEPA Direct Debit\",\"ownerName\":\"B. Klaassen\",\"supportedShopperInteractions\":[\"ContAuth\",\"Ecommerce\"],\"type\":\"sepadirectdebit\"},{\"brand\":\"mc\",\"expiryMonth\":\"03\",\"expiryYear\":\"2030\",\"holderName\":\"test ds\",\"id\":\"841632834573305G\",\"lastFour\":\"5454\",\"name\":\"MasterCard\",\"networkTxReference\":\"MCC11277844400321\",\"supportedShopperInteractions\":[\"ContAuth\",\"Ecommerce\"],\"type\":\"scheme\"},{\"brand\":\"visa\",\"expiryMonth\":\"03\",\"expiryYear\":\"2030\",\"holderName\":\"test\",\"id\":\"8316291232257822\",\"lastFour\":\"1111\",\"name\":\"VISA\",\"networkTxReference\":\"495231625432360\",\"supportedShopperInteractions\":[\"Ecommerce\",\"ContAuth\"],\"type\":\"scheme\"},{\"brand\":\"visa\",\"expiryMonth\":\"03\",\"expiryYear\":\"2030\",\"holderName\":\"Checkout Shopper PlaceHolder\",\"id\":\"831637669171755E\",\"lastFour\":\"0000\",\"name\":\"VISA\",\"networkTxReference\":\"853211547367886\",\"supportedShopperInteractions\":[\"ContAuth\",\"Ecommerce\"],\"type\":\"scheme\"},{\"brand\":\"bcmc\",\"expiryMonth\":\"03\",\"expiryYear\":\"2030\",\"holderName\":\"Titus\",\"id\":\"8416456085008296\",\"lastFour\":\"4449\",\"name\":\"MasterCard\",\"networkTxReference\":\"MCC78100658360223\",\"supportedShopperInteractions\":[\"Ecommerce\",\"ContAuth\"],\"type\":\"scheme\"},{\"brand\":\"visa\",\"expiryMonth\":\"03\",\"expiryYear\":\"2030\",\"holderName\":\"Titus\",\"id\":\"841632390316397J\",\"lastFour\":\"1237\",\"name\":\"VISA\",\"networkTxReference\":\"374324413821976\",\"supportedShopperInteractions\":[\"Ecommerce\",\"ContAuth\"],\"type\":\"scheme\"},{\"id\":\"831638438430639G\",\"name\":\"PayPal\",\"shopperEmail\":\"sb-erajg5894837@personal.example.com\",\"supportedShopperInteractions\":[\"ContAuth\",\"Ecommerce\"],\"type\":\"paypal\"},{\"brand\":\"mc\",\"expiryMonth\":\"03\",\"expiryYear\":\"2030\",\"holderName\":\"Checkout Shopper PlaceHolder\",\"id\":\"831633953157577C\",\"lastFour\":\"1234\",\"name\":\"MasterCard\",\"networkTxReference\":\"MCC76114457251102\",\"supportedShopperInteractions\":[\"Ecommerce\",\"ContAuth\"],\"type\":\"scheme\"},{\"id\":\"8316291024941757\",\"name\":\"VISA\",\"supportedShopperInteractions\":[\"ContAuth\"],\"type\":\"visa\"},{\"brand\":\"mc_amazonpay\",\"expiryMonth\":\"10\",\"expiryYear\":\"2020\",\"holderName\":\"John Smith\",\"id\":\"8416282582572190\",\"lastFour\":\"5454\",\"name\":\"MasterCard\",\"networkTxReference\":\"MCC61181783340806\",\"supportedShopperInteractions\":[\"ContAuth\"],\"type\":\"scheme\"},{\"brand\":\"mc_amazonpay\",\"expiryMonth\":\"10\",\"expiryYear\":\"2020\",\"holderName\":\"John Smith\",\"id\":\"8416282577823681\",\"lastFour\":\"5454\",\"name\":\"MasterCard\",\"networkTxReference\":\"MCC68682427470806\",\"supportedShopperInteractions\":[\"ContAuth\"],\"type\":\"scheme\"},{\"id\":\"8416282544276302\",\"name\":\"VISA\",\"supportedShopperInteractions\":[\"ContAuth\"],\"type\":\"visa\"},{\"id\":\"8316282527194192\",\"name\":\"VISA\",\"supportedShopperInteractions\":[\"ContAuth\"],\"type\":\"visa\"},{\"id\":\"8316282524618854\",\"name\":\"VISA\",\"supportedShopperInteractions\":[\"ContAuth\"],\"type\":\"visa\"},{\"id\":\"8416282395996198\",\"name\":\"VISA\",\"supportedShopperInteractions\":[\"ContAuth\"],\"type\":\"visa\"}]},\"paymentMethodsExtraDetails\":{\"ideal\":{\"icon\":{\"url\":\"http:\\\/\\\/localhost:8080\\\/pub\\\/static\\\/version1647897072\\\/frontend\\\/Magento\\\/blank\\\/en_US\\\/Adyen_Payment\\\/images\\\/logos\\\/ideal.png\",\"width\":65,\"height\":41},\"isOpenInvoice\":false,\"configuration\":{\"amount\":{\"value\":1500,\"currency\":\"EUR\"},\"currency\":\"EUR\"}},\"card\":{\"icon\":{\"url\":\"http:\\\/\\\/localhost:8080\\\/pub\\\/static\\\/version1647897072\\\/frontend\\\/Magento\\\/blank\\\/en_US\\\/Adyen_Payment\\\/images\\\/logos\\\/card.png\",\"width\":77,\"height\":50},\"isOpenInvoice\":false},\"paypal\":{\"icon\":{\"url\":\"http:\\\/\\\/localhost:8080\\\/pub\\\/static\\\/version1647897072\\\/frontend\\\/Magento\\\/blank\\\/en_US\\\/Adyen_Payment\\\/images\\\/logos\\\/paypal.png\",\"width\":65,\"height\":41},\"isOpenInvoice\":false,\"configuration\":{\"amount\":{\"value\":1500,\"currency\":\"EUR\"},\"currency\":\"EUR\"}},\"klarna\":{\"icon\":{\"url\":\"http:\\\/\\\/localhost:8080\\\/pub\\\/static\\\/version1647897072\\\/frontend\\\/Magento\\\/blank\\\/en_US\\\/Adyen_Payment\\\/images\\\/logos\\\/klarna.png\",\"width\":77,\"height\":50},\"isOpenInvoice\":true,\"configuration\":{\"amount\":{\"value\":1500,\"currency\":\"EUR\"},\"currency\":\"EUR\"}},\"sepadirectdebit\":{\"icon\":{\"url\":\"http:\\\/\\\/localhost:8080\\\/pub\\\/static\\\/version1647897072\\\/frontend\\\/Magento\\\/blank\\\/en_US\\\/Adyen_Payment\\\/images\\\/logos\\\/sepadirectdebit.png\",\"width\":65,\"height\":41},\"isOpenInvoice\":false,\"configuration\":{\"amount\":{\"value\":1500,\"currency\":\"EUR\"},\"currency\":\"EUR\"}},\"klarna_paynow\":{\"icon\":{\"url\":\"http:\\\/\\\/localhost:8080\\\/pub\\\/static\\\/version1647897072\\\/frontend\\\/Magento\\\/blank\\\/en_US\\\/Adyen_Payment\\\/images\\\/logos\\\/klarna_paynow.png\",\"width\":65,\"height\":41},\"isOpenInvoice\":true,\"configuration\":{\"amount\":{\"value\":1500,\"currency\":\"EUR\"},\"currency\":\"EUR\"}},\"scheme\":{\"configuration\":{\"amount\":{\"value\":1500,\"currency\":\"EUR\"},\"currency\":\"EUR\"}}}}"

**Comment by Fifciu** [comment] 2022-04-04 10:29
@tnaber The response looks like mine. That's great. Check `paymentMethodsExtraDetails.paypal.icon` property. It's an object but it should be a `string`. If you use `paymentMethodsExtraDetails` as `paymentMethodsConfiguration` for Adyen Drop-in configuration (in version 4.9.0) you will see that icons aren't displayed correctly because `icon` value has been put in `src` attribute as `[object Object]`.

**Comment by tnaber** [comment] 2022-04-04 11:24
@Fifciu, I see. Good catch! Do you agree that changing it to a string on your side would be the correct solution for this?

**Comment by Fifciu** [comment] 2022-04-04 12:23
Yes, I agree

**Comment by tnaber** [comment] 2022-04-04 13:29
What do you mean? The fields are still persisted when sending the object as a string right?

**Comment by Fifciu** [comment] 2022-04-04 14:05
I mean that `icon` is an object that looks like:
```ts
interface {
  width: number,
  height: number,
  url: string
}
```
And I am wondering if instead of mapping it to `icon.url` string, shouldn't we customize Adyen Drop-in to use every 3 fields if available?

**Comment by tnaber** [comment] 2022-04-07 08:37
Hi @Fifciu,
That might be an interesting improvement. I am not sure to what extent the `width` and `height` fields are used by the drop-in component. I recommend opening a feature request on https://github.com/Adyen/adyen-web
As the problem is solved and further work is out of scope for this plugin I will be closing this issue :)

Cheers,
Titus

**Closed by tnaber** 2022-04-07 08:37 UTC
Labels: Bug report, To be investigated, Headless

**Comment by ThermScissorpunch** [comment] 2022-04-08 14:25
I am also expereincing this issue.
![image](https://user-images.githubusercontent.com/61228862/162455616-c4f9598d-321a-4dd4-b731-2de862f38170.png)
Can you make it so that the paymentMethodsExtraDetails object can be imported into the Web Drop In without modifying it first?

**Comment by tnaber** [comment] 2022-04-12 06:39
Hi @Fifciu and @ThermScissorpunch,

I opened a feature request [here](https://github.com/Adyen/adyen-web/issues/1576)

Cheers,
Titus
