### ISSUE TITLE
Unable to complete payment with iDeal

### ISSUE THREAD

**Issue by SimonPrins** [Adyen/adyen-magento2#834] opened 2020-09-30 14:09 UTC
**Describe the bug**
After upgrading the Adyen module to version 6.6.0 I am no longer able to complete the payment with the iDeal payment method. When clicking the 'Place order' button the page scrolls up to the iDeal section, however no error is displayed. I am not redirected to the iDeal payment page as I would expect.

**To Reproduce**
1. Go through the checkout process and choose iDeal as payment method.
2. Click 'Place order'

**Expected behavior**
I am redirected to the iDeal payment page.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 85.0.4183.102

**Additional context**
I am also experiencing this issue when trying to pay with PayPal: https://github.com/Adyen/adyen-magento2/issues/823 This could be related, however unlike what is mentioned in that issue I do not get redirected to a previous step in the checkout process when paying with iDeal.

**Comment by cyattilakiss** [comment] 2020-09-30 15:32
Hi @SimonPrins ,

Do you see the dropdown correctly rendered under the ideal payment method to choose your bank?
When I tried to reproduce it on one of our 6.6.0 environments I didn't face the same problem. Do you maybe have a staging website where we can reproduce this issue? 
What is the version of your Magento2 environment?

Thank you in advance.
Best,
Attila
Adyen

**Comment by SimonPrins** [comment] 2020-10-01 07:55
I do see the selection to choose the bank rendered correctly, although we have some customizations in the frontend so that it is not actually rendered as a dropdown, see screenshot:

<img width="718" alt="Schermafbeelding 2020-10-01 om 09 45 02" src="https://user-images.githubusercontent.com/6427655/94782646-d1eac300-03cb-11eb-9231-54eb1ed6eaa5.png">

These customizations are currently working on production with an earlier version of the Adyen module.
We are on Magento version 2.3.5-p2

I will send you an email with the details for our test environment.

**Comment by cyattilakiss** [comment] 2020-10-01 08:01
Hi @SimonPrins ,

Thank you for the response. Indeed we are going to have a problem there, let me check your test environment and I can point it out where to send the issuer id in the payment-information request :)
I will close this issue here since the problem is caused by a customisation, but let's follow up in email about this.

Best,
Attila
Adyen

**Closed by cyattilakiss** 2020-10-01 08:01 UTC
Labels: Bug report
