### ISSUE TITLE
Authorisation in cancelled order

### ISSUE THREAD

**Issue by SandroRh** [Adyen/adyen-magento2#1943] opened 2023-02-02 20:31 UTC
**Describe the bug**
We are facing an issue with the payment method named "PIX" (Brazil) where order is canceled by adyen payment response, and after that adyen authorize that payment. So adyen is authorizing a payment for a canceled order. In the adyen panel the order status is "paid", but in magento order remains canceled.

**To Reproduce**
1. Authorize payment on a canceled order.
2. See error

**Expected behavior**
Do not authorize a payment on a cancelled order in Magento. Adyen module should check if the order is canceled when trying to authorize, and if so, then cancel the payment in Adyen Panel too.

**Magento version**
2.4.2

**Plugin version**
8.9.0

**Screenshots**
![image](https://user-images.githubusercontent.com/44475867/216442915-eac6a923-ff30-4ffc-9d0b-aafcd0ac44cd.png)

**Comment by Morerice** [comment] 2023-02-03 08:59
Hi @SandroRh,

Thanks for opening this issue. Since there is no code fragment referenced and because we weren't able to reproduce the issue based on the steps provided, could you please open an internal ticket by sending an email to support@adyen.com?

We will be in close contact with our support team to identify a possible solution. If this is something related to the plugin, we will link the fix to this issue.

Regards,
Jean
Adyen

**Closed by Morerice** 2023-02-03 08:59 UTC
Labels: Bug report
