### ISSUE TITLE
[PW-6382] GraphQL PlaceOrder dont work

### ISSUE THREAD

**Issue by larsroettig** [Adyen/adyen-magento2#1267] opened 2021-12-02 09:42 UTC
**Describe the bug**
* it is not possible to check out via `adyen_cc` via *GraphQLResolver* \
  `Magento\QuoteGraphQl\Model\Resolver\PlaceOrder::resolve`

**To Reproduce**
Execute Query `setPaymentMethodOnCart`

```graphql
 mutation setPaymentMethodOnCart(
        $cart_id: String!
        $payment_method: String!
        $additional_data: AdyenAdditionalDataCc
    ) {
        setPaymentMethodOnCart(
            input: {
                cart_id: $cart_id
                payment_method: {
                    code: $payment_method
                    adyen_additional_data_cc: $additional_data
                }
            }
        ) {
            cart {
                id
                selected_payment_method {
                    code
                    title
                }
            }
        }
    }

```

**Variables:**
```
{
	cart_id: 'my_cart_id',
	payment_method: 'adyen_cc',
	additional_data: {
		cc_type: 'mc',
		stateData:  JSON.stringify(onChangeData)
	}
}
```

Execute Query `placeOrder`
```graphql
    mutation placeOrder($cartId: String!) {
        placeOrder(input: { cart_id: $cartId }) @connection(key: "placeOrder") {
            order {
                order_number
            }
        }
    }
```

**Variables:**
```
{
cartId: 'my_cart_id'
}
```

**Error**
```
AdyenLoggerTest.INFO: JSON Response to Adyen:{"status":422,"errorCode":"14_006","message":"Required object 'paymentMethod' is not provided.","errorType":"validation","pspReference":"851638437550915E"} {"is_exception":false} []
``` 

I started with debugging session at `Magento\QuoteGraphQl\Model\Resolver\PlaceOrder::resolve`
he loads the payment correct and pushes it correct to Adyen logic looks like the module lost this information a plugin observer etc.

**Expected behavior**
Should be possible to place an order with `adyen_cc`

**Magento version**
2.4.3

**Plugin version**
`dev-feature/graphql-reapply`

**Screenshots**

**Comment by acampos1916** [comment] 2021-12-02 11:17
Hey @larsroettig, thanks for reaching out with this issue.

Sounds very similar to what @Bartlomiejsz reported a few weeks back. This seems related to the stateData not being added to the quote/order payment entity `additional_information` column, which should be done in the AdyenCcDataAssignObserver.php class when the `payment_method_assign_data_adyen_cc` is dispatched.

Can you verify if in your instance the `payment_method_assign_data_adyen_cc` event is dispatched and that AdyenCcDataAssignObserver.php saves the stateData with `setAdditionalInformation`?

**Comment by Bartlomiejsz** [comment] 2021-12-03 11:29
Hi @acampos1916 @larsroettig 
Since I don't have possibility these days to submit PR with changes that I'm making to make `placeOrder` work I will share it here, so you could use it if you need it quickly:
I'm adding following plugin in `graphql/di.xml`:
```
    <type name="Magento\Quote\Api\PaymentMethodManagementInterface">
        <plugin name="Namespace_Adyen::setAdyenStateData"
                type="Namespace\Adyen\Plugin\Quote\Api\PaymentMethodManagement"/>
    </type>
```
with following content:
```
<?php

declare(strict_types=1);

namespace Namespace\Adyen\Plugin\Quote\Api;

use Adyen\Payment\Api\AdyenStateDataInterface;
use Exception;
use Magento\Quote\Api\Data\PaymentInterface;
use Magento\Quote\Api\PaymentMethodManagementInterface as Subject;

class PaymentMethodManagement
{
    private AdyenStateDataInterface $adyenStateData;

    /**
     * @param AdyenStateDataInterface $adyenStateData
     */
    public function __construct(
        AdyenStateDataInterface $adyenStateData
    ) {
        $this->adyenStateData = $adyenStateData;
    }

    /**
     * @param Subject $subject
     * @param string $result
     * @param int $cartId
     * @param PaymentInterface $method
     * @return string
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function afterSet(Subject $subject, string $result, $cartId, PaymentInterface $method): string
    {
        if (strpos($method->getMethod(), 'adyen') !== 0) {
            return $result;
        }

        try {
            $this->adyenStateData->save(
                $method->getAdditionalData()['stateData'] ?? '',
                $cartId
            );

            // phpcs:ignore Magento2.CodeAnalysis.EmptyBlock.DetectedCatch
        } catch (Exception $e) {
            //
        }

        return $result;
    }
}
```

**Comment by larsroettig** [comment] 2021-12-03 11:50
@Bartlomiejsz thank you som mutch for your help i will apply and check today

**Comment by tnaber** [comment] 2021-12-15 09:01
Hi @larsroettig, did this solution solve your issue?

**Comment by larsroettig** [comment] 2021-12-15 09:06
Hi @tnaber, Solution from @Bartlomiejsz works satisfactory but don't have time to open PR this week Christmas rush, sorry

**Comment by tnaber** [comment] 2021-12-15 09:41
Of course :) Thanks for verifying, I will look into it!

**Comment by pepijnblom** [comment] 2021-12-20 10:00
We are running into this same issue and the proposed fix does not seem to solve the issue, using version 8 of the module on Magento 2.4.3-p1 with PHP 7.4

I'm also confused as to the `adyen_additional_data_cc` being used in the mutation as that is reported to not exist.

**Comment by acampos1916** [comment] 2021-12-30 14:02
Hello @pepijnblom, I believe that you tested the v8 release of the plugin, but unfortunately this feature is still not merged and released #1245. We're working on tests and adjustments to this feature, apologies for the delay.

In the meantime feel free to test and give us feedback on #1245.

**Comment by Morerice** [comment] 2022-04-07 14:28
This issue is pending more information from our side. However in the meantime, the order can be placed by chaining the mutation calls. **Updated example request:**

```graphql
mutation setPaymentMethod(
    $cartId: String!
) {
    setPaymentMethodOnCart(
        input: {
            cart_id: $cartId
            payment_method: {
                code: "adyen_cc"
                adyen_additional_data_cc: {
                    cc_type: "VI"
                    stateData:  $stateData
                }
            }    
        }
    ) {
        cart {
            selected_payment_method {
                code
                title
            }
        }
    }

    placeOrder(
        input: {
            cart_id: $cartId
        }
    ) {
        order {
            order_number
            cart_id
            adyen_payment_status {
                isFinal
                resultCode
                additionalData
                action
            }
        }
    }
}
```

**Comment by jesse-deboer** [comment] 2022-04-13 10:31
Just to be sure, this issue still exists in Adyen Payment 8.2.0 right?

**Comment by Morerice** [comment] 2022-04-13 12:13
> Just to be sure, this issue still exists in Adyen Payment 8.2.0 right?

Hi @jesse-deboer

This issue should not occur when a request similar to the example above is used.

Regards,
Jean
Adyen

**Comment by jesse-deboer** [comment] 2022-04-14 14:34
So, this would mean that you need to save the stateData to something like localStorage if there is a step after the payment method like a review step right?

Also, I can't find any documentation on `Payload JSON String with orderId, details, paymentData and threeDSAuthenticationOnly.` 

What is `details` and what is `paymentData`, where can I get this information? This is also not documented anywhere in the Headless Magento intergration docs.

**Comment by Morerice** [comment] 2022-04-21 14:57
Hi @jesse-deboer

The `paymentData` is returned by Adyen in the [paymentDetails](https://docs.adyen.com/plugins/magento-2/magento-headless-integration#handling-the-paymentsdetails-response) response.

The `details` object can generated automatically if you're using the [Adyen Web Component](https://docs.adyen.com/plugins/magento-2/magento-headless-integration#create-a-data-object). Otherwise you have to replicate it yourself based on the documentation for the [/payments](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/post/payments) endpoint.

Best regards,
Jean
Adyen

**Comment by jesse-deboer** [comment] 2022-04-21 16:04
Thanks @Morerice, combining the calls (although not the most pretty solution) worked!

I might be something wrong, but I am getting a new error though when I call the `placeOrder` mutation: `[2022-04-21 15:04:05] AdyenLoggerTest.WARNING: Attempted to get the payment status for order 2112200141. Exception: The cart isn't active. {"is_exception":false} []`

Should I ignore this and try again using `adyenPaymentStatus` or is this a bug?

**Comment by paales** [comment] 2022-06-08 10:32
@Morerice We are running into this issue as well. To communicate to the Magento backend we're using an additional graphql-mesh layer to direct calls to various backends. However the mesh will automatically split all mutations into separate calls (issue https://github.com/Urigo/graphql-mesh/issues/3454).

We are now going to apply the patch mentioned here https://github.com/Adyen/adyen-magento2/issues/1267#issuecomment-985444019

**Comment by paales** [comment] 2022-06-08 15:54
@Morerice I've confirmed that when the patch is applied it works as expected, can we perhaps get this in the module?

**Comment by Morerice** [comment] 2022-06-22 13:21
Hi @jesse-deboer,

Apologies for the late reply. This issue was fixed on v8.2.2.

Best,
Jean

**Comment by luankosaka1** [comment] 2022-07-14 12:26
I'm currently using version 6 and I'm looking to migrate to 7 or 8, but I encountered this error (error code: 14_006) when I use the setPaymentMethodOnCart mutation. I wanted to know if version 7 or 8 has another change I could use.

**Comment by Morerice** [comment] 2022-08-17 11:24
Hi @luankosaka1,

GraphQL functionality was added on v8.2.0 so we would recommend to move to at least this version.
Closing this issue since as previously mentioned we want to avoid saving the encrypted `stateData` in the database.

Regards,
Jean
Adyen

**Closed by Morerice** 2022-08-17 11:24 UTC
Labels: Bug report, Confirmed

**Comment by ali-ghanei** [comment] 2023-07-28 09:40
> This issue is pending more information from our side. However in the meantime, the order can be placed by chaining the mutation calls. **Updated example request:**
> 
> ```graphql
> mutation setPaymentMethod(
>     $cartId: String!
> ) {
>     setPaymentMethodOnCart(
>         input: {
>             cart_id: $cartId
>             payment_method: {
>                 code: "adyen_cc"
>                 adyen_additional_data_cc: {
>                     cc_type: "VI"
>                     stateData:  $stateData
>                 }
>             }    
>         }
>     ) {
>         cart {
>             selected_payment_method {
>                 code
>                 title
>             }
>         }
>     }
> 
>     placeOrder(
>         input: {
>             cart_id: $cartId
>         }
>     ) {
>         order {
>             order_number
>             cart_id
>             adyen_payment_status {
>                 isFinal
>                 resultCode
>                 additionalData
>                 action
>             }
>         }
>     }
> }
> ```
> 
> Thanks, Jean Adyen

But with this approach, we will have multiple duplicated orders if the payment status was failed, and users try different payment methods; what would be the alternative solution?

**Comment by novikor** [comment] 2023-09-28 14:24
It's a must-have to be documented somewhere. An insane amount of time and effort has been wasted before I found the reason for the error and its workaround...
