### ISSUE TITLE
Error going back from payment method using Adyen 7.0 RC2

### ISSUE THREAD

**Issue by quackpack** [Adyen/adyen-magento2#968] opened 2021-02-12 09:13 UTC
**Describe the bug**
When a user decides to go back to the store from any payment method or if they need to change their address info, returning back from the payment method the user is prompted with Magento Error screen:
![Screenshot 2021-02-12 at 09 29 09](https://user-images.githubusercontent.com/2312908/107745542-c3ff6400-6d14-11eb-862c-fc8ce01c0c16.png)

Error state: {"0":"The 1615852 Cart doesn't contain the 5533047 item."}

The same thing happens for any of our payment methods, Ideal, Klarna, Paypal etc.

**To Reproduce**
1. Go thru checkout as normal, select any payment option
2. Once you are on the payment gateway page click to go back to the store
3. Error message is shown

**Expected behavior**
Customers should expect to still see the checkout and alter contact details or change the payment method to something else.
Using Adyen 6.x this works just fine.

**Magento version**
Magento 2.3.6

**Plugin version**
7.0 RC2

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OSx

**Additional context**
Works fine on Adyen 6.x version.

**Comment by acampos1916** [comment] 2021-02-12 10:06
Hello @quackpack thanks for opening this issue.

Unfortunately I was not able to reproduce it with this setup and steps. I believe the exception might have logged more information about the stack call, could you share it here omitting any sensible data?

**Comment by brightonmike** [comment] 2021-02-24 08:57
@acampos1916 We are having similar problems.

Seems to concern line 160 of `controller/process/result.php`. 

I have attached our error log below. We don't get the issue locally, only on Magento cloud, so it's a real tricky one to figure out. It could be different from this original issue but I've a feeling there's a connection.


```
{"0":"No such entity with cartId = 1628","1":"#1 Magento\\Quote\\Model\\QuoteRepository->loadQuote() called at [vendor\/magento\/module-quote\/Model\/QuoteRepository.php:136]\n#2 Magento\\Quote\\Model\\QuoteRepository->get() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#3 Magento\\Quote\\Model\\QuoteRepository\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#4 Magento\\Quote\\Model\\QuoteRepository\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#5 Magento\\Quote\\Model\\QuoteRepository\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Quote\/Model\/QuoteRepository\/Interceptor.php:23]\n#6 Magento\\Quote\\Model\\QuoteRepository\\Interceptor->get() called at [vendor\/magento\/module-quote\/Model\/QuoteRepository.php:193]\n#7 Magento\\Quote\\Model\\QuoteRepository->save() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#8 Magento\\Quote\\Model\\QuoteRepository\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#9 Magento\\Quote\\Model\\QuoteRepository\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#10 Magento\\Quote\\Model\\QuoteRepository\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Quote\/Model\/QuoteRepository\/Interceptor.php:59]\n#11 Magento\\Quote\\Model\\QuoteRepository\\Interceptor->save() called at [vendor\/adyen\/module-payment\/Controller\/Process\/Result.php:160]\n#12 Adyen\\Payment\\Controller\\Process\\Result->execute() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#13 Adyen\\Payment\\Controller\\Process\\Result\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#14 Adyen\\Payment\\Controller\\Process\\Result\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/App\/Action\/Plugin\/ActionFlagNoDispatchPlugin.php:51]\n#15 Magento\\Framework\\App\\Action\\Plugin\\ActionFlagNoDispatchPlugin->aroundExecute() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#16 Adyen\\Payment\\Controller\\Process\\Result\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#17 Adyen\\Payment\\Controller\\Process\\Result\\Interceptor->___callPlugins() called at [generated\/code\/Adyen\/Payment\/Controller\/Process\/Result\/Interceptor.php:23]\n#18 Adyen\\Payment\\Controller\\Process\\Result\\Interceptor->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:111]\n#19 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#20 Adyen\\Payment\\Controller\\Process\\Result\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#21 Adyen\\Payment\\Controller\\Process\\Result\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#22 Adyen\\Payment\\Controller\\Process\\Result\\Interceptor->___callPlugins() called at [generated\/code\/Adyen\/Payment\/Controller\/Process\/Result\/Interceptor.php:32]\n#23 Adyen\\Payment\\Controller\\Process\\Result\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:186]\n#24 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:118]\n#25 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#26 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#27 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-store\/App\/FrontController\/Plugin\/RequestPreprocessor.php:99]\n#28 Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#29 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/fastly\/magento2\/Model\/FrontControllerPlugin.php:131]\n#30 Fastly\\Cdn\\Model\\FrontControllerPlugin->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#31 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php:71]\n#32 Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#33 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#34 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:23]\n#35 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:116]\n#36 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:263]\n#37 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:29]\n","url":"\/adyen\/process\/result\/?merchantReference=000&redirectResult=AAA","script_name":"\/index.php","report_id":"9ff71a85713f0d924da1dfc96af61578e7fe5fdb64386cea09db6d3218b5a879"}
```

**Comment by acampos1916** [comment] 2021-02-25 08:35
Thanks for the additional info @brightonmike,

I see that there's some recently introduced code there to save the quote with a new ID and it might be failing for some reason. We merged a [PR](https://github.com/Adyen/adyen-magento2/pull/959) into develop that [replaces that bit of code with a cloned quote](https://github.com/Adyen/adyen-magento2/pull/959/files#diff-b94e5bd4a2ef8442885afde3f17adc9a8a5a9c06e89f08b4a53a8a84831d07b2L133-L152) similar to how is done in parts of the Magento core and native modules. We should be merging this and some other changes into 7.0.0-rc.2 soon so you can try it out in Magento Cloud.

Best,
Ángel

**Comment by brightonmike** [comment] 2021-02-25 08:49
@acampos1916 That sounds really positive. I wasn't getting this issue locally where I hadn't run composer in a while so it does sound like that's the change connected to the issue. Thank you for clarifying!

**Closed** 2021-04-09 12:49 UTC
Labels: Bug report
