### ISSUE TITLE
textboxes for api key for test , notification password etc are disabled in the magento 2 configuration page.

### ISSUE THREAD

**Issue by shogunjames** [Adyen/adyen-magento2#914] opened 2020-12-17 17:02 UTC
**Describe the bug**
In the magento2 admin side the text boxes for entering the details are disabled. Please see the attachment.

Could you please help me in this.
![adyen_admin](https://user-images.githubusercontent.com/11349118/102518832-c8622480-40b7-11eb-8879-419e6e943c2a.png)

**Comment by acampos1916** [comment] 2020-12-18 15:50
Hello @shogunjames,

The plugin uses `type="obscure"` for those fields in the config XML https://github.com/Adyen/adyen-magento2/blob/master/etc/adminhtml/system/adyen_required_settings.xml#L46 but no frontend model or CSS is used, could you check if there's a CSS rule from another module affecting the obscure fields in your Magento instance?

You can try installing the plugin in a clean Magento instance to try to reproduce the issue.

Best,
Ángel

**Comment by cyattilakiss** [comment] 2021-06-09 11:18
Hi @shogunjames ,

I am going to close this issue now because we are not able to reproduce it but please feel free to reopen it in case it's still an ongoing problem maybe providing some more info that might cause this.

Best,
Attila
Adyen

**Closed by cyattilakiss** 2021-06-09 11:18 UTC
Labels: Bug report, Issue: Cannot Reproduce, Issue: Waiting for response
