### ISSUE TITLE
Card expire date bug

### ISSUE THREAD

**Issue by AndyHickinBellamy-Pozzani** [Adyen/adyen-magento2#1678] opened 2022-08-24 08:12 UTC
Once the customers on the card payment section of checkout, there's a couple of bugs in the expire date.
Number keypad does not work but the numbers above the letters do.
Enter a zero (0) and another zero is automatically appended and then the forward slash (/) so the month looks like 00/.
This is happening in desktop versions of Chrome, Edge, Opera and Firefox.

**Comment by Morerice** [comment] 2022-08-24 11:19
Hi @AndyHickinBellamy-Pozzani

Unfortunately I was unable to replicate this issue. On my end when I entered a zero from the keypad, nothing else was automatically added. Also when I then attempted to manually enter another zero, one was added instead (since you obviously can't have 00/). 

Could you please provide us with the plugin version you're currently using?

Thanks,
Jean
Adyen

**Comment by AndyHickinBellamy-Pozzani** [comment] 2022-08-25 08:59
Hi @Morerice 

Oh, how odd.

We're using Magento 2.3.5-p1 and Adyen Magento Extension 8.1.1

**Comment by Morerice** [comment] 2022-08-25 11:28
Hi @AndyHickinBellamy-Pozzani

Unfortunately I was unable to reproduce the issue on 8.1.1 as well.
I'm closing this issue since strictly speaking, this is not related to the Magento 2 module.

To give a bit more background, the Magento 2 module uses the [Adyen Card Component](https://docs.adyen.com/payment-methods/cards/web-component) for any input validation. Hence, I would recommend redirecting your question to [this repository](https://github.com/Adyen/adyen-web).

However, please ensure that you're able to replicate this issue on a clean Magento 2 instance before doing so.

Thanks,
Jean
Adyen

**Closed by Morerice** 2022-08-25 11:28 UTC
Labels: Bug report

**Comment by AndyHickinBellamy-Pozzani** [comment] 2022-08-25 11:36
Ok, thank you
