### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by ajpevers** [Adyen/adyen-magento2#204] opened 2017-10-25 11:48 UTC
Same problem as in #107

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '8815088272901681'
for key 'ADYEN_ORDER_PAYMENT_PSPREFERENCE', query was: INSERT INTO
`adyen_order_payment` (`pspreference`, `merchant_reference`, `payment_id`,
`payment_method`, `amount`, `total_refunded`, `created_at`, `updated_at`) VALUES
(?, ?, ?, ?, ?, ?, '2017-10-24 12:20:16', '2017-10-24 12:20:16')
```

@rikterbeek I will let you know as soon as I find out if errors are occurring before this message and what the end result of the payment is.

This is with Magento 2.1.9 and adyen/module-payment 2.1.2

**Comment by ajpevers** [comment] 2017-10-25 11:57
These are test payments:

There are logs containing this PSPReference in 3 files:
var/log/adyen/result.log (1x)
var/log/adyen/cronjob.log (2x)
var/log/adyen/notification.log (2x)

@rikterbeek does this mean that 2 notifications are received by the webshop concerning the same payment?

var/log/adyen/result.log:
```
[2017-10-24 06:41:34] AdyenLoggerTest.ADYEN_RESULT: Array
(
    [authResult] => AUTHORISED
    [merchantReference] => 13110152
    [merchantSig] => EwcQmu6R3nu5E4qkphXwEIlpWp1QTrKFWBSi4d5xv84=
    [paymentMethod] => ideal
    [pspReference] => 8815088272901681
    [shopperLocale] => nl_NL
    [skinCode] => EIyhP2o0
)
 {"is_exception":false} []
[2017-10-24 06:41:34] AdyenLoggerTest.ADYEN_RESULT: Processing ResultUrl {"is_exception":false} []
[2017-10-24 06:41:34] AdyenLoggerTest.ADYEN_RESULT: Updating the order {"is_exception":false} []
[2017-10-24 06:41:34] AdyenLoggerTest.ADYEN_RESULT: Do nothing wait for the notification {"is_exception":false} []
```

2 consecutive entries in var/log/adyen/cronjob.log:
```
[2017-10-24 12:20:14] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Processing notification 443 {"is_exception":false} []
[2017-10-24 12:20:14] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Array
(
    [entity_id] => 443
    [pspreference] => 8815088272901681
    [merchant_reference] => 13110152
    [event_code] => AUTHORISATION
    [success] => true
    [payment_method] => ideal
    [amount_value] => 12385
    [amount_currency] => EUR
    [live] => false
    [done] => 0
    [processing] => 1
    [created_at] => 2017-10-24 06:41:34
)
 {"is_exception":false} []
[2017-10-24 12:20:14] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Created comment history for this notification {"is_exception":false} []
[2017-10-24 12:20:14] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Updating the Adyen attributes of the order {"is_exception":false} []
[2017-10-24 12:20:14] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Processing the notification {"is_exception":false} []
[2017-10-24 12:20:14] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Authorisation of the order {"is_exception":false} []
[2017-10-24 12:20:14] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Order status is changed to Pre-authorised status, status is pending {"is_exception":false} []
[2017-10-24 12:20:14] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Prepare invoice for order {"is_exception":false} []
[2017-10-24 12:20:14] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: This payment method does not allow manual capture {"is_exception":false} []
[2017-10-24 12:20:14] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Validate if AUTHORISATION notification has the total amount of the order {"is_exception":false} []
[2017-10-24 12:20:14] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: The grandtotal amount is 12385 and the total order amount that is authorised is: 12385 {"is_exception":false} []
[2017-10-24 12:20:14] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: AUTHORISATION has the full amount {"is_exception":false} []
[2017-10-24 12:20:14] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Creating invoice for order {"is_exception":false} []
[2017-10-24 12:20:15] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: This payment method does not allow manual capture {"is_exception":false} []
[2017-10-24 12:20:15] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Created invoice {"is_exception":false} []
[2017-10-24 12:20:15] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Set order to authorised {"is_exception":false} []
[2017-10-24 12:20:15] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Order status is changed to authorised status, status is processing {"is_exception":false} []
[2017-10-24 12:20:16] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Send orderconfirmation email to shopper {"is_exception":false} []
[2017-10-24 12:20:16] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Notification 443 is processed {"is_exception":false} []
[2017-10-24 12:20:16] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Processing notification 444 {"is_exception":false} []
[2017-10-24 12:20:16] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Array
(
    [entity_id] => 444
    [pspreference] => 8815088272901681
    [merchant_reference] => 13110152
    [event_code] => AUTHORISATION
    [success] => true
    [payment_method] => ideal
    [amount_value] => 12385
    [amount_currency] => EUR
    [live] => false
    [done] => 0
    [processing] => 1
    [created_at] => 2017-10-24 06:46:43
)
 {"is_exception":false} []
[2017-10-24 12:20:16] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Created comment history for this notification {"is_exception":false} []
[2017-10-24 12:20:16] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Updating the Adyen attributes of the order {"is_exception":false} []
[2017-10-24 12:20:16] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Processing the notification {"is_exception":false} []
[2017-10-24 12:20:16] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Authorisation of the order {"is_exception":false} []
[2017-10-24 12:20:16] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Order status is changed to Pre-authorised status, status is pending {"is_exception":false} []
[2017-10-24 12:20:16] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Prepare invoice for order {"is_exception":false} []
[2017-10-24 12:20:16] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: This payment method does not allow manual capture {"is_exception":false} []
```

2 consecutive entries in var/log/adyen/notification.log
```
[2017-10-24 06:41:34] AdyenLoggerTest.ADYEN_NOTIFICATION: The content of the notification is: Array
(
    [live] => false
    [notificationItems] => Array
        (
            [0] => Array
                (
                    [NotificationRequestItem] => Array
                        (
                            [amount] => Array
                                (
                                    [currency] => EUR
                                    [value] => 12385
                                )

                            [eventCode] => AUTHORISATION
                            [eventDate] => 2017-10-24T08:41:34+02:00
                            [merchantAccountCode] => ScoreNL
                            [merchantReference] => 13110152
                            [operations] => Array
                                (
                                    [0] => REFUND
                                )

                            [paymentMethod] => ideal
                            [pspReference] => 8815088272901681
                            [reason] =>
                            [success] => true
                        )

                )

        )

)
 {"is_exception":false} []
[2017-10-24 06:41:34] AdyenLoggerTest.ADYEN_NOTIFICATION: The result is accepted {"is_exception":false} []
[2017-10-24 06:46:43] AdyenLoggerTest.ADYEN_NOTIFICATION: The content of the notification is: Array
(
    [live] => false
    [notificationItems] => Array
        (
            [0] => Array
                (
                    [NotificationRequestItem] => Array
                        (
                            [amount] => Array
                                (
                                    [currency] => EUR
                                    [value] => 12385
                                )

                            [eventCode] => AUTHORISATION
                            [eventDate] => 2017-10-24T08:46:43+02:00
                            [merchantAccountCode] => ScoreNL
                            [merchantReference] => 13110152
                            [operations] => Array
                                (
                                    [0] => REFUND
                                )

                            [paymentMethod] => ideal
                            [pspReference] => 8815088272901681
                            [reason] =>
                            [success] => true
                        )

                )

        )

)
 {"is_exception":false} []
[2017-10-24 06:46:43] AdyenLoggerTest.ADYEN_NOTIFICATION: The result is accepted {"is_exception":false} []
```

**Comment by ajpevers** [comment] 2017-10-25 12:04
The order status is processing and an invoice is created and paid.

![screen shot 2017-10-25 at 6 03 40 pm](https://user-images.githubusercontent.com/1489129/31997750-e8b7a2d4-b9ae-11e7-90c2-4eb73722b83a.png)

**Comment by ajpevers** [comment] 2017-10-25 12:12
There are 2 entries in the adyen_notification table:

| entity_id | pspreference | original_reference | merchant_reference | event_code | success | payment_method | amount_value | amount_currency | reason | live | additional_data | done | processing | created_at | updated_at |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| 443 | 8815088272901681 | NULL | 13110152 | AUTHORISATION | true | ideal | 12385 | EUR | NULL | false | NULL | 1 | 0 | 2017-10-24 06:41:34 | 2017-10-24 12:20:16 |
| 444 | 8815088272901681 | NULL | 13110152 | AUTHORISATION | true | ideal | 12385 | EUR | NULL | false | NULL | 0 | 1 | 2017-10-24 06:46:43 | 2017-10-24 12:20:14 |

**Comment by 50xSolutions** [comment] 2017-10-31 15:39
Greetings @ajpevers, @rikterbeek 

We are having the exact same issue (latest release 2.1.2) Magento EE 2.1.7

We also get in our adyen_notification table 2 entries for the same psp, but the issue is causing us additional problems because notifications **after** the one with double entry are not getting processed. 

 ```

[2017-10-22 12:08:06] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Processing notification 33223 {"is_exception":false} []
[2017-10-22 12:08:06] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Array
    [created_at] => 2017-10-22 12:06:21
[2017-10-22 12:08:06] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Created comment history for this notification {"is_exception":false} []
[2017-10-22 12:08:07] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Updating the Adyen attributes of the order {"is_exception":false} []
[2017-10-22 12:08:07] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Processing the notification {"is_exception":false} []
[2017-10-22 12:08:07] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Authorisation of the order {"is_exception":false} []
[2017-10-22 12:08:07] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Order status is changed to Pre-authorised status, status is processing {"is_exception":false} []
[2017-10-22 12:08:07] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Prepare invoice for order {"is_exception":false} []
[2017-10-22 12:08:07] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: This payment method does not allow manual capture {"is_exception":false} []

```

In this example, notification 33223 had 2 entries in the database but our issue is with the next one that came in the array, due to the error, the rest of the notifications do not get invoiced and their orders have already been set to processing.

```
entity_id	pspreference	original_reference	merchant_reference	event_code	success	payment_method	amount_value	amount_currency	reason	live	additional_data	done	processing	created_at	updated_at
33222	PSPXXXXXXX4461	NULL	P000108081	AUTHORISATION	true	ideal	5922	EUR	NULL	true	NULL	1	0	2017-10-22 12:06:20	2017-10-22 12:08:06
33223	PSPXXXXXXX4461	NULL	P000108081	AUTHORISATION	true	ideal	5922	EUR	NULL	true	NULL	0	1	2017-10-22 12:06:21	2017-10-22 12:08:03
33224	PSPXXXXXXX7160	NULL	B000007007	AUTHORISATION	true	ideal	3498	EUR	NULL	true	NULL	0	1	2017-10-22 12:06:47	2017-10-22 12:08:03`

```

**Comment by rikterbeek** [comment] 2017-11-01 13:20
Hi @ajpevers @50xSolutions,

If duplicate notifications are received it should not save them into the database.
This is done here: https://github.com/Adyen/adyen-magento2/blob/develop/Controller/Process/Json.php#L285-L296
Probably because the timespan is just a couple of seconds the other thread is not done yet.
What we need to add is in the cronjob as well a check if the payment was already executed before. If this is the case it should put it to done and ignore it. We will look into this and provide a fix.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment] 2017-11-03 08:18
Hi @ajpevers @50xSolutions,

See the PR above this should fix these issues.

Regards,
Rik
Adyen

**Comment by ajpevers** [comment] 2017-11-08 08:35
Thanks @rikterbeek 

I'll let you know when the patch is applied and how it performs.

**Comment by rikterbeek** [comment] 2018-01-18 07:33
Hi @ajpevers,

This is fixed in the hotfix release above and newer versions. The constraint will never happen because it will only execute it once because we have a duplicate check implemented. Closing the issue.

Regards,
Rik
Adyen

**Closed by rikterbeek** 2018-01-18 07:33 UTC
