### ISSUE TITLE
[PW-5546] Error: Call to undefined method PayPal\Braintree\Gateway\Data\Order\OrderAdapter

### ISSUE THREAD

**Issue by draper87** [Adyen/adyen-magento2#1168] opened 2021-10-07 09:10 UTC
**Describe the bug**
On a clean install of Magento 2.4.3 with no other third-party plugins other than Adyen 7.2.0, when we try to place an order with Adyen the result is a generic error message "Something went wrong with your request. Please try again later.". After checked the log file var/log/system.log we've discovered this:

`main.CRITICAL: Error: Call to undefined method PayPal\Braintree\Gateway\Data\Order\OrderAdapter::getQuoteId() in /var/www/html/vendor/adyen/module-payment/Gateway/Response/StateDataCleanupHandler.php:48
Stack trace:
`

After checking di.xml of Adyen It seems to me that both Adyen and Braintree are using a preference over the same Class
`Magento\Payment\Gateway\Data\Order\OrderAdapter`

I'm not sure what's going on here, how can I solve this without uninstall Braintree (actually I tried to disable Braintree's modules and Adyen stop to work).

**To Reproduce**
1. After adding a product to cart go to Checkout and fill customers data.
2. On payment page fill credit card number, expiry Date and CVC number.
3. Click on Place Order.

**Expected behavior**
I'm expecting to place the order without getting any error.

**Magento version**
2.4.3

**Plugin version**
7.2.0 (test mode)

**Screenshots**
![Screenshot from 2021-10-07 10-51-24](https://user-images.githubusercontent.com/61914749/136352053-bd637f7b-8282-4b30-a7cd-1852c6ce93cc.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome 94

**Comment by acampos1916** [comment] 2021-10-07 11:47
Hello @draper87, thank you for this report. Maybe this could happen if the Braintree module is loaded after Adyen's, even if disabled. We are investigating this to find a different solution to getting the quoteId.

**Comment by Djohn12** [comment] 2022-03-29 10:36
Hello,

I can see this issue is closed but we're still reproducing the bug with backend orders on a magento 2.4.3-p1 instance using adyen/module-payment 8.1.1

Error log is : 
```
Error: Call to undefined method PayPal\Braintree\Gateway\Data\Order\OrderAdapter::getQuoteId() in /magento_code/vendor/adyen/module-payment/Gateway/Request/CcBackendAuthorizationDataBuilder.php:54
```

Do you have any workaround or fix for this issue ?
Thanks in advance

**Comment by igi8819** [comment] 2022-06-02 14:06
I can still replicate this issue on adyen/moudle-payment:8.2.3

**Comment by vahir2016** [comment] 2022-06-07 08:44
Hello,

Same issue with Adyen 8.2.3 and  Magento EE 2.4.3.

**Comment by Morerice** [comment] 2022-06-07 14:33
Hi guys,

Apologies for the delay. I am re-opening this issue since it seems that it is occurring more frequently. Based on the previous comments it seems that it is occurring exclusively on Magento v2.4.3.

Best regards,
Jean
Adyen

**Closed** 2022-06-30 09:12 UTC
Labels: Bug report

**Comment by Winfle** [comment] 2023-03-27 21:04
This issue appears at 8.17.0

**Comment by lrotherfield-function** [comment] 2023-05-01 14:56
@Morerice as reported by @Winfle, I too am seeing this on 8.18 when trying to checkout with a 3DS enabled card stored in vault.

The change in 8.17 causes this issue: https://github.com/Adyen/adyen-magento2/blob/b8c9105b80ebd5b42c3023d5e91b88f8ae6e3426/Gateway/Request/RecurringVaultDataBuilder.php#L51

**Comment by lrotherfield-function** [comment] 2023-05-11 11:30
@acampos1916 Do you need me to open a new issue for this now that it is reintroduced in 8.17 and 8.18?
