### ISSUE TITLE
[PW-7088][PW-7036] Order status of newly created order struck at payment review, the admin configuration for adyen is pending, checked in 8.3.0,8.3.2,8.3.3 all versions

### ISSUE THREAD

**Issue by binuconcept** [Adyen/adyen-magento2#1660] opened 2022-08-10 16:17 UTC
Making your own contribution is easy, encouraged and greatly appreciated! We will put effort into reviewing and merging your PR quickly. For more info, please refer to the contribution guidelines: https://github.com/Adyen/adyen-magento2/blob/develop/CONTRIBUTING.md

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Magento version**
[e.g. 2.4.1]

**Plugin version**
[e.g. 6.6.8]

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devetus** [comment] 2022-08-11 11:17
@Morerice @RokPopov 
could be linked with the critical cron capture issue we've found after upgrading to v8.3.3
```
[2022-08-11 10:59:11] report.CRITICAL: Error when running a cron job {"exception":"[object] (RuntimeException(code: 0): Error when running a cron job at /vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:368, Error(code: 0): Call to undefined method Adyen\\Payment\\Helper\\Data::isPaymentMethodOpenInvoiceMethodValidForAutoCapture() at /vendor/adyen/module-payment/Helper/PaymentMethods.php:660)"} []
```
there is no `isPaymentMethodOpenInvoiceMethodValidForAutoCapture` method in the helper which is failing all capture updates and invoices in Magento for pending orders.

**Comment by devetus** [comment] 2022-08-11 11:21
looks like the method was renamed to `isPaymentMethodOpenInvoiceMethod` but not updated in all places.

**Comment by AlexandrosMor** [comment] 2022-08-12 07:48
It is fixed with the 8.3.5 release

**Comment by binuconcept** [comment] 2022-08-12 12:51
Adyen Payment 8.3.5 :  cross-checked, the Magento admin configuration of Adyen payemnt we are setting for order creation is **pending** but still it's going to **payment review.**
Cross-checked all versions 8.3.0,8.3.2,8.3.3, and 8.3.5 as well still the issue is there.

**Comment by michaelpaul** [comment] 2022-08-16 09:53
Hello @binuconcept, thanks for reporting this issue and testing again on the latest release. I've created another internal follow up ticket for it. Feel free to edit this issue's description field with your findings (e.g **steps to reproduce, versions, log snippets**), that helps a lot on fixing the problem.

**Comment by Morerice** [comment] 2022-08-29 09:34
Hi,

Issue was caused by a third party module, tasked with providing fraud prevention. For future reference we recommend using Adyen's [Risk Management](https://docs.adyen.com/risk-management) functionality for fraud prevention.

Thanks,
Jean
Adyen

**Closed by Morerice** 2022-08-29 09:34 UTC
Labels: Bug report

**Comment by GamesmenJordan** [comment] 2022-09-08 02:34
> Issue was caused by a third party module, tasked with providing fraud prevention.

Can you specify which module? Wondering if it is the same module we use (Signifyd)

**Comment by Morerice** [comment] 2022-09-08 08:16
> > Issue was caused by a third party module, tasked with providing fraud prevention.
> 
> Can you specify which module? Wondering if it is the same module we use (Signifyd)

Hi @GamesmenJordan,

The module was Forter.

Regards,
Jean
Adyen

**Comment by binuconcept** [comment] 2022-09-08 17:46
Hi @GamesmenJordan 
It's an issue with Adyen(the module checked all the latest modules this issue is their), Adyen team's future requests will fix this issue. (this is the response received from Adyen technical members)

We may need to add some patches from our end to move forward.

It's not because of Forter. If you are not using forter also you can replicate this issue.
