### ISSUE TITLE
Adyen\Payment\Logger\AdyenLogger not compatible with version 2.7.0 of Monolog\Logger

### ISSUE THREAD

**Issue by aligent-lturner** [Adyen/adyen-magento2#1576] opened 2022-06-16 23:55 UTC
**Describe the bug**
Version 2.7.0 of `monolog/monolog` introduced a new parameter to its `addRecord` function:
https://github.com/Seldaek/monolog/pull/1682
As such, the `addRecord` function of `\Adyen\Payment\Logger\AdyenLogger` is not compatible with this, and results in fatal errors being thrown:

```
Fatal error: Declaration of Adyen\Payment\Logger\AdyenLogger::addRecord($level, $message, array $context = []): bool must be compatible with Monolog\Logger::addRecord(int $level, string $message, array $context = [], ?Monolog\DateTimeImmutable $datetime = null): bool in /app/vendor/adyen/module-payment/Logger/AdyenLogger.php on line 89
```

**To Reproduce**
1. Run `bin/magento setup:upgrade` or `bin/magento setup:di:compile` (possibly other commands also)

**Expected behavior**
The command completes successfully.

**Magento version**
2.4.4

**Plugin version**
8.2.4 (but would be an issue with any v7 or v8 release)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Additional context**
`monolog/monolog` is not required in `composer.json`, despite being used directly by this module.
Either `monolog/monolog` needs to be required with a stricter version requirement (e.g. "~2.6.0"), or the code needs to be rewritten to handle both cases.

**Comment by candemiralp** [comment] 2022-06-17 08:38
Hello @aligent-lturner,

Thanks for opening this issue. The issue has already been fixed in the new releases v8.2.5 and v7.3.10. Could you please upgrade to the latest version and try again? If the issue is persistent you can always open the issue again.

Since issue was solved, I am closing this one.

Best Regards,
Can

**Closed by candemiralp** 2022-06-17 08:38 UTC
Labels: Bug report
