### ISSUE TITLE
[PW-1941] Payment form (hpp) gets cleared when change city

### ISSUE THREAD

**Issue by vovayatsyuk** [Adyen/adyen-magento2#563] opened 2019-10-30 14:28 UTC
**Magento version**: 2.3.2
**Plugin version**: 4.4.0

**Description**

1. Navigate to checkout and proceed to the payment step.
2. Select "Klarna Faktura" payment method and fill "Personal number" field.
3. Uncheck "use shipping address" checkbox and change City to something else.
4. Update billing address.
5. "Personal number" field gets cleared.

This issue happens with all "hpp" methods. ("Bankbetalning" for example.)

p.d. In fact, you can even press "Cancel" button, just wait a second after that:

![hpp](https://user-images.githubusercontent.com/306080/67866752-17ef3500-fb32-11e9-9d41-805f7c1394ed.gif)

You can also run this code snippet in browser console and form will be cleared too:

```js
require(['Magento_Checkout/js/model/quote'], function(quote) {
	quote.shippingAddress(quote.shippingAddress())
});
```

**Comment by cyattilakiss** [comment] 2019-11-07 13:33
Hi @vovayatsyuk ,

Thank you for raising this issue, we are going to pick this up into our backlog.
This should only happen if the shipping address is changed and not the billing address.

Best,
Attila
Adyen

**Comment by vovayatsyuk** [comment] 2019-11-07 13:56
@cyattilakiss is it possible to remove this behavior for both addresses? Asking because it will fix conflict with the firecheckout module.

In short, firecheckout calls for standard `shipping.validateShippingInformation` method when you press 'Place Order'. Unfortunately `validateShippingInformation` updates shipping address as well :(. 

Here is the part of validateShippingInformation method:

https://github.com/magento/magento2/blob/7aa94564d85e408baea01abc5315a0441401c375/app/code/Magento/Checkout/view/frontend/web/js/view/shipping.js#L324-324

```
selectShippingAddress(shippingAddress);
```

This results in cleared hpp forms when user pressed "Place Order".

**Comment by othuress** [comment] 2019-12-17 08:17
@cyattilakiss @rikterbeek  I would love your comment on @vovayatsyuk question.
Thank you
Ola

**Comment by cyattilakiss** [comment] 2019-12-17 13:11
Hi @vovayatsyuk , @othuress ,

We are still assessing what approach would be the best to fix the conflict with the one step checkout modules while keeping our multi payment method functionality. Sorry for the delay on this, we need to change some basic flows and we are still planning it. The item is in our backlog, will be refined and picked up as soon as we can.

Thank you for your patience and happy holidays!
Best,
Attila
Adyen

**Comment by lukaszlempicki-sii** [comment] 2020-04-23 13:51
@cyattilakiss How is it going with fixing this issue?

**Comment by AlexandrosMor** [comment] 2020-07-29 09:14
Hello @vovayatsyuk,

It is not possible to reproduce the issue with 6.3.0. Could please test with the latest one ?

kind regards,
Alexandros

**Comment by othuress** [comment] 2020-07-29 10:01
Hello @AlexandrosMor ,

could it be this one? Request #749667

**Comment by AlexandrosMor** [comment] 2020-07-29 10:31
Hello @othuress.

Can you be more specific about the number ? Is it a github PR ?

**Comment by othuress** [comment] 2020-07-29 11:38
@AlexandrosMor No it is adyen ticet

**Comment by floorjubbega** [comment] 2020-10-21 09:19
Duplicate of #561

**Closed by floorjubbega** 2020-10-21 09:19 UTC
Labels: Bug report
