### ISSUE TITLE
[PW-6450] Headless integration doesn't support Invoice lines (Klarna not supported)

### ISSUE THREAD

**Issue by Fifciu** [Adyen/adyen-magento2#1368] opened 2022-02-17 10:13 UTC
**Describe the bug**
I want to support Klarna in my Headless Adyen Magento2 integration. I've added `shopperEmail` to the payload like that:
```js
 paymentMethod: {
      method: 'adyen_cc',
      additional_data: {
        cc_type: CC_TYPES[componentData.paymentMethod.brand] || '',
        guestEmail,
        store_cc: componentData.storePaymentMethod,
        stateData: JSON.stringify({
          ...componentData,
          shopperEmail: email
        })
      }
    }
```

Unfortunately, I am getting `Error with payment method please select a different payment method.` from Adyen. After check, in Adyen's dashboard, I've found the acquirer response is `Refused (113 No InvoiceLines provided)` which means ["Invoice lines are missing"](https://docs.adyen.com/development-resources/error-codes#113-no-invoicelines-provided). 

I've checked the module code and it has:
```php
public function isPaymentMethodOpenInvoiceMethod($paymentMethod)
    {
        if (strpos($paymentMethod, 'afterpay') !== false ||
            strpos($paymentMethod, 'klarna') !== false ||
            strpos($paymentMethod, 'ratepay') !== false ||
            strpos($paymentMethod, 'facilypay_') !== false ||
            strpos($paymentMethod, 'affirm') !== false ||
            strpos($paymentMethod, 'clearpay') !== false ||
            strpos($paymentMethod, 'zip') !== false ||
            strpos($paymentMethod, 'paybright') !== false
        ) {
            return true;
        }

        return false;
    }
```

And I see the logic that should apply open invoice data to the request. However, it doesn't work in headless flow (I am trying `Klarna Pay Over Time` for US, with $, and hiting POST /payment-information endpoint). It gives the error.

**Expected behavior**
adyen-magento2 plugin adds lineItems to the request

**Magento version**
2.4.3

**Plugin version**
8.1.0

**Comment by jonathanribas** [comment] 2022-02-21 12:56
Hi @acampos1916, I hope you are doing well!
We are very interested in a fix for this one!

**Comment by tnaber** [comment] 2022-02-23 14:17
Hi @Fifciu,

Thank you for opening this issue. We will further investigate. 
If we understand you correctly, the function `isPaymentMethodOpenInvoiceMethod` returns false for you?

Cheers,
Titus

**Comment by Fifciu** [comment] 2022-02-23 14:27
@tnaber 
I am not really a PHP Developer but based on code analysis I think it returns true which is especially weird because the plugin is not adding LineItems to the payload.

**Comment by tnaber** [comment] 2022-03-23 14:52
Hi @Fifciu,

Is this only a problem for Klarna Pay Over Time, or also for Klarna Pay Later, Klarna Pay Now and other openinvoice methods, e.g. afterpay?

**Comment by tnaber** [comment] 2022-03-30 12:42
Hi @Fifciu and @jonathanribas,

Klarna is part an hpp method, thus setting "method": "adyen_hpp" instead of "method": "adyen_cc" resolves the issue on my side. Can you verify whether this also solves your problem?

Cheers,
Titus

**Comment by Fifciu** [comment] 2022-03-31 11:19
Hello @tnaber ,
I am going to check this but... in meanwhile, how can I figure out when should I set the method to `adyen_hp`p and when to `adyen_cc`? What about other types like `adyen_oneclick`, `adyen_pos_cloud`, and `adyen_boleto`

**Comment by tnaber** [comment] 2022-03-31 11:33
Hi @Fifciu,

I feel like the documentation might come a bit short on this, I will be looking into it and come back to you. 
In the meantime, this is what my body looks like for when testing for klarna.

```
{
    "cart_id":<id>,
    "paymentMethod": {
        "method": "adyen_hpp",
        "additional_data": {
            "brand_code": "klarna",
           "stateData": "{\"paymentMethod\":{\"type\":\"klarna\"},\"clientStateDataIndicator\":true}"
        }
    }
}
```

 Hope this helps!

**Comment by Fifciu** [comment] 2022-03-31 11:41
`adyen_cc` looks to work fine also for Paypal. Would it be possible to provide map like `paymentMethod` -> `adyen_<cc/oneclick/hpp/boleto>`?

**Comment by Fifciu** [comment] 2022-03-31 12:36
I am trying to use `klarna_account` with payload like:
```
{
cartId: 'RSBXhodZzI1IUU2XREA8tf2bBDRTfreS',
  email: 'filip*****@gmail.com',
  billingAddress: {
    city: 'Radom',
    countryId: 'US',
    firstname: '***',
    lastname: '****',
    postcode: '26-600',
    region: 'Armed Forces Pacific',
    regionCode: 'AP',
    regionId: 11,
    street: [
      'ul. ******88, 1',
      '11'
    ],
    telephone: '+4879*******'
  },
  paymentMethod: {
    method: 'adyen_hpp',
    additional_data: {
      stateData: '{"riskData":{"clientData":"...someHash..."},"paymentMethod":{"type":"klarna_account"},"clientStateDataIndicator":true,"shopperEmail":"filip.jdrasik@gmail.com"}'
    }
  }
}
```

But I am still getting 113 Error - Invoice lines are missing...
PSP Reference: MRHGXFSCCGNG5S82

**Comment by tnaber** [comment] 2022-04-04 09:01
Hi @Fifciu,

Regarding your first suggestion, such a mapping is currently not available. We agree this would be a valuable contribution and will be looking into this in the future.

Regarding the payload you sent, in additional data I see you are not specifying a 'brand_code' like in the body I sent. Could you verify whether the exact body I sent (with an active cart_id) returns a proper response for you? Currently it is hard for me to determine whether the problem is caused by a bug or by the wrong fields being received.

Cheers,
Titus

**Comment by marc-arnoult** [comment] 2022-04-04 09:09
Hi @Fifciu,
I'm currently working with @jonathanribas with the VSF Integration Magento2.

Right now, i'm testing https://docs.vuestorefront.io/adyen/magento2/guide/introduction.html . After a debug session, i modified the payload send to the `payment-information` endpoint.

Here what's it look like :
```
{
    "cartId": "*******",
    "email": "*****",
    "billingAddress": {
        "countryId": "FR",
        "regionCode": null,
        "region": null,
        "customerId": "*****",
        "street": [
            "9 Rue Edouard Lefebvre"
        ],
        "company": null,
        "telephone": "*****",
        "fax": null,
        "postcode": "78000",
        "city": "Versailles",
        "firstname": "*****",
        "lastname": "***",
        "middlename": null,
        "prefix": null,
        "suffix": null,
        "vatId": null,
        "customAttributes": []
    },
    "paymentMethod": {
        "method": "adyen_hpp",
        "additional_data": {
            "brand_code": "klarna_account",
            "stateData": "{\"riskData\":{\"clientData\":\....\"},\"paymentMethod\":{\"type\":\"klarna_account\"},\"clientStateDataIndicator\":true}"
        }
    }
}
And it worked for me.

Don't hesitate to PM me if you need more information !

**Comment by tnaber** [comment] 2022-04-04 13:17
Good to hear that it's solved. I will have a look at the documentation to prevent confusion for future integrations. If you have any specific suggestions for the docs this would be greatly appreciated!
I am closing this issue.

**Closed by tnaber** 2022-04-04 13:17 UTC
Labels: Bug report, Priority: high, Confirmed, Headless

**Comment by chris-vaimo** [comment] 2022-09-29 08:28
@tnaber I think this step of the docs (https://docs.adyen.com/plugins/magento-2/magento-headless-integration#create-a-data-object) really should be updated to explain how to resolve which payment method to use & to make it clear(er) that for example **adyen_cc** won't work for all payment options (e.g. it works with Trustly for some reason, but not Klarna).
