### ISSUE TITLE
Place order button invisible when selecting Amazon Pay

### ISSUE THREAD

**Issue by jonathanribas** [Adyen/adyen-magento2#1480] opened 2022-05-02 12:01 UTC
**Describe the bug**
I can't see Place Order button when I select Amazon Pay.

**To Reproduce**
1. Add a product to your cart
2. Proceed all steps until Payment Methods is reached
3. Select Amazon Pay
4. You should see Place Order button but it's not appearing on both Mobile and Desktop version.

**Expected behavior**
I should see Place order button as I can see it for Klarna (HPP too).

**Magento version**
2.4.3-p1

**Plugin version**
8.2.0

**Screenshots**
<img width="667" alt="Screenshot 2022-05-02 at 13 00 40" src="https://user-images.githubusercontent.com/3003782/166230373-0b4ad82e-93bf-47f7-820d-e06f33aa0989.png">

**Comment by tnaber** [comment] 2022-05-04 13:37
Hi @jonathanribas,

Thank you for opening this issue. We are not able to reproduce this issue, these kind of issues are often related to setup issues on Amazon Pay. Please reach out to our support team via support@adyen.com and provide the screenshot you added here.
I will be closing this issue for now. Feel free to reopen if it is not fixed by a change in setup.

Cheers,
Titus

**Closed by tnaber** 2022-05-04 13:37 UTC
Labels: Bug report
