### ISSUE TITLE
 savePaymentInformationAndPlaceOrder plugins incorrectly changing return type

### ISSUE THREAD

**Issue by ryanpalmerweb** [Adyen/adyen-magento2#590] opened 2019-11-21 16:15 UTC
**Magento version**: 2.3.2-p2
**Plugin version**: 5.0.2
**Description**

This issue manifested in the checkout as the place order button showing various errors such as "The entity that was requested doesn't exist. Verify the entity and try again" and "No such entity with cartId = " - however we found that the order was being placed and a refresh of the checkout would instead show no items in the shopping cart.

<img width="818" alt="Screen Shot 2019-11-21 at 16 08 54" src="https://user-images.githubusercontent.com/7669058/69356051-bf1b4400-0c7a-11ea-8845-3ad986a9dbb3.png">

A stack trace on the exception revealed that another module was throwing a NoSuchEntityException with the order repository being unable to retrieve the entity by order id.

Various third party modules intercept the savePaymentInformationAndPlaceOrder method which is part of the \Magento\Checkout\Api\PaymentInformationManagementInterface class

The original class contains the following definition in the PHP file - take note of the return type

```
    /**
     * Set payment information and place order for a specified cart.
     *
     * @param int $cartId
     * @param \Magento\Quote\Api\Data\PaymentInterface $paymentMethod
     * @param \Magento\Quote\Api\Data\AddressInterface|null $billingAddress
     * @throws \Magento\Framework\Exception\CouldNotSaveException
     * @return int Order ID // RETURN TYPE INT / ORDERID
     */
      public function savePaymentInformationAndPlaceOrder
```

This means that any modules extending this class (including your own!) rely on the method to return an integer containing the new order id.

However, the plugins AdyenPaymentInformationManagementAddPaymentInfo and AdyenGuestPaymentInformationManagementAddPaymentInfo can change the return type to an encoded JSON string, breaking plugins further down the chain.

```
    /**
     * @param \Magento\Checkout\Api\GuestPaymentInformationManagementInterface $subject
     * @param $result
     * @return string
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function afterSavePaymentInformationAndPlaceOrder(
        \Magento\Checkout\Api\GuestPaymentInformationManagementInterface $subject,
        $result
    ) {
        try {
            $order = $this->orderRepository->get($result);
            $payment = $order->getPayment();

            if ($payment->getMethod() === AdyenCcConfigProvider::CODE) {
                //THIS CHANGED THE RETURN TYPE
                return $this->adyenHelper->buildThreeDS2ProcessResponseJson(
                    $payment->getAdditionalInformation('threeDSType'),
                    $payment->getAdditionalInformation('threeDS2Token')
                );
            } else {
                return $result;
            }
        } catch (NoSuchEntityException $e) {
            $this->adyenLogger->error("Exception: " . $e->getMessage());
            throw new \Magento\Framework\Exception\LocalizedException(__('This order no longer exists.'));
        }

        return $result;
    }
```

This means that modules further down the chain will attempt to load an order from the order repository using your JSON 3DS object as the order ID.

I would suggest either changing the mechanism so that the return type is always the order ID, or at least setting the plugin to use a much higher value for the sort order

Here is an example of a plugin which is broken from the return type being changed.
```

  /**
     * @param \Magento\Checkout\Model\PaymentInformationManagement $subject
     * @return int Order ID.
     */
    public function afterSavePaymentInformationAndPlaceOrder(
        \Magento\Checkout\Model\PaymentInformationManagement $subject,
        $result
        )
    {
        if (!$this->helper->isEnabled()) {
            return $result;
        }

        $orderId = $result;

        //THE ORDERID IS NOW INVALID AS IT IS A JSON OBJECT BEING PASSED BY ADYEN
        $order = $this->orderRepository->get($orderId);
        ...

        return $result;
    }
```

I have attached a temporary workaround that we have implemented which raises the order of the Adyen plugin so that it is more likely to be executed last

[AdyenDi.zip](https://github.com/Adyen/adyen-magento2/files/3875641/AdyenDi.zip)

**Comment by cyattilakiss** [comment] 2019-11-21 16:45
Hi @ryanpalmerweb ,

Thank you for reaching out.
We use only the after method in the interceptor that is why we chose to use sortOrder=10 . On this link https://devdocs.magento.com/guides/v2.3/extension-dev-guide/plugins.html#prioritizing-plugins you can read about the prioritisation. It says if you want to run your after method the last, you should add the smallest sortOrder number for it. I'm surprised that changing the sortOrder for a larger number helped solving your issue, because it means the docs is not correct - or I misunderstood something :). Can you maybe share your regarding di.xml settings and maybe log the processing order of the other interceptors? That would be really interesting to see for us too.

Regarding the response type and content of the after method, unfortunately we cannot send the integer back because of the 3DS2 flow where we require multiple step interaction with the customer on the frontend. Before 5.0.0 we did it before placing the order so we didn't need to use interceptors, but turned out that it was a bad practise because the order validation and creation could go south and then the payment was already done while the order was not created. That is why we decided to change the behaviour like this.

Let me know what do you think and of course I'm waiting for the lines and logs so we can check if the prioritisation is indeed wrong and we should use a higher value or not.

Best,
Attila
Adyen

**Comment by ryanpalmerweb** [comment] 2019-11-21 17:40
Hi Attila,

Indeed, the documentation does seem to say we have this the wrong way round, however the logs are showing a different result.

Both your module and the other (WeltPixel GoogleTagManager) had selected a sort order of 10, so our module overrides using 9999.

I added the following line to the top of each interceptor.

`\Magento\Framework\App\ObjectManager::getInstance()->get(\Psr\Log\LoggerInterface::class)->debug(get_class($this));`

The log files now show the following :

> [2019-11-21 17:05:55] main.DEBUG: WeltPixel\GoogleTagManager\Plugin\GuestPaymentInformation [] []
> [2019-11-21 17:05:55] main.DEBUG: Adyen\Payment\Plugin\GuestPaymentInformationManagement [] []

Thanks,
Ryan

**Comment by ryanpalmerweb** [comment] 2019-11-21 17:42
WeltPixel di.xml attached :

`<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Checkout\Model\ShippingInformationManagement">
        <plugin name="weltpixel-googletagmanager-checkout-shippinginformation"
                type="WeltPixel\GoogleTagManager\Plugin\ShippingInformation" sortOrder="10"/>
    </type>
    <type name="Magento\Checkout\Model\PaymentInformationManagement">
        <plugin name="weltpixel-googletagmanager-checkout-paymentinformation"
                type="WeltPixel\GoogleTagManager\Plugin\PaymentInformation" sortOrder="10"/>
    </type>
    <type name="Magento\Checkout\Model\GuestPaymentInformationManagement">
        <plugin name="weltpixel-googletagmanager-checkout-guestpaymentinformation"
                type="WeltPixel\GoogleTagManager\Plugin\GuestPaymentInformation" sortOrder="10"/>
    </type>
    <type name="Magento\Wishlist\Model\Item">
        <plugin name="weltpixel-googletagmanager-wishlist-addtocart"
                type="WeltPixel\GoogleTagManager\Plugin\WishlistAddToCart" sortOrder="10"/>
    </type>
    <type name="Magento\Quote\Model\Quote\Config">
        <plugin name="weltpixel-googletagmanager-quote-config"
                type="WeltPixel\GoogleTagManager\Plugin\QuoteConfig" sortOrder="10"/>
    </type>
    <type name="Magento\Framework\App\Http\Context">
        <plugin name="weltpixel-googletagmanager-context"
                type="WeltPixel\GoogleTagManager\Plugin\HttpContext" sortOrder="1"/>
    </type>
</config>`

**Comment by ryanpalmerweb** [comment] 2019-11-21 22:02
Hi Attila,

I wanted to rule out other factors, such as our override affecting the sort order.

I've set the sort order to 9 within our override for Adyen, and I now get the following log output instead :

> [2019-11-21 22:00:44] main.DEBUG: Adyen\Payment\Plugin\GuestPaymentInformationManagement [] []
[2019-11-21 22:00:44] main.DEBUG: WeltPixel\GoogleTagManager\Plugin\GuestPaymentInformation [] []

I think we can safely say that the lowest number is being processed first

Thanks
Ryan

**Comment by Maikel-Koek** [comment] 2019-11-27 16:37
@cyattilakiss 
I'm also having issues with this altered return type.

I'm not adding a custom plugin, so the 'workaround' to change the sortorder doesn't apply to me, it's just that I (and all of Magento) rely on an order ID when I call `savePaymentInformationAndPlaceOrder`, not some json encoded string, with not even the order ID in it.

You mentioned it was a bad practice what you did before, but I think this is an even more bad practice, changing the return type (and value!) of a core method.

I'm not sure how to get around this, isn't there another way for you to implement this?

**Comment by PascalBrouwers** [comment] 2019-11-28 09:53
@cyattilakiss even more bad practice is suggesting everyone just should 'change sortOrder' because you messed up and every plugin that comes after this breaks because the return type changed. Don't try to fix up by changing the prioritisation, fix it by using the correct return type!

**Comment by JeroenVanLeusden** [comment] 2019-11-28 09:58
Just bumped into this. You should never alter the return type in a plugin, no matter what sort order. It should be implemented in .a different way If interaction with the frontend is needed.

**Comment by cyattilakiss** [comment] 2019-11-28 13:02
HI @Maikel-Koek, @PascalBrouwers, @JeroenVanLeusden 

Thank you all for your inputs in this issue. I will answer everyone below.

@Maikel-Koek 
> You mentioned it was a bad practice what you did before, but I think this is an even more bad practice, changing the return type (and value!) of a core method.
Yes we are aware. This is why we want to run the after interceptor the latest so we leave the rest of the plugins untouched but as @ryanpalmerweb raised the issue that the sort order is not working as expected in Magento this approach seems to fail. I also found this thread regarding this issue https://github.com/magento/magento2/issues/25150 . Since this is only an issue in certain versions we cannot change the sort order for some and keep it as it is for the rest, that is why the custom module would be a solution but I also understand that it is not a possibility for everyone.

> I'm not sure how to get around this, isn't there another way for you to implement this?
The biggest issue that we have to do the 3DS2 validation after the order was created in Magento but before we redirect to the success or error page. We are going to try to find a better solution for this without messing the interceptor return value, but as a quick solution we chose this approach.

@PascalBrouwers 
The sort order suggestion is only for those who has the interceptor sort order issue described in the current ticket above. The ones with a version where the sort order works as expected this interceptor should run the last. I understand your concerns with the return type, we are going to try to find a better solution for this.

@JeroenVanLeusden
> It should be implemented in a different way If interaction with the frontend is needed.
Do you have any suggestion for us to change the implementation without breaking the type constraint while staying on the checkout page?

> Also sort order of after plugins seems to be broken, see magento/magento2#25678. Even the sort order 'solution' you provide will fail eventually if it's fixed by Magento.
Yes the sort order of the after plugin is broken, we got quite a good proof from @ryanpalmerweb and we also found the issue already raised at Magento. The initial idea was if this plugin is running the latest then it shouldn't fail in our case since the frontend will handle the modified response type, but we are really open to move for a better solution.

Thank you again for the input, I hope I answered well and we can fix it as soon as possible.

Best,
Attila
Adyen

**Comment by PascalBrouwers** [comment] 2020-01-15 08:37
please fix ;)

**Comment by zetxek** [comment] 2020-01-15 09:23
Would be useful to not stale the bug, but to get it fixed 😅

**Comment by vtransy** [comment] 2020-02-26 09:28
Hi guys.

I got this issue also.

The solution is quite simple. Detail technical issue I noted here:
https://mrvts.wordpress.com/2020/02/26/magento-2-aduyen-bug-report-wrong-format-of-after-plugin-in-checkout-process-public-function-aftersavepaymentinformationandplaceorder/

**For SOLUTION is here:**

Search in your project plugin: `afterSavePaymentInformationAndPlaceOrder`

it will have xml define like this for each one:
``` <type name="Magento\Checkout\Model\GuestPaymentInformationManagement">
        <plugin name="weltpixel-googletagmanager-checkout-guestpaymentinformation"
                type="WeltPixel\GoogleTagManager\Plugin\GuestPaymentInformation" sortOrder="10"/>
    </type>```

The sortOrder of this plugin in Aduyen is 10 so you change all sortOrder in other plugin of this function to a number smaller than 10 (ex: 5) then the issue will be resolved.

For example, in my case `WeltPixel\GoogleTagManager` >> fire this issue. I will change xml of this extion for after plugin like this:

```<type name="Magento\Checkout\Model\GuestPaymentInformationManagement">
        <plugin name="weltpixel-googletagmanager-checkout-guestpaymentinformation"
                type="WeltPixel\GoogleTagManager\Plugin\GuestPaymentInformation" sortOrder="5"/>
    </type>```

Set sortOrder="5"

You can do it direct in extension (not recommend ) or you can create custom extension which override plugin which raise issue.

How to override plugin is guide here: https://magento.stackexchange.com/questions/155520/how-to-override-or-disable-core-plugins-in-magento2

**Comment by Maikel-Koek** [comment] 2020-02-26 09:30
@vtransy 
We know how to resolve this, but it's a workaround, not a fix of the actual problem :)

But it looks like Adyen is starting to correctly resolve this in this PR:
https://github.com/Adyen/adyen-magento2/pull/643

**Comment by vtransy** [comment] 2020-02-26 09:33
@Maikel-Koek I agree, my solution not fix the root cause. But in the meantime while we wait for the fix, we need a work around solution which is very simple to resolve the bug to help release function for our project.

**Comment by cyattilakiss** [comment] 2020-04-01 08:17
Hi @ryanpalmerweb , @Maikel-Koek , @PascalBrouwers , @zetxek , @vtransy 

Thank you all for the input and for the patience!

In the latest release (version 6.0.0) we released the fix for this issue, removing the interceptor which was overwriting the response. We introduced instead a new API endpoint to retrieve the current payment status. You can check the changes in the pull request #643

Please note:
* For PWA integrations this is a breaking change because now you need to perform another API call before you can redirect the shopper to the success page. (The updated PWA integration documentation is coming soon for the new release on our docs page)
* There are changes on the checkout frontend as well, so if you customised the frontend - extending or overwriting the plugin's default behaviour it may break the customisation.

I will close this issue for now but please feel free to reopen it if you still experience the issue after the upgrade or have any additional feedback.

Best,
Attila
Adyen

**Closed by cyattilakiss** 2020-04-01 08:17 UTC
Labels: Bug

**Comment by frostblogNet** [comment] 2020-11-25 11:15
I have the same issue with your extension

adyen/module-payment                                              6.6.5

in a fresh installed

magento commerce                                                   2.3.6

whitout any custom extension at all.

Any idea´s?

**Comment by cyattilakiss** [comment] 2020-11-25 20:53
Hi @frostblogNet ,

Please check the logs for exception or any errors. The error message you have indicates that there was an error or an exception thrown during the place order process and not that the interceptor overwrote the result.
Do you have the error with a non Adyen payment method as well?

Best,
Attila
Adyen
