### ISSUE TITLE
[PW-6545] Incorrect payment methods

### ISSUE THREAD

**Issue by marc-arnoult** [Adyen/adyen-magento2#1440] opened 2022-04-06 13:32 UTC
**Describe the bug**
Payment methods do not appear or not correctly.
Paypal is not shown, and apple pay appear ( it should not on Windows/Chrome ).

Retrieve the payment methods response : 
```
{
    "paymentMethodsResponse": {
        "paymentMethods": [
            {
                "brands": [
                    "amex",
                    "maestro",
                    "mc",
                    "visa"
                ],
                "configuration": {
                    "merchantId": "000000000202216",
                    "merchantName": "****"
                },
                "name": "Apple Pay",
                "type": "applepay"
            },
            {
                "brands": [
                    "amex",
                    "maestro",
                    "mc",
                    "visa"
                ],
                "name": "Cartão de crédito",
                "type": "scheme"
            },
            {
                "configuration": {
                    "intent": "capture"
                },
                "name": "PayPal",
                "type": "paypal"
            }
        ]
    },
    "paymentMethodsExtraDetails": {
        "applepay": {
            "icon": {
                "url": "https://checkoutshopper-live.adyen.com/checkoutshopper/images/logos/medium/applepay.png",
                "width": 77,
                "height": 50
            },
            "isOpenInvoice": false,
            "configuration": {
                "amount": {
                    "value": 2845,
                    "currency": "EUR"
                },
                "currency": "EUR"
            }
        },
        "card": {
            "icon": {
                "url": "static.imgix.net/static/version1648806722/base/Magento/base/default/Adyen_Payment/images/logos/card.png",
                "width": 77,
                "height": 50
            },
            "isOpenInvoice": false
        },
        "paypal": {
            "icon": {
                "url": "static.imgix.net/static/version1648806722/base/Magento/base/default/Adyen_Payment/images/logos/paypal.png",
                "width": 65,
                "height": 41
            },
            "isOpenInvoice": false,
            "configuration": {
                "amount": {
                    "value": 2845,
                    "currency": "EUR"
                },
                "currency": "EUR"
            }
        },
        "scheme": {
            "configuration": {
                "amount": {
                    "value": 2845,
                    "currency": "EUR"
                },
                "currency": "EUR"
            }
        }
    }
}
```
Error on the first page of the checkout : 
```
(index):1 Uncaught TypeError: Unable to process binding "foreach: function(){return adyenPaymentMethods }"
Message: Unable to process binding "afterRender: function(){return renderCheckoutComponent() }"
Message: Cannot read properties of undefined (reading 'slice')
    at getStreetAndHouseNumberFromAddress (adyen-hpp-method.min.js:formatted:352:45)
    at UiClass.getFormattedAddress (adyen-hpp-method.min.js:formatted:381:26)
    at UiClass.buildComponentConfiguration (adyen-hpp-method.min.js:formatted:412:49)
    at Object.renderCheckoutComponent (adyen-hpp-method.min.js:formatted:131:46)
    at afterRender (eval at createBindingsStringEvaluator (knockout.min.js:formatted:2593:28), <anonymous>:3:174)
    at evaluateValueAccessor (knockout.min.js:formatted:2786:28)
    at knockout.min.js:formatted:2915:40
    at init (after-render.min.js:1:177)
    at knockout.min.js:formatted:2965:58
    at Object.ignore (knockout.min.js:formatted:1276:45)
getStreetAndHouseNumberFromAddress @ adyen-hpp-method.min.js:formatted:352
getFormattedAddress @ adyen-hpp-method.min.js:formatted:381
buildComponentConfiguration @ adyen-hpp-method.min.js:formatted:412
renderCheckoutComponent @ adyen-hpp-method.min.js:formatted:131
afterRender @ VM7014:3
evaluateValueAccessor @ knockout.min.js:formatted:2786
(anonymous) @ knockout.min.js:formatted:2915
```

The previous error is very weird because of all my tests after that, it do not seems that it enter in this code at the first step, only at the payment step.

It can some from this file `vendor/adyen/module-payment/view/frontend/web/js/model/set-shipping-information-mixin.js`

If we can't find the source of this error, it could help to add a check on the method `getStreetAndHouseNumberFromAddress` maybe ? To prevent this kind of errors.

**To Reproduce**
⚠️ This bug is very hard to reproduce. It seems random.
When this error appear i'm on the first page of the checkout, it's very weird because, from what i saw we should not enter in this code at the first step of the checkout.

The only time a reproduced it, was on a first visit on the website with a clear session.

**Expected behavior**
I should see all the payment methods configured in Magento.

**Magento version**
 2.4.3-p1

**Plugin version**
8.1.1

**Screenshots**
![Capture d’écran 2022-04-05 183113](https://user-images.githubusercontent.com/16859411/161984432-9978e78b-9f2b-4fe8-aa6f-c059a3c1ded9.png)
![Capture d’écran 2022-04-05 183046](https://user-images.githubusercontent.com/16859411/161984453-1c693d58-6a10-4853-89de-bd37050a2817.png)

**Desktop (please complete the following information):**
 - OS: Windows / OS X
 - Browser: Chrome
 - Version:  99.0.4844.84

**Comment by tieroom** [comment] 2022-04-11 11:36
We are seeing the same JS error. In our case resulting in credit card fields not displaying properly (similar to what is reported in #1445). The error occurs intermittently and seems to be some race condition in the loading of different javascript code in the checkout. We have rolled back to 8.1.1 where everything works fine.

**Comment by jonathanribas** [comment] 2022-04-11 11:44
Hi @tieroom, I'm working with @marc-arnoult and unfortunately we have this issue on `8.1.1` :( it's really random issue.

**Comment by tieroom** [comment] 2022-04-11 12:15
@jonathanribas Ah, I read the original post too quickly. If it's the same issue as ours, it must occur a lot less on 8.1.1 as we have not been able to reproduce it there while it was fairly easy to reproduce on 8.2.0. But maybe our problem is a completely separate bug? 

We were seeing things like this:
![Skärmavbild_2022-04-08_kl _18 13 28](https://user-images.githubusercontent.com/5046863/162737199-6d268bbc-5432-4735-9dc6-21bf881fab5f.png)

**Comment by jonathanribas** [comment] 2022-04-11 12:57
We know it's not optimal but we have fixed it this way.

For information we were having this issue more than 500 times a day.

`diff --git a/composer.json b/composer.json
index c3b8abdc7c78917b0e8c24734538ebea521752a5..8eb2d8d5e7a1ba4844141c23a1ad9d017d360f25 100644
--- a/composer.json
+++ b/composer.json
@@ -328,6 +328,9 @@
     "composer-exit-on-patch-failure": true,
     "patches": {
+      "adyen/module-payment": {
+        "address-street-slice": "patches/adyen/address-street-slice.patch"
+      },
diff --git a/patches/adyen/address-street-slice.patch b/patches/adyen/address-street-slice.patch
new file mode 100644
index 0000000000000000000000000000000000000000..0c9fc43ba9ee2937951c57ffb3606af0bbc7cf38
--- /dev/null
+++ b/patches/adyen/address-street-slice.patch
@@ -0,0 +1,14 @@
+diff --git a/vendor/adyen/module-payment/view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js b/vendor/adyen/module-payment/view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
+index 196dc3c87..90477cc99 100755
+--- a/vendor/adyen/module-payment/view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
++++ b/vendor/adyen/module-payment/view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
+@@ -579,6 +579,9 @@ define(
+              */
+             getFormattedAddress: function(address) {
+             function getStreetAndHouseNumberFromAddress(address, houseNumberStreetLine, customerStreetLinesEnabled) {
++                if (typeof address.street === 'undefined') {
++                    address.street = [''];
++                }
+                 let street = address.street.slice(0, customerStreetLinesEnabled);
+                 let drawHouseNumberWithRegex = parseInt(houseNumberStreetLine) === 0 || // Config is disabled
+                     houseNumberStreetLine > customerStreetLinesEnabled || // Not enough street lines enabled
`

**Comment by tnaber** [comment] 2022-04-12 14:07
Hi all,

This is a duplicate of #1347, in which a solution is also proposed. An internal ticket has been opened

Cheers,
Titus

**Comment by tnaber** [comment] 2022-04-20 13:42
Hi @jonathanribas, @marc-arnoult and @tieroom,
In #1456, I added a fix for the problem occurring in the `adyen-cc-method.js`. If you have some time and would be able to check it out that would be greatly appreciated! I am also curious if this might fix the JS error related to the address.
Additionally, if you found some extra steps to recreate the problem regarding the address slicing I gladly hear them.

It seems like the issues are caused by some asynchronous calls that have not completed yet when, for instance, a slice is run the result.

Cheers,
Titus

**Closed** 2022-05-11 07:53 UTC
Labels: Bug report, Priority: high, Confirmed
