### ISSUE TITLE
3D-secure validation was successful but payment transaction is not authorised. 

### ISSUE THREAD

**Issue by sheppeybrian** [Adyen/adyen-magento2#853] opened 2020-10-12 14:45 UTC
3D secure payments (that are not frictionless) are dropped after 3D secure completes successfully 

1. Place a order that requires 3D secure authorisation 
2. Customer gets routed to banks 3D secure for authorisation 
3. Authorisation approved by bank
4. Customers state no website confirmation page is shown, the connection to website gets dropped. 
"error message just said something about the connection to the website or server had been lost or disconnected"
5. No transaction recorded on Adyen Platform 
6. Magento order comments show "Customer was redirected to bank for 3D-secure validation. Once the shopper authenticated, the order status will be updated accordingly

**Expected behavior**
Customer gets returned to website's confirmation page
Transaction get recorded in Adyen Payments List

adyen-php-api-library
6.3.0
adyen-magento2
6.6.1
Magento
2.3.5-p2

**Comment by kevin-blackbird** [comment] 2020-10-13 07:45
Hi, 

I have the same issue with version 6.6.0 on Magento 2.3.4, i want to add more information if it can help.

After validating 3D Secure customer is redirected to /adyen/process/redirect with a param PaRes which can reach 6k char length. That give an 502 Nginx error like "upstream sent too big header while reading response header from upstream"

Some people recommand (and Adyen too after i create a support ticket) to use http2_max_header_size 16k; in nginx config, I tried it and it doesn't work. Even if it would work it's not the best solution. 

On Adyen's platform there is an offer but no payment is registered.

Last information from Adyen after my ticket creation : 
"we are working on a more permanent solution in the coming sprint, as we found that the solution provided by Magento had some negative effects on the URL length. However we have seen for our other merchants that extending the allowed field length should resolve the issue in the meantime while we build our long term solution. "

Kevin

**Comment by acampos1916** [comment] 2020-10-13 08:59
Hello @sheppeybrian, thanks for opening this issue,

Can you confirm that the problem is the same as the one described by @kevin-blackbird? Also discussed in #815.

@kevin-blackbird indeed we are working in a different solution for the SameSite cookie policy so that we don't face URL length issues.

Cheers,
Ángel

**Comment by fahu** [comment] 2020-10-13 10:01
We are experiencing the same issue. setting `http2_max_header_size 16k` in Nginx does not solve the issue.

**Comment by sheppeybrian** [comment] 2020-10-13 12:51
Hello @acampos1916 
Yes this does sound similar I've been following the chrome SameSite issue and have set http2_max_header_size 16k; in nginx config.
This does not resolve the issue but was under the impression the 6.6.1 would finally sort this out.
Odd thing is returns from a frictionless 3dsecure don't seem to be affected? 
Currently have 3DS off as causing too many customer service issues.  However this leaves site with no Liability Shift

**Comment by fahu** [comment] 2020-10-13 13:36
We are experiencing the exact same issue.

**Comment by fahu** [comment] 2020-10-13 15:24
@sheppeybrian You can debug it though in testing mode ;-)

**Comment by sheppeybrian** [comment] 2020-10-13 17:57
@fahu Seems to need to be a live transaction and be returned as approved by the cards authorising bank.

**Comment by fahu** [comment] 2020-10-14 02:30
@sheppeybrian Yes we can reproduce this on our test system (with the Adyen test system) too.

We use the following credit card data to reproduce the issue:

Number: `6771 7980 2100 0008`
Expiration Date: `03/30`
CVC: `737`

Taken from https://docs.adyen.com/development-resources/test-cards/test-card-numbers


By the way we could (temporary) fix the issue by adapting our nginx config to increase the buffer sizes:

```
proxy_buffers 16 16k;
proxy_buffer_size 64k;
proxy_busy_buffers_size 128k;
proxy_temp_file_write_size 128k;
```

In case you use fastcgi you will have to use the following:
```
fastcgi_buffers 16 16k;
fastcgi_buffer_size 64k;
fastcgi_busy_buffers_size 128k;
fastcgi_temp_file_write_size 128k;
```

**Comment by sheppeybrian** [comment] 2020-10-14 10:12
@fahu  I've had it confirmed by our server hosts that these changes were made.  Unfortunately did not fix the issue for us.

**Comment by Anve94** [comment] 2020-10-14 10:47
@sheppeybrian It really depends on your hosting stack where these changes should be made. It does not have to be at the same place as other commenters mention, because each server config is different. When the redirect request is sent to the server with a very long URL, the connection can be dropped **anywhere** in the "servicing chain" where there is a character limit. In my case, this was in the SSL offloader. It can really be anywhere in the stack where the request is passing through; SSL offloaders, Load balancers, Nginx/Apache configuration etc. Whenever the URL exceeds the allowed URL length in any of these services, the connection gets dropped.

If you want to test how long URL's can be for your server stack to handle, you can just craft a custom URL for your Magento instance. In my case, redirect URL's didn't exceed 8k characters and the connection was dropped by the SSL offloader, hence we updated the configuration there as detailed in a #815 comment. For you the connection might be dropped elsewhere. Also keep in mind that depending on the card/issuer involved, and the length of your domain, a configuration with 8k character limits might not be high enough. I'd recommend crafting a custom URL of absurd length to see if you hit a 404 on that URL. If the connection doesn't drop, you know the length of the crafter URL is serviceable by your server stack.

I agree that Adyen should fix the length of URL's in an update, but I hope the above points will help you move forward towards a solution in the meantime.

**Comment by PascalBrouwers** [comment] 2020-10-19 14:36
Was able to reproduce with the same creditcard test from https://docs.adyen.com/development-resources/test-cards/test-card-numbers
Number: 6771 7980 2100 0008
Expiration Date: 03/30
CVC: 737

You also get this popup for 1/10th of a second: 
![Screenshot 2020-10-19 at 16 34 29](https://user-images.githubusercontent.com/17834386/96465375-2f369f00-1229-11eb-8849-424ca3d056bc.png)

**Comment by fahu** [comment] 2020-10-20 09:27
Update: Even AWS Cloudfront has a hard URL limit of 8,192 bytes that can't by modified (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html). This means that we currently have no way to provide a quick fix for URLs > 8,192 bytes.

**Comment by floorjubbega** [comment] 2020-10-22 09:31
Duplicate of #815

**Closed by floorjubbega** 2020-10-22 09:31 UTC
Labels: Bug report
