### ISSUE TITLE
Not all payment methods are showing on OPC

### ISSUE THREAD

**Issue by BenGoos** [Adyen/adyen-magento2#2063] opened 2023-05-22 14:04 UTC
**Describe the bug**
Some alternative payment methods aren't showing when first visiting the checkout page. When you fill in an address and you reload the page all the alternative payment methods will show. We are using Amasty One Step Checkout Pro.

**Expected behavior**
All the alternative payment methods needs to be shown when you visit the checkout page. 

**Magento version**
2.4.5-p1

**Plugin version**
8.17.1

**Screenshots**
Screenshot on first visit (no address given):
<img width="1122" alt="Scherm­afbeelding 2023-05-22 om 15 18 31" src="https://github.com/Adyen/adyen-magento2/assets/25454683/59b0251e-de99-4bbd-a995-8e80b913345f">

Screenshot after reloading page and address givin, this result we want on the first visit and when no address is given:
<img width="925" alt="Scherm­afbeelding 2023-05-22 om 15 19 01" src="https://github.com/Adyen/adyen-magento2/assets/25454683/2ef7e55c-e841-4cd0-9678-78a086f994a5">

**Comment by candemiralp** [comment] 2023-05-23 07:24
Hello @BenGoos,

Thank you for raising this issue. Our payment module needs events that are fired from Magento's regular checkout after updating the quote billing/shipping address in order to fetch the payment methods according to the shoppers cart, country etc. ([paymentMethods API call reference](https://docs.adyen.com/api-explorer/Checkout/70/post/paymentMethods))

This kind of 3rd party extensions break the expected flow and exhibit unexpected behaviours on the checkout page ([Adyen Docs](https://docs.adyen.com/plugins/adobe-commerce/troubleshooting#step-2-disable-third-party-plugins)). As Adyen, we deliver our open source payment modules to work seamlessly on default setup. However, it's our merchants' or system integrators' responsibility to configure/customise the module if they want to use an unsupported 3rd party plugin.

I am closing this issue as it is not a bug but an issue caused by an unsupported 3rd party module. Please don't hesitate to reach out to us for your further questions.

Best Regards,
Can

**Closed by candemiralp** 2023-05-23 07:24 UTC
Labels: Bug report
