### ISSUE TITLE
im getting error when running setup:di:compile

### ISSUE THREAD

**Issue by amjad-alarori** [Adyen/adyen-magento2#2007] opened 2023-03-25 00:45 UTC
i upgraded adyen from 7.3 to 8.17, but the deployment fail on:
 **"MiBInterface 'Magento\QuoteGraphQl\Model\Cart\Payment\AdditionalDataProviderInterface' not found#0 /var/www/html/vendor/composer/ClassLoader.php(571): include()"**

**To Reproduce**
1. Run "bin/magento setup:de:compile"
2. See error: "MiBInterface 'Magento\QuoteGraphQl\Model\Cart\Payment\AdditionalDataProviderInterface' not found#0 /var/www/html/vendor/composer/ClassLoader.php(571): include()"

**Expected behavior**
compilation finish without error.

**Magento version**
[2.4.3-p1]

**PHP version**
[7.4]

**Plugin version**
[8.17.0]

**Screenshots**
<img width="1652" alt="image" src="https://user-images.githubusercontent.com/54799568/227668786-88930199-e2d0-4a25-b7f6-6abfd2d1d3f7.png">

**Comment by Morerice** [comment] 2023-03-27 11:01
Hi @amjad-alarori,

I attempted to re-create this issue based on your specifications and the steps to reproduce, but in my case, compilation was successfully completed. Are there other steps that you could provide to maybe try and re-create this issue?

Thanks,
Jean
Adyen

**Comment by maaarghk** [comment] 2023-03-28 15:19
Have you disabled Magento_GraphQl module e.g. using https://github.com/yireo/magento2-replace-graphql ?

**Comment by candemiralp** [comment] 2023-04-18 07:38
Hello @amjad-alarori,

I am closing this ticket since we can't reproduce the issue currently and there is no answer to the above comments. You can re-open this issue with additional information if the issue is persistent on your end.

Best Regards,
Can

**Closed by candemiralp** 2023-04-18 07:38 UTC
Labels: Bug report
