### ISSUE TITLE
[PW-4236] Payment stuck on Payment Review

### ISSUE THREAD

**Issue by YanP-Adyen** [Adyen/adyen-magento2#782] opened 2020-08-03 16:31 UTC
**Describe the bug**
Payment is fine on Adyen's side but stuck on "Payment Review" on Magento's side

**To Reproduce**
This has been seen with PayPal (1755943111120959), Klarna (4755947294427622) and Mastercard (4355960853227246).
Everything is fine ou Adyen's side, no particular flow (no 3DS)

Comment history for Klarna transaction : 
```
Jul 14, 2020 2:26:31 PM Processing Customer Not Notified
    Adyen Payment Successfully completed
    
    Jul 14, 2020 2:26:31 PM Pending Customer Not Notified
    Payment is authorised waiting for capture
    
    Jul 14, 2020 2:26:31 PM Pending Customer Not Notified
    Adyen HTTP Notification(s):
    eventCode: AUTHORISATION
    pspReference: 4755947294427622
    paymentMethod: klarna
    success: true
    reason:klarna
    
    Jul 14, 2020 2:25:17 PM Customer Not Notified
    Adyen Result URL response:
    authResult: AUTHORISED
    pspReference: 4755947294427622
    paymentMethod: klarna
    
    Jul 14, 2020 2:23:56 PM Pending Customer Notified

```

Logs for Klarna and Mastercard payments : 
[Klarna_pending.log](https://github.com/Adyen/adyen-magento2/files/5017116/Klarna_pending.log)
[mc_pending.log](https://github.com/Adyen/adyen-magento2/files/5017117/mc_pending.log)

As you can see, nothing triggers me here everything seems to be correctly processed.
To be noted, the merchant is having old versions of both Magento (2.2.2) and Adyen's plugin (4.0.3)

**Comment by Anve94** [comment] 2020-08-06 07:02
I've encountered the same issue with up-to-date versions of the software.
Magento version: 2.3.4-p2
Adyen version: 6.2.0

Notifications are processed by the cron Model in the module and the associated logs are stating the order state was changed to processing. However, the order state itself is still on 'Payment Review', both in the sales_order and in sales_order_grid table. The last history amendment for this credit card order is: "We will authorize <amount> after the payment is approved at the payment gateway."

@YanP-Adyen I've been communicating with Adyen support about this, if there's any result coming out of it, I'll make sure to post a resolution to this issue for you.

**Comment by tieroom** [comment] 2020-09-17 07:14
Same issue here. We are on Magento 2.3.5-p2 with Adyen 6.5.0.

**Comment by tieroom** [comment] 2020-09-18 08:44
Wondering if this could be due to long tokens in some of the callbacks, causing them to get denied by the web server, as in #815

**Comment by Anve94** [comment] 2020-09-18 11:18
@tieroom Seems to me orders are never processed anymore if issues arise in the redirect flow. #815 is a good example of this, since the callback is never picked up by the module when that issue crops up, and as such the cron simply never processes a notification anymore. In the case of that specific, the orders aren't even available on the Adyen portal. Didn't check the cron logs but I'm fairly sure during #815 there is no notification sent to the cron in the first place.

When I responsed to the issue above, 6.5.0 wasn't out yet. We didn't really got the issue resolved with support, but at some point the issues just stopped cropping up. Issues occured again with the token length in the GET request as reported in #815, but once we got that resolved the cron is processing notifications and is mutating orders as expected again.

**Comment by AlexandrosMor** [comment] 2020-09-22 10:35
Hello @Anve94,

Thank you for raising this issue. Could you please check the cron logs and the error logs to see why the notifications are not processed? Further more please check the adyen_notification table to check if the notifications are there. Also you can see which notifications are processed with state of done and which are not picked by the cron. 

kind regards,
Alexandros

**Comment by tieroom** [comment] 2020-09-23 09:29
> Could you please check the cron logs and the error logs to see why the notifications are not processed?

I can't see anything in the logs indicating there was an error.

> Further more please check the adyen_notification table to check if the notifications are there.

Yup, the notifications are there.

> Also you can see which notifications are processed with state of done and which are not picked by the cron.

All the affected transactions have the field "done" in the notifications table set to "1", if that is what you mean we should check.

So I guess it looks like the notifications are received fine. The issue comes afterwards when the overall magento status for the order is to change from "Payment Review" to "Processing", somehow that fails for a small subset of Adyen transactions.

**Comment by manuel-inhertz** [comment] 2020-12-16 11:56
This is still an issue, any news about how to fix this?

**Comment by kapilqtsolv** [comment] 2021-02-08 11:17
Same for me.
Still facing the issue.

**Comment by tieroom** [comment] 2021-05-03 07:34
FYI, after upgrading to Magento 2.4.2 and Adyen 7.0.0, we are not seeing this issue anymore.

**Comment by acampos1916** [comment] 2021-05-25 13:21
Hello all, seems like for some of this ticket's commenters the issue was found in older versions of the plugin, thanks for your feedback.

@manuel-inhertz is this still an issue for you? Which version of the plugin were you using back when you commented and do you have steps to reproduce?

**Comment by acampos1916** [comment] 2021-06-07 06:56
I'll be closing this issue due to inactivity, @manuel-inhertz let us know if you can provide the requested info.

**Closed by acampos1916** 2021-06-07 06:56 UTC
Labels: Bug report

**Comment by gvasilakiss** [comment] 2021-08-03 08:56
Has anyone fixed this on adyen/module-payment: "7.1"?

**Comment by acampos1916** [comment] 2021-08-04 08:09
Hello @gvasilakiss. Which notifications are being processed? Is there anything related in the var/log/adyen log files?

**Comment by gvasilakiss** [comment] 2021-08-04 09:12
Hi @acampos1916, When I complete an order, I get the payment confirmation on the Adyen Payments as Authorised, but on Magento, the payment status is still showing as Payment review and the comments are:

Aug 3, 2021 11:12:45 AM Payment Review Customer Not Notified
We will authorize £249.00 after the payment is approved at the payment gateway. Transaction ID: "XXXXXXXXXX"

Aug 3, 2021 11:12:45 AM Customer Not Notified
Adyen Result response:
authResult: Authorised
pspReference: XXXXXXXXXXXXXXX

This is the logs files from the Ayden folder

[info_AD.log](https://github.com/Adyen/adyen-magento2/files/6930059/info_AD.log)

**Comment by acampos1916** [comment] 2021-08-04 13:47
Thanks @gvasilakiss, I see those log lines are related to the initial payment request. Have you also checked the ones for the notification processing in cronjob.log?

**Comment by gvasilakiss** [comment] 2021-08-04 13:52
I don't have any notification logs currently. On the cronjob log I got this: [2021-08-03 10:10:10] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: There are no verified Adyen IP addresses in cache. Updating IP records. {"is_exception":false} []
