### ISSUE TITLE
Credit Card not shown at first on checkout with  Adyen  9.8.1 / Magento 2.4.5-p8

### ISSUE THREAD

**Issue by apomili** [Adyen/adyen-magento2#2755] opened 2024-09-26 10:54 UTC
We have three shop with 2.4.5-p8 version of Magento Commerce (ex Enterprise)

**Describe the bug**
After Adyen update when you go to checkout and fill shipping address and go on the payment method, the Credit Card radio not appear. Now if you refresh the page, the payment method will correctly appear

**To Reproduce**
1. Configure Magento with adyen credit card payment method 
2. Add a product on cart
3. Go to checkout page and fill your data
4. Now when the page move on payment method the CC method should not be visible
5. Refresh the page and now CC will appear

**Expected behavior**

**Magento version**
[2.4.5-p8] Enterprise

**Plugin version**
[9.8.1]

**Comment by candemiralp** [comment] 2024-09-27 12:15
Hello @apomili,

Thank you for reporting this issue. Unfortunately, we are not able to reproduce the issue on the given versions of the plugin and Magento. Since the issue is not reproducible on the default versions and the code references, clear error or exception messages are missing, this issue needs to be investigated by our support team.

Could you please reach out to Adyen technical support via `support@adyen.com` and attach the relevant logs (under `var/log/adyen/*` directory on your server) after reproducing the issue? I am closing this issue since the rest will be handled through ticketing system by support team.

Best Regards,
Can

**Closed by candemiralp** 2024-09-27 12:15 UTC
Labels: Bug report

**Comment by DavsialL** [comment] 2024-11-04 21:55
Hey @apomili 
Were you able to resolve this? We are facing the exact same issue. Our payment page has a lot of customizations and perhaps your solution could give me some clue on what is causing this. 
Thank you,
Vlad
