### ISSUE TITLE
Alipay and Alipay HK Invalid Request

### ISSUE THREAD

**Issue by andreawiki** [Adyen/adyen-magento2#909] opened 2020-12-14 10:57 UTC
We are using adyen version 6.6.5  magento version 2.2.11
Some browser show Invalid Request after clicking Alipay payment:
![WhatsApp Image 2020-12-14 at 6 33 22 PM](https://user-images.githubusercontent.com/75980553/102073301-110ea900-3e3e-11eb-9dc2-a99f833df795.jpeg)

Working
Mac - Chrome Version 87.0.4280.67
Mac - Chrome Version 87.0.4280.88 
Mac - Firefox 84.0

Not Working
Mac - Firefox Version 80.0.1
Mac - Chrome 83 (but upgrade to 87 then ok) Mac - Firefox 83.0
Mac - Chrome Version 87.0.4280

**Comment by floorjubbega** [comment] 2020-12-28 16:17
Hi @andreawiki, 

Thank you for opening this GitHub issue!

The issue seems to point towards some issues within the request for Alipay.
Could you please provide us with the JSON request and response from the info.log (var/log/adyen folder) for a transaction that was successful and one that failed?
You could also share these logs within the zendesk ticket you had opened with us so we can further investigate. 

Regards, 
Floor 
Adyen

**Comment by andreawiki** [comment] 2021-03-23 06:24
Hi,

Attached please find the 2 log file for your handling.

Thanks,
Andrea


[Success - 4371.txt](https://github.com/Adyen/adyen-magento2/files/6187360/Success.-.4371.txt)
[Fail - 4520.txt](https://github.com/Adyen/adyen-magento2/files/6187361/Fail.-.4520.txt)

**Comment by floorjubbega** [comment] 2021-03-23 07:45
Hi @andreawiki,

I have deleted your comment including the logs, seeing it contains sensitive information (PSP, accountname). We will look into the logs.

I did notice that the successful request was for alipay_hk (using countrycode HK), while the invalid request used the generic type "alipay". Could you make sure to use type alipay_hk for your Hong Kong transactions and see if that resolves the issue you have been seeing?

Regards, 
Floor 
Adyen

**Comment by andreawiki** [comment] 2021-03-23 09:22
Hi， Please try these 3 cases, should be correct,  thxx

[ALIPAY 2.zip](https://github.com/Adyen/adyen-magento2/files/6188274/ALIPAY.2.zip)
[UNION PAY 2.zip](https://github.com/Adyen/adyen-magento2/files/6188275/UNION.PAY.2.zip)
[ALIPAY_HK.zip](https://github.com/Adyen/adyen-magento2/files/6188276/ALIPAY_HK.zip)

**Comment by cyattilakiss** [comment] 2021-06-09 13:03
Hi @andreawiki ,

Thank you for providing these details.
I've tested the following cases in a test environment with your request on my merchant account just to be sure that it's not a merchant account configuration issue and also tested these on the latest module version to see if it has been an issue on v6 but has been foxed in v7. Here are my findings:

Your requests provided with the reference: 
CUP and Unionpay 
- `000004549 ` We don't support cup at the moment in the Magento2 plugin and it will be supported via the card component not via a separate payment method
- `000004462` - Unionpay is supported via a separate component as a redirect payment method that's why it passed

Alipay_HK
- `000004544` I see only a redirect, did it fail to redirect the customer?
- `000004371` seems correct, the previous should have the same flow as well. Do you have any way to reproduce it?

Alipay
 - `000004546`  I see only a redirect, did it fail to redirect the customer? (passes with my merchant reference)
 - `000003218` indeed passing even with my merchant account
 
In case we can find a way to reproduce the issue with Alipay and Alipay_HK we can fix it but for now I am not able to reproduce it.
CUP is not supported at the moment but Unionpay is.

Best,
Attila
Adyen

**Comment by tnaber** [comment] 2021-12-29 15:11
Hi, 

Closing this issue, please reopen if this is still an active problem for you :)

Cheers,
Titus

**Closed by tnaber** 2021-12-29 15:11 UTC
Labels: Support question, Bug report, Progress: on hold, Needs more info
