### ISSUE TITLE
Google Pay Integration Issue 6.6.1

### ISSUE THREAD

**Issue by lucygecko** [Adyen/adyen-magento2#856] opened 2020-10-21 08:27 UTC
**Describe the bug**
The frontend displays 'Google Pay is not available' to the user. The console logs `Error: Google Pay - No paymentMethodPresent`

**To Reproduce**
1. Go to the checkout payment stage
2. Click the Google Pay option

**Expected behavior**
The Google Pay button to load at the payment stage

**Screenshots**
[Frontend](https://drive.google.com/file/d/1k5PIHDETt7EneWuZNyLh7sqqmiXCpzzi/view?usp=sharing)
[Console log](https://drive.google.com/file/d/12jyk4Nplhk8pwB8X4PzQdcstgSka3q7n/view?usp=sharing)

**Desktop (please complete the following information):**
Magento: 2.3.5-p1
Browser: chrome
Version: 6.6.1

**Comment by floorjubbega** [comment] 2020-10-22 09:49
Duplicate of #854

**Closed by floorjubbega** 2020-10-22 09:49 UTC
Labels: Bug report

**Comment by cyattilakiss** [comment] 2020-10-22 12:38
Hi @lucygecko ,

I believe the payment method is working but when you are testing you don't have any payment method set up in your own Google pay wallet. Please follow the steps of testing this payment method: https://docs.adyen.com/payment-methods/google-pay/web-component#test-and-go-live and let us know if you still see this message after the steps in the doc linked.

Best,
Attila
Adyen
