### ISSUE TITLE
Issue with Payment Capture

### ISSUE THREAD

**Issue by amfclearwell** [Adyen/adyen-magento2#565] opened 2019-10-31 11:11 UTC
**Magento version**: 2.3.3
**Plugin version**: 4.5.4
**Description**

We have just updated to Magento 2.3.3 and updated to 4.5.4 of the plugin. Since these updates our payments are no longer getting captured:

31 Oct 2019 10:22:12 New Order Customer Not Notified
31 Oct 2019 10:22:12 New Order Customer Not Notified
We will authorize £15.44 after the payment is approved at the payment gateway. Transaction ID: "882572517331238K"
31 Oct 2019 10:22:12 Customer Not Notified
Adyen Result response:
authResult: Authorised
pspReference: 882572517331238K

Cronjob is running but there appears to be an error thrown up on the next run immediately after an order is placed: "Error when running a cron job"

Not sure if anyone is able to advise on a fix or solution. The process was working without issue before the updates. Thanks.

**Comment by cyattilakiss** [comment] 2019-11-01 10:33
Hey @amfclearwell ,

Can you please send the details to support@adyen.com also?
I would suggest you to send the error logs that you have in Magento because probably it helps with a bit more details why the cron job has an error while running.
Also after it is fixed can you please share your learnings under this issue?

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment] 2019-11-07 13:31
Hi @amfclearwell ,

I will close this issue now, but please feel free to reopen if the issue is still need help here with it. Also we are happy to hear the solution if you have already found it.

Best,
Attila
Adyen

**Closed by cyattilakiss** 2019-11-07 13:31 UTC
