### ISSUE TITLE
3Ds1 redirect error after complete challenge

### ISSUE THREAD

**Issue by marquesdevopen** [Adyen/adyen-magento2#871] opened 2020-11-04 07:54 UTC
**Describe the bug**
Using adyen version 6.6.4 on magento 2.2.9
When a customer places an order through 3Ds1 they are redirected to payment. After authenticating, the redirect should go back to the success page, but it doesn't. Return an empty cart.

**To Reproduce**
1. Filled shipping and billing information
2. Use a 3ds1 card to complete the order
3. Complete the challenge 
4. The redirect should take you back to the success or error page, but it takes you to the cart indicating that it is empty.
5. We can see an error complaining about the quotes

**Expected behavior**
After complete the challenge, the redirect should take you back to the success or cart but not to the cart with 0 items. 

**Screenshots**
![Captura de pantalla 2020-11-03 a las 15 44 30](https://user-images.githubusercontent.com/39096480/98083678-01816500-1e7b-11eb-93cd-dbbde45111ab.png)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: chrome
 - Version: 86

**Additional context**

**Comment by cyattilakiss** [comment] 2020-11-04 08:38
Hi @marquesdevopen ,

Thank you for raising this issue. Are you able to reproduce it on your test environment or in your live environment maybe?
If so please contact [our support](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420) and please provide them the pspreference/offer where you noticed this issue, the logs related to that payment attempt and if possible the test website so we can try and reproduce it ourselves.
Please also indicate that you opened this issue on our github repo so they can find the necessary informations faster.

Best,
Attila
Adyen

**Comment by ebaschiera** [comment] 2020-11-04 10:08
Hi @marquesdevopen ,
does it happen to both logged-in customers and guests?

We are having a similar issue and we are investigating it.

Thank you.

**Comment by cyattilakiss** [comment] 2020-11-04 10:15
Hi @ebaschiera 
Could you please also send the same data to support so we can also start investigating it?

Maybe an extra piece of info that you could provide to us:
When redirecting back the customer after the authentication what requests do you see in the network tool of the browser?
Do you see the transparent/redirect and the process/redirect requests and after that the cart or do you maybe miss any of the redirect requests?

Thank you in advance,
Attila
Adyen

**Comment by ebaschiera** [comment] 2020-11-04 11:03
Hi @cyattilakiss ,

we are on Magento 2.3.0 and Adyen module 6.6.4.
The issue we are facing is with 3DS v1 with guest customers (not logged-in).
When coming back from the 3DS validation, the session is lost.
We see the transparent/redirect and the process/redirect requests. The issue happens on process/redirect, where the function `_getOrder()` runs this: `$incrementId = $this->_getCheckout()->getLastRealOrderId();`
Also the customer is logged out.
We are not in production. We are testing the latest version of the module before going in production.

Thank you!

**Comment by cyattilakiss** [comment] 2020-11-04 11:11
Hi @ebaschiera ,

This indeed looks like the session is still lost somehow. Could you please share the staging website with our support team to see if we can also reproduce this issue and maybe we are going to be able to spot something else.
Just out of curiosity is the session also lost in Firefox or only in Google chrome?

Thanks,
Attila
Adyen

**Comment by ebaschiera** [comment] 2020-11-04 16:02
It happens with Chrome, not with Firefox.

I sent to Support the URL of the website.

Thanks!

**Comment by ebaschiera** [comment] 2020-11-09 08:26
It turns out our problem affects Magento 2.2.8 and 2.3.0.
Per https://github.com/Adyen/adyen-magento2/commit/271fe93da5ce92bcf51a9f6add04683d9bebad59 the versions I mentioned are no more supported.

@marquesdevopen sorry for taking over your issue, I am out now.

**Comment by cyattilakiss** [comment] 2020-11-09 08:58
Hi @ebaschiera ,

We are going to create an FAQ page with the necessary steps for 2.2.8
I will keep the discussion in our support system going.

Hi @marquesdevopen ,

Do you have an update about the issue, is it still ongoing or could you find the solution together with support?

Best,
Attila
Adyen

**Comment by marquesdevopen** [comment] 2020-11-25 08:20
With the update of adyen to version 6.6.5 we have seen that the 3ds1 problem is solved and 3ds2 and 3ds1 work correctly. 
We still have the problem with minifieds in this version. When minified js and css are enabled, adyen does not work. This happens because the url of the js changes and .min.js is added to the file path, causing a 404 error where it cannot find these files.

**Comment by ebaschiera** [comment] 2020-11-26 18:12
In Magento 2.2 you have to do something like [this](https://github.com/magento/magento2/issues/5835#issuecomment-296290118).
[Here](https://github.com/Adyen/adyen-magento2/commit/04a0e657c5f4aa66ae9594fc71fb3c1745aff7b0) you can find the url to put in there.

**Comment by msilvagarcia** [comment] 2021-03-10 15:12
Hey there,

These issues should have been fixed by now. If that's not the case, let us know.

Kind regards,
Marcos
Adyen

**Closed by msilvagarcia** 2021-03-10 15:12 UTC
Labels: Bug report, Issue: Needs more info, Progress: on hold, Support question
