### ISSUE TITLE
Capture notification retries if product from order doesn't exist

### ISSUE THREAD

**Issue by jonathanribas** [Adyen/adyen-magento2#2248] opened 2023-10-02 13:44 UTC
**Describe the bug**
Capture notification is retried 5 times because a product that has been ordered doesn't exist anymore.

**To Reproduce**
1. Place an order with SKU `123`
2. Delete SKU `123` before Adyen capture notification is processed
3. Capture will run and fail when loading order here https://github.com/Adyen/adyen-magento2/blob/develop/Helper/Webhook/CaptureWebhookHandler.php#L99
5. Order never goes to next status and get stuck in workflow
6. Message set inside `error_message` column: `The product that was requested doesn't exist. Verify the product and try again.`

**Expected behavior**
Adyen notification should not depend on order items existing or not.

Important business logic can be plugged on `sales_order_invoice_pay` event and on this case, it will run the times notification is retried instead of a single time.

**Magento version**
2.4.6-p2

**Plugin version**
8.19.1

**Comment by candemiralp** [comment] 2023-10-04 15:42
Hello @jonathanribas,

Thank you for raising this issue.

Capture webhook tries to create an invoice. In order to create an invoice, you need line items of the order. In my opinion, this error message is valid and webhook shouldn't be processed in this case since invoice creation is not possible if the given product is removed. Moving the state to `processing` is not possible without creating an invoice. 

What do you think of trying only once and mark the notification as done if this exception is thrown?

Best Regards,
Can

**Comment by jonathanribas** [comment] 2023-10-04 21:03
Hi @candemiralp, thanks for your reply.

Actually it's not invoice creation that is throwing this exception, it's when order is freshly get here https://github.com/Adyen/adyen-magento2/blob/develop/Helper/Webhook/CaptureWebhookHandler.php#L99

On our side, Signifyd creates the invoice and Adyen capture notification updates invoice status to paid.

Your suggestion will help not dispatching invoice pay event several times but won't set invoice as paid.

**Comment by candemiralp** [comment] 2024-01-15 13:32
Hello @jonathanribas,

Apologies for the very late response, I completely missed your previous comment.

As I see your point now. I tried the following steps to reproduce the issue without success.

1. Capture mode has been set to `manual`
2. Place an order (Klarna and cart payments have been tried.)
3. Process the authorisation webhook
4. Manually capture the funds
5. Remove the item from the catalog
6. Process capture webhook

After those steps, every time I got order status `processing` without any issue. Do you have any other suggestion to reproduce this error?

Best Regards,
Can

**Comment by candemiralp** [comment] 2024-03-29 13:45
Hello @jonathanribas,

Thank you for your response. However, we still can't reproduce this issue unfortunately. 

I am closing this Github issue since it's not reproducible on the given version and the latest stable version.

Best Regards,
Can

**Closed by candemiralp** 2024-03-29 13:45 UTC
Labels: Bug report, Needs more info
