### ISSUE TITLE
[PW-7147] - Adyen Webhook is not updating order status in magento if we manually capture from Adyen customer area 

### ISSUE THREAD

**Issue by ashar01** [Adyen/adyen-magento2#1682] opened 2022-08-26 12:14 UTC
It looks like if capture set to manual or capture with delay then adyen plugin doesn't work properly. Below is the functionality of Adyen plugin after upgrade and before upgrade.
Adyen version 8
1- When we place order from magento it shows status 'Payment Review'.
2- After few minutes order status changes to 'Pending'.
3- As the capture delay is set to manual, We capture payments from Adyen customer area.
But the problem is it doesn't inform magento by changing status or adding comment that payment is being captured. We need to manually check each transaction one by one and match with magento and then create invoice which is hassle. However this works differently in Adyen version 6 plugin.

Adyen Version 6
1- When we place order from magento it shows status 'Payment Review'.
2- After few minutes order status changes to 'Pending'.
3- As the capture delay is set to manual, We capture payments from Adyen customer area.
4- Once payment is settled Adyen changes order status in magento to 'Complete' using webhook. (This no longer working in Adyen version 8 plugin)

Conclusion:
it looks like capture delay no longer supported.
It also looks like with latest version of plugin we can't capture payments from Adyen customer area

**Comment by Morerice** [comment] 2022-08-30 08:27
Hi @ashar01,

Thanks for opening this issue. I'm able to reproduce the issue where the capture request was triggered via the Adyen Customer Area. I will create an internal ticket for it.

In the meantime, you can create a capture request from the Magento admin order page, by creating an invoice. This will automatically trigger a capture request to Adyen, which will then be handled by the plugin.

Regards,
Jean
Adyen

**Comment by lano-vargas** [comment] 2022-09-09 11:50
I'm having similar issues on latest version Extension version 8.3.1. Where not matter what status we set in the configuration it's always in "Payment Review" . The setting "Order status: payment authorisation" is set to "Pending Payment" when an order is authorised via the webhook notification the status is still as  "Payment Review"  it should change to "Pending Payment" or "Pending" depending on each of your configuration mine is set to "Payment Review" unfortunately not happening.

Has anyone had to downgraded and is back working properly and is there any doc for this module on process for downgrading using composer ? Thanks in advance.

**Comment by Morerice** [comment] 2022-09-15 08:50
Hi @lano-vargas,

Are the webhooks that are being received triggered from functionality within the Adyen Magento module, or are they triggered from the Adyen customer area?

I'm asking because this issue is specifically for webhooks triggered from the customer area.

Thanks,
Jean
Adyen

**Comment by lano-vargas** [comment] 2022-09-15 11:08
Hi @Morerice.  

When we placed and order from the website on checkout page the status is in payment review. We wait a minute or so, we also check the webhook overview to see when it processed. but when we check the order the payment has message delivered from the webhook and its been authorised and we can see in Adyen portal is approved as well but  the status still in payment review, We're not really sure what's causing this, We have a ticket with support but yet  everything seems to be ok, cron job, configuration no errors etc.. all running ok but still this is lingering.... 

It may be or no be related to this issue, I'm not sure but it's getting frustrating.
Thanks

**Comment by Morerice** [comment] 2022-09-16 12:04
Hi @lano-vargas,

Thanks for your response. I understand your frustration, however based on your description it doesn't seem to be a problem related to this specific issue, since the webhook is not being triggered from an action in the Adyen customer area.

We are in close contact with our support team, so for your issue, it would be better if we kept using that communication channel.

Thanks,
Jean
Adyen

**Comment by ashar01** [comment] 2022-09-22 00:48
Hi @Morerice ,
Do you have any estimate for fixing this issue?

**Comment by Morerice** [comment] 2022-09-22 19:57
Hi @ashar01,

The linked PR will be in our next version that should be released this week.

Thanks,
Jean
Adyen

**Closed** 2022-09-30 11:41 UTC
Labels: Bug report
