### ISSUE TITLE
[PW-4998] Console error and unable to continue on checkout for iDeal when using legacy-build.js (prototype)

### ISSUE THREAD

**Issue by kweij** [Adyen/adyen-magento2#1063] opened 2021-06-07 14:29 UTC
Magento (sadly) still contains the `prototype` JS library which can be included by third patry modules. This horrible excuses for a library hacks into the prototypes of JS elements and can very likely cause incompattibility problems. Such is the case with "some code" that is being served in Adyen's minified `bundle.js`.

**To Reproduce**
1. Include the legacy-build.js (prototype) library by depending on it through requirejs
2. Have HPP payments active on the checkout
3. Click/select the Adyen HPP iDeal payment method (may also work with other payment methods)
4. Wait for totals to be recalculated (of an other async request that is being triggered by selecting a payment)

**Expected behavior**
No error in the console and being able to select a bank in the iDeal select field

**Magento version**
2.4.2-p1

**Plugin version**
7.0.1

**Console error**
```
legacy-build.min.js:formatted:1759 Uncaught (in promise) TypeError: Cannot read property 'removeChild' of null
    at remove (legacy-build.min.js:formatted:1759)
    at HTMLDivElement._methodized [as remove] (legacy-build.min.js:formatted:396)
    at t.r.cleanUp (bundle.js:23)
    at Object.r.onComplete (bundle.js:23)
    at t.<anonymous> (bundle.js:23)
    at bundle.js:23
    at Array.some (<anonymous>)
    at bundle.js:23
    at Array.some (<anonymous>)
    at ve (bundle.js:23)
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 91.0.4472.77

**Additional context: More stack tracing from the pretty-printed minified `budle.js`:**

> .. remove (legacy-build.min.js:formatted:1759):

```
    remove: function(b) {
        b = $(b);
        b.parentNode.removeChild(b);
        return b
    },
```

> .. t.r.cleanUp (bundle.js:23):

```
                r.cleanUp = function() {
                    r.nodeRiskContainer && r.nodeRiskContainer.remove()
                }
```

**Root cause / why this breaks:**
In `bundle.js:23` the _intended_ behaviour would be:
- to check if the `r.nodeRiskContainer` node exists
- if so remove it
- _expecting_ that after `.nodeRiskContainer.remove()` `r.nodeRiskContainer` would yield `false`
- a second/follow-up call to `r.cleanUp` shouldn't retrigger `.nodeRiskContainer.remove()`

However  the `prototype`  library alters the `.remove()` method for `Elements` into:
```
    remove: function(b) {
        b = $(b);
        b.parentNode.removeChild(b);
        return b
    },
```
And with this behaviour of `.remove()` the node `r.nodeRiskContainer` will not turn into `undefined` or `null` it will only have lost it's relation to the parent (`body` in this perticular case). Now the second call to `r.cleanUp`, `r.nodeRiskContainer` _still_ yields `true` and the code will try to perform `r.nodeRiskContainer.remove()` again which in `prototype` will try to get `b.parentNode` which is `null`. This throws the `TypeError: Cannot read property 'removeChild' of null`.

**Conclusion**:
"Some code" in `bundle.js` is not compattible with the `prototype` JS library. And I understand that, because .. why support that hellhole of a dependecy?! Sadly however, Magento provides this piece of doodoo so I guess the Adyen module should be compattible with it as well.

My workaround will be to seek the dependency that requires `prototype` and disable/remove it from the checkout (as it will not be need there anyways).

**Comment by acampos1916** [comment] 2021-06-22 13:31
Hello @kweij sorry for the late reply.

Thank you for the detailed report! Indeed this could be something we can look at. I've opened an internal ticket to work on this and will update with any progress made.

**Comment by AlexandrosMor** [comment] 2021-08-23 09:06
Hello @kweij, 

Could you please send us the Include the requirejs code snippet how do you include the legacy-build.js (prototype) library ?

kind regards
Alexandros
Adyen

**Comment by AlexandrosMor** [comment] 2021-08-23 20:00
Hello @kweij,

We added in the `frontend/requirejs-config.js` the `legacy-build.min` for testing:

```
var config = {
    paths: {
        'prototype': 'legacy-build.min'
    },
```
Ideal and the other payment methods worked without any `legacy-build.min.js` error in the console so
I would like to ask what is the reason that you have to add the ` 'prototype': 'legacy-build.min'` in the requirejs file or I might testing it wrong ? Furthermore We test our releases as it is and any modification to the plugin might cause issues.

kind regards
Alexandros
Adyen

**Comment by kweij** [comment] 2021-09-07 07:12
Hi @AlexandrosMor,

The culprit, in our case, is the VladimirPopov_Webforms module which adds the dependency on `prototype` as following:

```
define(['prototype','jquery','jquery/ui','mage/translate'], function () {
...
```

Because of Javascript bundling (a necessity for performance) prototype is included in the default bundle and so also loaded in the checkout. I suppose the simply adding `prototype` as a dependency in `requirejs-config.js` can de done as following:

```
    },
    deps: [
        "prototype"
    ]
};
```

Even without customization of the Adyen module, this issue should occur because the root-cause is the incompatibility with `prototype`.

Hope this helps to recreate the issue.

Kind regards,
Klaas

**Comment by AlexandrosMor** [comment] 2022-04-11 14:04
Hello @kweij, 
The bundle.js file is removed so we are not getting any console error testing with iDeal. You could try the latest plugin version as this issue is resolved

kind regards,
Alexandros
Adyen.

**Comment by AlexandrosMor** [comment] 2022-04-12 09:29
Hello @kweij,

The issue is solved in the latest versions so we will recommend to update the plugin. We are going to close this issue and feel free to open a new issue if it is needed. 

kind regards,
Alexandros
Adyen

**Closed by AlexandrosMor** 2022-04-12 09:29 UTC
Labels: Bug report, Priority: medium, To be investigated

**Comment by kweij** [comment] 2022-04-15 09:56
Hi @AlexandrosMor,

Thank you for your reaction, I will checkout the latest version of the plugin!
