### ISSUE TITLE
additionnal_information in payment table is truncated on big orders

### ISSUE THREAD

**Issue by Nuranto** [Adyen/adyen-magento2#1698] opened 2022-09-05 15:23 UTC
Making your own contribution is easy, encouraged and greatly appreciated! We will put effort into reviewing and merging your PR quickly. For more info, please refer to the contribution guidelines: https://github.com/Adyen/adyen-magento2/blob/develop/CONTRIBUTING.md

**Describe the bug**

On one of our order, `additional_information` in payment table is so big that it exceed the column size limit (TEXT). It leads to truncated text that causes errors in Magento (cannot list orders, cannot view concerned order, etc..)

```[2022-09-05T15:14:32.093988+00:00] .CRITICAL: InvalidArgumentException: Unable to unserialize value. Error: Control character error, possibly incorrectly encoded in /var/www/html/vendor/magento/framework/Serialize/Serializer/Json.php:45
Stack trace:
#0 /var/www/html/vendor/magento/framework/Model/ResourceModel/AbstractResource.php(153): Magento\Framework\Serialize\Serializer\Json->unserialize('{"guestEmail":"...')
#1 /var/www/html/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(489): Magento\Framework\Model\ResourceModel\AbstractResource->_unserializeField(Object(Magento\Sales\Model\Order\Payment\Interceptor), 'additional_info...', Array)
#2 /var/www/html/vendor/magento/module-sales/Model/ResourceModel/Order/Payment/Collection.php(80): Magento\Framework\Model\ResourceModel\Db\AbstractDb->unserializeFields(Object(Magento\Sales\Model\Order\Payment\Interceptor))
```

**To Reproduce**

I don't know how to reproduce

**Magento version**

2.4.5

**Plugin version**

8.4.0

**Comment by Nuranto** [comment] 2022-09-05 15:29
EDIT: It occurs 2 times actually. Both on very big orders (with a lot of products)

**Comment by Morerice** [comment] 2022-09-28 12:10
Hi @Nuranto,

I was not able to replicate the specified issue, even when I added a large number of products to the order. From my tests, the number of products does not impact the info saved by the adyen module in the `additional_information` field since the module does not save any product related info in this field.

The module does save the `action` variable in this field which can be quite long. However this variable cannot be deleted/truncated during payment processing since it is required by the module. However, it is possible to remove it once the payment is completed (after webhook handling).

Did this issue occur when the payment was done using a specific payment method? Also would it be possible for you to check if you have some other enabled module that is adding product data in the `additional_information` field?

Thanks,
Jean
Adyen

**Comment by Nuranto** [comment] 2022-09-28 12:47
Hi @Morerice,

The quantity of product was just a guess. It was not because of that then...

It happened 2 times only. Never since.

There is no other extension that could add data in the additional_information. 

I can send you the PSP reference if that can help.

**Comment by Nuranto** [comment] 2022-09-28 13:03
Of course !

It's done

**Comment by Suzell** [comment] 2022-11-30 16:44
Closing ticket since being handled via support email.

**Closed by Suzell** 2022-11-30 16:44 UTC
Labels: Bug report

**Comment by Nuranto** [comment] 2022-11-30 17:29
Note: I just disabled additionnal risk data option, which hide the issue. Doesn't mean the issue is resolved in this package.

**Comment by Nuranto** [comment] 2024-01-27 16:03
Update : We had several cases those past few days. (we did not changed anything in our conf, additionnal risk data option is still disabled). It's very annoying.

**Comment by Nuranto** [comment] 2025-03-10 16:00
Still annoying us every week....

**Comment by khushboo-singhvi** [comment] 2025-04-02 21:37
Hey @Nuranto,

Hope you are doing great! 

We’ve looked into it, and it appears that the `additional_information` field in the `sales_order_payment` table is getting truncated on large orders due to the default database column type being TEXT, which has a size limitation (~64KB).

We were unable to reproduce the case, But I would also recommend you going through the Adyen Support and raising the issue there, so we can actually check the PSPReferences and the logs. We assure a potential enhancement to avoid data loss in these scenarios, if we are able to track the usecase correctly and will update this thread once we have a fix or module patch available.

Let us know if you'd like help implementing a workaround in the meantime!

Regards!
Khushboo
