### ISSUE TITLE
Chargeback notifications error

### ISSUE THREAD

**Issue by dronerdk** [Adyen/adyen-magento2#1654] opened 2022-08-09 08:42 UTC
We see this error when having a chargeback (Klarna).

The webhooks cannot be processed and the error will keep be present in the top of the administration.

M2.4.3-p1
Adyen 8.2.5
<img width="1996" alt="Skærmbillede 2022-08-09 kl  10 39 45" src="https://user-images.githubusercontent.com/15999222/183605087-8f701437-20f7-4bd6-87ed-adf786ced134.png">

**Comment by Morerice** [comment] 2022-08-09 12:21
Hi @dronerdk,

Thanks for opening this issue. However this is a duplicate of https://github.com/Adyen/adyen-magento2/issues/1494. Please follow this issue for any updates.

Thanks,
Jean
Adyen

**Closed by Morerice** 2022-08-09 12:21 UTC
Labels: Duplicate, Bug report
