### ISSUE TITLE
[ECP-8681] Order can not be cancelled

### ISSUE THREAD

**Issue by ajith107** [Adyen/adyen-magento2#2265] opened 2023-10-09 17:42 UTC
**Prerequisite**

- Adyen Magento 2 module is installed and enabled.
- Adyen Credit Card payment is set up and working fine.
- Capture delay settings is **immediate** on both Magento & Adyen settings.
- Enabled Adyen Risk management

**Describe the bug**
The Adyen module is trying to cancel the order when Magento processing the `CANCEL_OR_REFUND` notification. However, Magento provides the following error and the order is stuck at the initial status `payment_review` or `pending`

```
AdyenLoggerTest.ADYEN_NOTIFICATION: Order can not be cancelled
```

**To Reproduce**

After investigating, Here are the findings

1. As we already know the initial order status is "pending" or "payment_review" for the Adyen orders. Let's just assume the order goes into case management for Manual review.
2. Even though the payment goes into case management, Magento still gets the `AUTHORISATION` notification from Adyen and Magento is processing it.
3. Once the `AUTHORISATION` notification is processed, Magento creates the Invoice for that particular order and keeps the order status as still `pending`, because the payment has gone to Case management.
4. On case management, If the payment has been rejected due to a fraud check, then Magento receives the `CANCEL_OR_REFUND` notification.
5. Upon processing, the CANCEL_OR_REFUND notification Magento is trying to cancel the order. But this will not work out here... Since the invoice is already created in Magento. _(by the AUTHORISATION notification)_. We can not cancel the order in Magento. That’s how the core Magento works.
6. In this case, we can’t cancel the order. However what we can do here is,  Since the payment is already rejected on the Adyen portal, We can create the Offline credit memo in Magento which will create an offline credit memo for the orders and the order status will also updated to `closed`

**Expected behavior**

- Since the invoice has been already created on Magento, we have to create a credit memo for this order. Adyen can create offline credit memo in this case

**Magento version**

- 2.4.5

**Plugin version**

- 8.13

**Additional context**

- We can provide a fix for creating an offline credit memo around these areas
- https://github.com/Adyen/adyen-magento2/blob/develop/Helper/Webhook/CancelOrRefundWebhookHandler.php#L58
- https://github.com/Adyen/adyen-magento2/blob/develop/Helper/Webhook/CancelOrRefundWebhookHandler.php#L82

**Comment by candemiralp** [comment] 2023-10-12 07:47
Hello @ajith107,

Thank you for creating this Github issue. We created an internal ticket to solve this issue. Once the investigation has been completed, we will inform you.

Best Regards,
Can

**Comment by candemiralp** [comment] 2023-10-30 15:30
Hello @ajith107,

Thank you for your patience during our investigation. I tried to reproduce the issue on v8.13.0, v8.22.2 and v9.0.2. However, I couldn't succeed. My environment was set to immediate capture as well as Adyen configuration was on immediate capture. I created a custom risk rule and that rule triggers manual review for case managements.

My observations are below.

1. If the capture mode is set to immediate on both platforms, Magento will create a paid invoice and Adyen will capture the payment automatically. In this case, there won't (can't) be cancellation because this authorisation has been captured already. This payment should be refunded for failing reviews. If the manual case review is rejected, Adyen will send a `CAPTURE_OR_REFUND` webhook and `modification.action` field in the webhook body will be `refund`. This flow is handled in CaptureOrRefundWebhookHandler [here](https://github.com/Adyen/adyen-magento2/blob/58d86ce58be1f3f974f541a584435e7fc2c2a0fe/Helper/Webhook/CancelOrRefundWebhookHandler.php#L59). After processing this webhook, a credit memo will be created and order will be closed.

2. If the capture mode is set to manual on both platforms, Magento won't create an invoice and Adyen will the payment in authorized state only. In this case, authorisation can be canceled. If the manual case review is rejected, Adyen will send a `CAPTURE_OR_REFUND` webhook and `modification.action` field in the webhook body will be `cancel`. This flow is handled in CaptureOrRefundWebhookHandler [here](https://github.com/Adyen/adyen-magento2/blob/58d86ce58be1f3f974f541a584435e7fc2c2a0fe/Helper/Webhook/CancelOrRefundWebhookHandler.php#L57C18-L57C18). After processing this webhook, the order will be cancelled.

If you see `Order can not be cancelled` error message in the logs, it indeed indicates that `$order->canCancel()` returns `false`. In this case, I assume your webhook body contains `modification.action: 'cancel'`. However, ideally you shouldn't get this modification action for auto capture payments. There could be a misconfiguration in your Customer Area for risk management. 

In the screenshot below you can see the expected payment events in the correct descending order. Could you please confirm that you have `Capture - <auto>` in the payment events block of your Payment Details page of an example payment after `Payment` line and before `Manual Review` line?

<img width="821" alt="Screenshot 2023-10-30 at 16 23 38" src="https://github.com/Adyen/adyen-magento2/assets/20255503/df557a9f-07ea-46a9-aa83-c38bf5e1bed5">

Best Regards,
Can

**Comment by candemiralp** [comment] 2023-11-14 12:27
Hello @ajith107,

I wonder did you have any time to check the comment above?

Best Regards,
Can

**Comment by ajith107** [comment] 2023-11-14 12:31
@candemiralp Really thanks for your detailed explanation.
we have contacted the Adyen support regards to this issue and the case is closed. 

Case number - 03117977

Please feel free to close this issue, If you would like

**Comment by candemiralp** [comment] 2023-11-14 12:53
Hello @ajith107,

Thank you very much for confirming the issue. I am closing this Github issue since the issue was resolved by our support team.

Best Regards,
Can

**Closed by candemiralp** 2023-11-14 12:53 UTC
Labels: Bug report
