### ISSUE TITLE
6.3.0 frontend checkout payments not working

### ISSUE THREAD

**Issue by PascalBrouwers** [Adyen/adyen-magento2#774] opened 2020-07-24 08:10 UTC
**Describe the bug**

**To Reproduce**
1. Go to checkout and then payment step
2. Error: 
Uncaught TypeError: AdyenCheckout is not a constructor
    at UiClass.initialize (adyen-hpp-method.min.js:1)

**Expected behavior**
No error and payment methods should show

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 83.0.4103.116

**Additional context**
Please fix the frontend requirejs

**Comment by AlexandrosMor** [comment] 2020-07-28 12:46
Hello @PascalBrouwers ,

Can you see the payment methods ? Otherwise sounds that the plugin is not installed.

kind regards,
Alexandros

**Comment by PascalBrouwers** [comment] 2020-07-28 12:50
Upgrading the module would not disable it, or am I wrong?

**Comment by bmxpasw** [comment] 2020-07-29 07:07
We got the same error. Clear cache / deploy / etc didn't solve it.

![image](https://user-images.githubusercontent.com/27968209/88768156-f41d5600-d17a-11ea-8256-9701a0464f33.png)

**Comment by Caudalie** [comment] 2020-07-30 14:11
Hi,

Same issue with Magento 2.3.2. No error logs in the folder Adyen.

![adyen_error](https://user-images.githubusercontent.com/35835058/88933011-1e583c00-d27f-11ea-868a-1051e47f7201.JPG)

**Comment by justinpappalil** [comment] 2020-08-07 07:46
Reproduced the same issue at our end. We upgraded to the latest version of Adyen but the payment section is not loading in the checkout step. We got the error mentioned above.

**Comment by Caudalie** [comment] 2020-09-01 17:19
I just tried your new release 6.5.0 and the payment section still doesn't load in the checkout.

```
GET https://checkoutshopper-live.adyen.com/checkoutshopper/sdk/3.4.0/adyen.min.js net::ERR_ABORTED 404 (Not Found)

[ERROR] Failed to load the "Adyen_Payment/js/view/payment/method-renderer/adyen-oneclick-method"

[ERROR] Failed to load the "Adyen_Payment/js/view/payment/method-renderer/adyen-hpp-method" component.
```


any chance to get a help ?
I cannot update since the 6.2.1

**Comment by acampos1916** [comment] 2020-09-02 07:10
Hello @Caudalie, thank you for the additional information.

In your last message I can see that your instance is trying to fetch adyen.min.js, but that resource doesn't exist. You probably have set up Magento to minify JS assets automatically but that library is not hosted in your server and the .min version is not available in checkoutshopper-live.adyen.com.

You would have to add a minification exclusion for the adyen.js library by creating a custom module with a config.xml for that value or adding a config path for `dev/js/minify_exclude` and a pattern from the URL (e.g. that includes `checkoutshopper-live.adyen.com` and `checkoutshopper-test.adyen.com`). Both alternatives are described in this [Magento issue](https://github.com/magento/magento2/issues/5835).

The plugin can't be released with this exclusion because previously loaded config values for that path could be overwritten, this should be done only once in the Magento instance for that scope following the recommendations in that Github issue.

@justinpappalil @PascalBrouwers @bmxpasw could you confirm if this is the same problem you're experiencing and if this workaround works?

Best,
Ángel

**Comment by nishpatel** [comment] 2020-09-04 19:21
Hi Ángel we are experiencing the same issue. 
The request url is: https://checkoutshopper-live.adyen.com/checkoutshopper/sdk/3.4.0/adyen.min.js
Will use the alternatives described not ideal.

Thanks

Nish

**Comment by LexKoomen** [comment] 2020-09-15 09:02
You can upgrade by disabling JS minification. But this seems like a really small issue on your end... How come you still didnt fix this... All you have to do is duplicate the js code on your end and make it available on .min.js............

come on guys

**Comment by acampos1916** [comment] 2020-10-06 13:06
Hello all,

With #816 we added a JS minification inclusion so Magento doesn't try to minify adyen.js. This was released on 6.6.0.

I'll close this issue now but feel free to reach out with additional insights.

Ángel

**Closed by acampos1916** 2020-10-06 13:06 UTC
Labels: Bug report

**Comment by amenk** [comment] 2020-12-14 06:44
@acampos1916 
We have the same problem on 6.6.5 - actually we use Amasty Page Speed Optimizer, which also das JS optimization and minification. Probably we have to add an exclude here as well. There seems an option for this

Would it makse sense to add compatibility / documentation for the Amasty Module in the Adyen module or would the other way around be the way to go?

**Comment by acampos1916** [comment] 2020-12-14 08:10
Hey @amenk, thanks for this report of the compatibility with Amasty Page Speed Optimizer,

Be aware that the minification config was reverted in 6.6.1, it caused issues in some Magento versions so it is expected to see this issue still. We're working on a RC that moves the JS resource to the plugin and that would get rid of this issue https://github.com/Adyen/adyen-magento2/tree/7.0.0-rc.1.

As for the documentation, we have a short article on how to manually add the exclusion [here](https://www.adyen.help/hc/en-us/articles/360016010120-Why-do-I-get-a-404-error-for-adyen-min-js-after-activating-Magento-s-JS-minification-)

**Comment by amenk** [comment] 2020-12-15 07:30
@acampos1916 We were not yet successful with using the Adyen + Amasty JS Optimizations together. The interesting part is, that the minify-exclusion option is hidden, when Amasty JS Optimization is in place. So I guess it is also not used then.

What is the ETA for 7.0.0 release? Does it make any sense to wait?

**Comment by acampos1916** [comment] 2020-12-15 08:06
@amenk maybe the Amasty Optimization ignores the JS minify exclusion and uses its own configuration for this. If you do find a way to make it work let us know!

ETA for 7.0.0 is 3-4 weeks from now.

**Comment by amenk** [comment] 2021-01-08 07:30
This works in a config.xml:

    <default>
        <dev>
            <js>
                <minify_exclude>
                    <adyen>https://checkoutshopper-live.adyen.com/checkoutshopper/sdk/3.4.0/adyen.js</adyen>
                </minify_exclude>
            </js>
        </dev>
    </default>


Still wondering if the subnode is required or if

n98-magerun2 config:store:set "dev/js/minify_exclude" "https://checkoutshopper-live.adyen.com/checkoutshopper/sdk/3.4.0/adyen.js"

also should work

**Comment by AlexandrosMor** [comment] 2021-01-08 07:34
Hello @amenk 

The exclude minification in the config works for magento versions 2.3 and will not work for lower versions like 2.2. 

kind regards,
Alexandros
Adyen

**Comment by amenk** [comment] 2021-01-08 08:00
thanks, we are on 2.3 -- so config:store:set might also work?
