### ISSUE TITLE
Module version 6.6.2 not compilable on Magento 2.2.11

### ISSUE THREAD

**Issue by AlvaroOleaAlfa9** [Adyen/adyen-magento2#864] opened 2020-10-28 08:57 UTC
**Describe the bug**
The last version of the module is not compilable on the last minor version of Magento 2.2.11. The module README says that it supports at least 2.2.8. It seems a problem with the implementation of the "**CsrfAwareActionInterface**" Interface, that seems to only be available on Magento 2.3.X

**To Reproduce**
1. Install a Magento 2.2.11 environment.
2. Install Adyen Payment module, version 6.6.2.
3. Execute compile command: `php bin/magento setup:di:compile`
4. See error: `PHP Fatal error:  Interface 'Magento\Framework\App\CsrfAwareActionInterface' not found in /XXX/vendor/adyen/module-payment/Controller/Transparent/Redirect.php on line 33`

**Expected behavior**
Compilation should be executed correctly.

**Comment by AlexandrosMor** [comment] 2020-10-28 09:25
Hello @AlvaroOleaAlfa9,

Thank you for pointing the issue,  We are going to fix it and make a release as soon as possible

kind regards
Alexandros

**Comment by AlexandrosMor** [comment] 2020-10-29 14:43
Hello @AlvaroOleaAlfa9, 

The issue is fixed by the latest release [6.6.4](https://github.com/Adyen/adyen-magento2/releases/tag/6.6.4)

kind regards
Alexandros

**Closed by AlexandrosMor** 2020-10-29 14:43 UTC
Labels: Bug report
