### ISSUE TITLE
[PW-2639] [Klarna] Phone format restriction is not UX-friendly

### ISSUE THREAD

**Issue by philippe-caer** [Adyen/adyen-magento2#749] opened 2020-06-29 07:49 UTC
This ticket is created as per Support request #1411529

**Is your feature request related to a problem? Please describe.**
When you are using Adyen extension v6 on Magento 2, and you select Klarna Slice it option at checkout, you get asked your "telephone". Once typed, when you click on "place order", you get an error message if you typed a space or dash or anything not numerical in the phone field. Consequently, 99% of customers will get this error message without knowing the field is numerical only.

**Describe the solution you'd like**
1a. Do not ask customer's phone if he already has typed it in his information/address.
1b. Else, rename Telephone by Phone
2. Remove restrictions applied on this field, or make sure that official phone numbers such as "+1 (555) 555-1234" (for the US) or "01.48.19.27.98" (for France) are considered valid.

If Klarna needs numbers only, this should be managed on your side (back-end), not on front (from a UX perspective).

**Describe alternatives you've considered**
If too complicated, at least inform the customer only numbers should be entered in the field

Thanks !

**Comment by acampos1916** [comment] 2020-07-06 06:47
Hello @philippe-caer,

Thanks for opening this issue. It seems related to #747 and we'll take a look at improving the validation and error message for the Klarna phone field.

Cheers,
Ángel

**Comment by floorjubbega** [comment] 2020-10-21 09:47
Duplicate of #747

**Closed by floorjubbega** 2020-10-21 09:47 UTC
Labels: Enhancement
