### ISSUE TITLE
Configuration "Notification User Name" and "Notification Pasword" should be set at store view level

### ISSUE THREAD

**Issue by pascalexperius** [Adyen/adyen-magento2#917] opened 2020-12-18 11:02 UTC
The "Notification User Name" and "Notification Password" settings are configured at website level.

`showInStore="0"` 

Which is applied for the settings:

payment_other/adyen_group_all_in_one/adyen_required_settings/notification_username
payment_other/adyen_group_all_in_one/adyen_required_settings/notification_password

As a result, the Adyen module allows you to add the same username / password for 

Website: website.com
Storeview: website.be
Storeview website.nl

Since a merchant might choose to use a seperate Adyen account for a storeview.be (for example when testing a new storeview and use an Adyen test-account for this storeview), these settings should be set on storeview level too.

`showInStore="1"`

File: 

adyen-magento2/etc/adminhtml/system/adyen_required_settings.xml

**Comment by peterojo** [comment] 2020-12-29 12:39
Hi @pascalexperius thanks for contacting us. This setting is by design; this plugin supports using only one set of notification credentials to receive payment updates in all Storefronts of the website. We advise merchants to not to use the same API credentials across different websites and to use test credentials for test integrations. Please checkout the [documentation](https://docs.adyen.com/plugins/magento-2/set-up-the-plugin-in-magento) for more information.
I will close this issue, but please reach out to us if you find other issues.

**Closed** 2020-12-29 12:40 UTC
Labels: Enhancement, wontfix
