### ISSUE TITLE
Refused Credit card payment - no status saved to order

### ISSUE THREAD

**Issue by paulappelbe** [Adyen/adyen-magento2#901] opened 2020-12-03 08:14 UTC
**Describe the bug**
When paying by credit card, and the payment is refused, there is an order that is created with an empty status.
There didn't use to be an order created upon refused orders.

**To Reproduce**
1. Create an order
2. Attempt to pay by credit card and get a refused status
3. go to orders section in admin
4. look at the order (that shouldn't be created) status for your customer - it is null

**Expected behavior**
Do not create order OR create order with refused status

**Comment by acampos1916** [comment] 2020-12-03 08:28
Thanks for opening this issue @paulappelbe,

Depending on the type of card an order can be created even for a failed payment. For example, 3DS1 failed payments will [create an order that will be cancelled by a notification](https://github.com/Adyen/adyen-magento2/blob/master/Controller/Process/Redirect.php#L226). Can you see that comment in the order history?

Cheers,
Ángel

**Comment by paulappelbe** [comment] 2020-12-03 08:38
Hi @acampos1916 
It's all payments, we dont have 3DS setup.
simply using the test card 4111 1111 1111 1111 with the wrong date or cvv it creates the order with a null status, and it never gets updated by notifications
Paul

**Comment by acampos1916** [comment] 2020-12-03 08:46
Thanks for the extra info @paulappelbe,

I was not able to reproduce the issue with 4111 1111 1111 1111 with the wrong date or cvv. Is there any error message in your instance's logs?

**Comment by paulappelbe** [comment] 2020-12-07 09:05
Hi @acampos1916 
Here are some logs : it all seems normal.
There seem to be a couple of problems related to refused payments where it is not handled. If you use a fake or wrong card, it creates the order in the admin, but it shouldn't, and Adyen doesn't return the refused status, and if you set a payment as refused in the Adyen interface, the status is not updated in Magento.
Thanks,
Paul

```
[2020-12-07 08:21:07] main.ERROR: Unable to place order: The payment is REFUSED. {"exception":"[object] (GraphQL\\Error\\Error(code: 0): Unable to place order: The payment is REFUSED. at /var/www/html/magento/vendor/webonyx/graphql-php/src/Error/Error.php:174, Magento\\Framework\\GraphQl\\Exception\\GraphQlInputException(code: 0): Unable to place order: The payment is REFUSED. at /var/www/html/magento/vendor/magento/module-quote-graph-ql/Model/Resolver/PlaceOrder.php:100, Magento\\Framework\\Exception\\LocalizedException(code: 0): The payment is REFUSED. at /var/www/html/magento/vendor/adyen/module-payment/Gateway/Validator/CheckoutResponseValidator.php:211)"} []


[2020-12-07 08:21:07] AdyenLoggerTest.INFO: JSON Response to Adyen:{"additionalData":{"expiryDate":"3\/2031","cardBin":"411111","cardHolderName":"Checkout Shopper PlaceHolder","cardSummary":"1111","paymentMethod":"visa","merchantReference":"ECV000001252"},"pspReference":"883607329267951C","refusalReason":"CVC Declined","resultCode":"Refused","refusalReasonCode":"24","merchantReference":"ECV000001252"} {"is_exception":false} []
[2020-12-07 08:21:07] AdyenLoggerTest.ADYEN_NOTIFICATION: The content of the notification item is: Array
(
    [additionalData] => Array
        (
            [expiryDate] => 03/2031
            [cardBin] => 411111
            [cardHolderName] => Checkout Shopper PlaceHolder
            [cardSummary] => 1111
            [merchantReference] => ECV000001252
            [hmacSignature] => c/cj7zsa/8lJq991Rk57himuoLTdPddt9EcvW0fQw6U=
        )

    [amount] => Array
        (
            [currency] => EUR
            [value] => 2290
        )

    [eventCode] => AUTHORISATION
    [eventDate] => 2020-12-07T09:21:07+01:00
    [merchantAccountCode] => merchantAccountCode
    [merchantReference] => ECV000001252
    [paymentMethod] => visa
    [pspReference] => 883607329267951C
    [reason] => CVC Declined
    [success] => false
)
 {"is_exception":false} []
[2020-12-07 08:21:07] AdyenLoggerTest.ADYEN_NOTIFICATION: The result is accepted {"is_exception":false} []

```

**Comment by acampos1916** [comment] 2020-12-07 12:39
Thanks for the logs @paulappelbe. I did some more testing and was still not able to reproduce using 4111...

Could you step-debug the plugin and Magento instance at [this point](https://github.com/magento/magento2/blob/2.4/app/code/Magento/Quote/Model/QuoteManagement.php#L411)? The REFUSED exception should stop the quote from being submitted into an order there.

**Comment by paulappelbe** [comment] 2020-12-07 15:05
Hi @acampos1916 
It's not being stopped at that point, and continuing on until [here](https://github.com/magento/magento2/blob/53ad434d78cd2d357203fb82e5ea059883f403b8/app/code/Magento/Sales/Model/Order/Payment.php#L437) where it stops.
In the [place function](https://github.com/magento/magento2/blob/53ad434d78cd2d357203fb82e5ea059883f403b8/app/code/Magento/Sales/Model/Order/Payment.php#L341) the action is authorize, order state is new, and status remains empty.

**Comment by acampos1916** [comment] 2020-12-08 09:38
Thanks @paulappelbe.
Yes, the exception is thrown further into the order submit action. If I try to reproduce the issue I get the same results (In the place function the action is authorize, order state is new, and status remains empty) but still no order is created. I believe that there might be some extra logic going on, maybe a third party plugin?

**Comment by gudal** [comment] 2020-12-11 14:30
Hello, 

No, there is no third party plugin installed

Thanks, 
Guillaume Dalaudier

**Comment by acampos1916** [comment] 2020-12-14 08:25
Are you able to find out why the exception being thrown doesn't prevent the quote from being submitted? I believe this is standard Magento behavior. Also, which Magento version is being used?

**Comment by gudal** [comment] 2020-12-14 09:43
We are using Magento 2.3.4-p2

**Comment by acampos1916** [comment] 2020-12-15 08:10
Thanks @gudal @paulappelbe, let us know if you find out why the exception being thrown doesn't prevent the quote from being submitted, I think that should be standard Magento behavior, unrelated to the plugin.

For now I will be closing this issue as it doesn’t seem to be reproducible but if you do find something interesting shoot us a message and we can reopen it.

**Closed by acampos1916** 2020-12-15 08:10 UTC
Labels: Bug report

**Comment by TonyRutherford1** [comment] 2021-02-04 12:01
@acampos1916 We also have this issue with failed orders not showing a status in order grid

**Comment by acampos1916** [comment] 2021-02-05 08:15
Thanks @TonyRutherford1, are you then able to reproduce [these steps](https://github.com/Adyen/adyen-magento2/issues/901#issuecomment-739974885)? And if so are you able to find out why the exception being thrown doesn't prevent the quote from being submitted?
