### ISSUE TITLE
Error in in-person payment: The transaction could not be completed

### ISSUE THREAD

**Issue by jocielandrade** [Adyen/adyen-magento2#2026] opened 2023-04-11 21:09 UTC
After payment confirmation in Adyen's POS, the message "The transaction could not be completed" was displayed in Magento's website and the order was not created. The payment was created in Adyen's side with the current date/time in the field "Merchant reference".

1. Go to https://sales.redbydufry.com/br/
2. Add a product to cart and go to checkout page
3. Enter data for steps 1 and 2;
4. In step 3 (payment) select the option "Pagar na loja (estou na loja)" (pay at store);
5. Select the terminal and click to place the order;
6. Confirm the payment at POS.

Expected behavior:
The payment is confirmed in POS and the order is created in Magento.

Current behavior:
The payment is confirmed in POS but the error message "The transaction could not be completed" is displayed in the website and the order is not created in Magento.

Magento version:
2.4.5-p1

Plugin version:
8.14.0

Screenshots:
![image](https://user-images.githubusercontent.com/9613351/231287972-1641fa6a-838e-4c09-ba7a-d556669bd114.png)
![image](https://user-images.githubusercontent.com/9613351/231288469-09ca690d-4f72-4231-a0b6-8ca03561006f.png)

Adyen's Account:
Company: DufryAG
Merchant Account: DufrydoBrasil_POS
PSP Reference: NL7FPR2636M72Q42

**Comment by candemiralp** [comment] 2023-04-28 14:51
Hello @jocielandrade,

Thank you for raising this issue and apologies for the late reply. Meantime, we were investigating the reason of the failure on the POS payment request and the information on the Github issue is not enough to identify it. In this case, further investigation is required and we don't consider sharing screenshots and payment logs on Github safe.

We saw that you already have an support request for the same issue, we would prefer communicating through that ticket. One of our support engineers will reach out to you about this issue. We kindly ask any kind of evidence to reproduce the issue from your side.

For the visibility I will keep that Github issue open until the issue is resolved. Afterwards, the external contributors will be informed if there is a bug.

Best Regards,
Can

**Comment by candemiralp** [comment] 2023-05-03 16:57
Hello @jocielandrade,

Once again, thank you for raising this issue. Internal ticket was closed since the issue was resolved. I am also closing this Github issue. If you have further questions, please do not hesitate to re-open this issue.

Best Regards,
Can

**Closed by candemiralp** 2023-05-03 16:57 UTC
Labels: Bug report
