### ISSUE TITLE
Order being canceled before receiving notification of approved payment (Brazilian PIX)

### ISSUE THREAD

**Issue by yuri-calabrez** [Adyen/adyen-magento2#1745] opened 2022-09-30 15:42 UTC
Hello
Hope you are doing great.

We are facing an issue that after the order is placed, we are receiving a payment canceled response, but soon after the order paid notification is received.

**Magento version**
2.4.2-p2

**Plugin version**
8.4.0

**Screenshots**
![image](https://user-images.githubusercontent.com/20018267/193306038-d1b8baad-49ff-42d7-abcc-8e7be78ecb5d.png)
![image](https://user-images.githubusercontent.com/20018267/193306689-134b4b38-4b8b-4eb9-9b13-17aedfdaf5b8.png)

**Comment by Morerice** [comment] 2022-10-03 11:58
Hi @yuri-calabrez,

Thanks for opening this issue. Could you please provide some steps to reproduce this issue? And are there other payments that are successfully going trough on pix? Or are all orders with this payment method failing because of this?

Thanks,
Jean
Adyen

**Comment by yuri-calabrez** [comment] 2022-10-03 22:08
Hi @Morerice 

We were unable to reproduce the error, at first it only occurred in the production environment. But basically the user finalizes the payment and finalizes the purchase. After that, around 2min more or less, we received this cancellation response.

**_And are there other payments that are successfully going trough on pix?_**
Yes, this bug only occurred in some orders, which makes it even more difficult to reproduce the error.

Regards,
Yuri

**Comment by Morerice** [comment] 2022-10-06 07:18
Hi @yuri-calabrez,

Since the issue is not reproducible and because no problematic specific code snippet has been identified, can you open a ticket with our support team by contacting support@adyen.com? There we would be able to share logs to try and identified what's causing this issue.

Thanks,
Jean
Adyen

**Comment by Morerice** [comment] 2022-11-03 07:54
Hi @yuri-calabrez,

This issue has been addressed in https://github.com/Adyen/adyen-magento2/pull/1802

Regards,
Jean
Adyen

**Closed by Morerice** 2022-11-03 07:54 UTC
Labels: Bug report
