### ISSUE TITLE
Error with HPP methods with virtual checkout

### ISSUE THREAD

**Issue by RaphaelBronsveld** [Adyen/adyen-magento2#418] opened 2019-03-11 09:52 UTC
**Magento version**: 2.2.5 
**Plugin version**: 3.0.0 (also reproduced on 2.3.0)
**Description**

Hi, we currently have some problems related to the virtual checkout. We have an issue where customers are able to click on the "place order" button without having a billing address. This results in a full screen loader, and since there is no error handling here, customers are forced to refresh the checkout. 

**Steps to reproduce**
- Make sure HPP methods are visible on initial load (default country / merchant country)
- Create a virtual product and add this to the cart.
- Proceed to checkout (as a guest, without any pre-filled data)
- Payment method is visible (e.g. iDeal in our example), or default payment method Check / Money order

HPP Method:
![Screenshot 2019-03-11 at 10 36 41](https://user-images.githubusercontent.com/42035462/54113951-a53a1980-43e9-11e9-86c3-a9e18b3c50d6.png)

Check / Money Order
![Screenshot 2019-03-11 at 10 36 33](https://user-images.githubusercontent.com/42035462/54113952-a53a1980-43e9-11e9-990a-e707a19bba59.png)

If a customer tries to place the order, it'll result in the full screen loader (and no error feedback).
By default, Magento disables the place order button when there is no billing address set.
https://github.com/magento/magento2/blob/0eb8677b0b4e35606032e856cc1ef7c80e68829f/app/code/Magento/Checkout/view/frontend/web/js/view/payment/default.js#L43

And in the template for the button:
https://github.com/magento/magento2/blob/0eb8677b0b4e35606032e856cc1ef7c80e68829f/app/code/Magento/OfflinePayments/view/frontend/web/template/payment/checkmo.html

However (for the HPP methods):
https://github.com/Adyen/adyen-magento2/blob/3.0.0/view/frontend/web/template/payment/hpp-form.html#L175

Note: I only checked this for the iDeal and Klarna method. All the other methods (non-hpp) seem to be going fine.

Thanks in advance!

**Comment by cyattilakiss** [comment] 2019-03-13 11:27
Hi @RaphaelBronsveld ,

This issue was fixed in the #390 which was release in the version 4.0.0
Can you please confirm if the issue is solved after updating or cherry picking the solution?

Best,
Attila
Adyen

**Comment by RaphaelBronsveld** [comment] 2019-03-13 11:49
Hi @cyattilakiss , thanks for the reply!

It seems that I'm not able to update due to #419 . I'll wait for that issue and update when it is ready.

Gr, Raphael

**Comment by cyattilakiss** [comment] 2019-03-13 14:09
Hi @RaphaelBronsveld ,

#419 is solved now, please let me know if the update helps.

Best,
Attila
Adyen

**Closed** 2019-03-19 20:46 UTC
