### ISSUE TITLE
php8 error when bundled product in cart

### ISSUE THREAD

**Issue by skeutmeier** [Adyen/adyen-magento2#1974] opened 2023-02-27 14:10 UTC
Making your own contribution is easy, encouraged and greatly appreciated! We will put effort into reviewing and merging your PR quickly. For more info, please refer to the contribution guidelines: https://github.com/Adyen/adyen-magento2/blob/develop/CONTRIBUTING.md

**Describe the bug**
When having a bundled product in cart, there is an php8 compatibilty error thrown

**To Reproduce**
1. Add bundled product to cart
2. try to checkout with klarna

**Expected behavior**
be able to checkout with klarna

**Magento version**
2.4.4p2

**Plugin version**
8.15.0

**Screenshots**
from system.log:
main.CRITICAL: Exception: Deprecated Functionality: number_format(): Passing null to parameter #1 ($num) of type float is deprecated in /[DOCROOT]/vendor/adyen/module-payment/Helper/Data.php on line 375 in  /[DOCROOT]/vendor/magento/framework/App/ErrorHandler.php:61

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version 110.0.5481.100

**Comment by Morerice** [comment] 2023-03-07 08:40
Hi @skeutmeier,

I'm closing this issue since it's a duplicate of https://github.com/Adyen/adyen-magento2/issues/1976.

Regards,
Jean
Adyen

**Closed by Morerice** 2023-03-07 08:40 UTC
Labels: Bug report

**Comment by skeutmeier** [comment] 2023-03-07 08:43
nope. its not.
this issue is already fixed. I commited a pull request. (so its OK to be closed)
But its not a duplicate. #1976 is a different error

**Comment by skeutmeier** [comment] 2023-07-17 09:13
Seems like my Pull request was never merged into main, and no other fix for this was applied either. This is still not working.

Please reopen the ticket
