### ISSUE TITLE
Notifications 302 response on Magento 2.3.3

### ISSUE THREAD

**Issue by thestudio4** [Adyen/adyen-magento2#765] opened 2020-07-14 08:18 UTC
**Describe the bug**
No matter what has been set on the Adyen settings the url /adyen/process/json will always give a 302 response. Although while visiting the URL from your browser the URL will produce a 401 unauthorised which is correct as no authorisation details are sent with the request. Which indicates that the plugin is creating the 302 redirect for some reason, possibly expecting something that isn't there? I can see a similar issue had been fixed for 2.3 [https://github.com/Adyen/adyen-magento2/pull/328](url)

**To Reproduce**
1) Add the plugin to Magento 2.3.3
2) Configure the plugin with Adyen
3) In the Adyen admin, go Account->Server Communication
4) Setup a new notification
5) Test configuration, resulting in a 302 response everytime.

**Expected behavior**
This should be bringing back a response of "[accepted]" as explained on the test.

**Screenshots**
![adyen3](https://user-images.githubusercontent.com/864280/87401691-622a2080-c5b2-11ea-8a9f-38047773a5bc.jpg)

**Additional context**
We have noticed that every time the notification test is made, the Magetno 2 /var/log/debug.log is throwing the below error:

main.DEBUG: Request validation failed for action "Magento\Framework\App\Action\Forward\Interceptor" [] []

**Comment by acampos1916** [comment] 2020-07-21 13:08
Hello @thestudio4, thanks for raising this issue and sorry for the late response,

Which version of the plugin is being used? If it is >6.2.0 please be aware that some changes were introduced to the way the webhook receives those notifications https://github.com/Adyen/adyen-magento2/releases/tag/6.2.0.

Still, the 302 HTTP code is suspicious. Are there some URL rewrites or server configuration that could be interfering? Which URL is the redirect pointing to? `adyen/process/json`->`?` 

Also, is this reproducible in a test/local environment? You can use a client like Postman to send the notification JSON copied from Account->Server Communication to the local endpoint and see the results.

Cheers,
Ángel Campos

**Comment by thestudio4** [comment] 2020-07-21 13:42
Hi Ángel,

I was originally using 6.2.0 but updated the plugin to the latest version 6.2.1 after reading the bug reported here: https://github.com/Adyen/adyen-magento2/pull/328 

There isn't any redirects as explained in the original post. When visiting the URL from the browser I am presented with a 401 unauthorised error. If we had a redirect we wouldn't see this. The 401 is happening because I'm not sending any authorisation details in my request. Which suggests to me the code is failing and trying to redirect which is what happened on the URL above. I have no idea where it is trying to redirect to as the image indicates it just says 302 response. I have don't have a local environment of the site. I have just installed postman but could you advise on what auth option needs to be chosen as I've tried basic auth and just got a 401.

Thanks,
Justin

**Comment by acampos1916** [comment] 2020-07-21 15:37
@thestudio4 

Ok understood. The #328 PR was originally closed and #357 was merged instead for better backwards compatibility. But this was 2 years ago and such changes are in the plugin since version 2.4.2. Moreover, I just tested the notification receiving in 6.2.1 M2.3.3 and the records were received and accepted successfully, so I don't think this is a problem with the plugin's compatibility with the Magento version.

Be aware that there's a new security configuration section for notifications in the admin panel https://docs.adyen.com/plugins/magento-2/set-up-the-plugin-in-magento#security. From your messages I believe that this functionality is disabled in your instance, but worth to take a look.

Are there additional interesting messages in notification.log or error.log when the webhook is hit? And as a last resort, would you be able to debug and trace at which point of the Json.php class the request returns 302?

Cheers,
Ángel

**Comment by acampos1916** [comment] 2020-10-21 07:21
Hello @thestudio4,

Since there has been no activity on this issue I will close it now. Let us know if my previous message led you to a solution for the 302 response on the notifications endpoint.

**Closed by acampos1916** 2020-10-21 07:21 UTC
Labels: Bug report, Waiting for response
