### ISSUE TITLE
Race condition may cause the order status to be reverted to pending

### ISSUE THREAD

**Issue by pmzandbergen** [Adyen/adyen-magento2#2726] opened 2024-08-29 11:27 UTC
**Description**
When a Customer is delayed between the PSP and the Magento return page the order status can be reversed from `processing`, or in fact any possible state (like `holded`) back to `pending`.

**Cause**
The Controller for the return page calls the PaymentResponseHandler, which in turn updates the order according to the response.

**Code**
1. https://github.com/Adyen/adyen-magento2/blob/365cd45433fd0922c7fbd985a8e732e94ee99376/Controller/Return/Index.php#L98
2. https://github.com/Adyen/adyen-magento2/blob/365cd45433fd0922c7fbd985a8e732e94ee99376/Controller/Return/Index.php#L164
3. https://github.com/Adyen/adyen-magento2/blob/365cd45433fd0922c7fbd985a8e732e94ee99376/Helper/PaymentResponseHandler.php#L210

**Solution**
Check the current order status before doing any changes. If the status isn't `pending_payment` leave the order as-is, since either a previous executing of the controller or the webhook processor has already updated the order.

**I also highly recommend to implement locking to prevent race conditions in case the return controller is executed at the same time as the notification processor (`Adyen\Payment\Helper\Webhook::processNotification(...)`). If no lock is applied (the current situation) those processes may collide. Please note you'll have to place the lock before loading the order, or you'll be using a cached and possible out-of-date model.**

_Note: Finished my previous LEGO set 😇_

**Comment by dimitriBouteille** [comment] 2024-08-29 13:28
Hi @pmzandbergen 

Probably same issue https://github.com/Adyen/adyen-magento2/issues/2708

**Comment by kpitn** [comment] 2024-09-03 07:52
We have the same problem sometimes order in the workflow are not the same : 

**Wrong workflow**


Sep 2, 2024 6:34:18 PM **Pending**
Adyen paymentsDetails response:
authResult: Authorised
pspReference: XXXXXXXXXXXXXX
paymentMethod: mc
Sep 2, 2024 6:34:18 PM **Processing**
Adyen Payment Successfully completed
Sep 2, 2024 6:34:18 PM **Processing**
AUTHORISATION webhook notification w/amount EUR XXX was processed
Sep 2, 2024 6:34:18 PM **Pending**
Adyen HTTP Notification(s):
eventCode: AUTHORISATION
pspReference: XXXXXXXXXXXXXX
paymentMethod: mc
success: true
reason:152400:9559:07/2026
Sep 2, 2024 6:33:33 PM **Pending Payment**
ThreeDS2 action is required to complete the payment.
Result code: ChallengeShopper
Sep 2, 2024 6:33:33 PM **Pending**
Sep 2, 2024 6:33:33 PM
Adyen Result response:
authResult: ChallengeShopper

**Correct workflow**

Sep 3, 2024 6:59:53 AM **Processing**
Adyen Payment Successfully completed
Sep 3, 2024 6:59:53 AM **Processing**
AUTHORISATION webhook notification w/amount EUR XXX was processed
Sep 3, 2024 6:59:53 AM **Pending**
Adyen HTTP Notification(s):
eventCode: AUTHORISATION
pspReference: XXXXXXXXXXXXXX
paymentMethod: mc
success: true
reason:588273:4777:06/2029
Sep 3, 2024 6:59:53 AM **Pending**
Adyen paymentsDetails response:
authResult: Authorised
pspReference: XXXXXXXXXXXXXX
paymentMethod: mc
Sep 3, 2024 6:59:28 AM **Pending Payment**
ThreeDS2 action is required to complete the payment.
Result code: ChallengeShopper
Sep 3, 2024 6:59:28 AM **Pending**
Sep 3, 2024 6:59:28 AM
Adyen Result response:
authResult: ChallengeShopper

**Comment by pmzandbergen** [comment] 2024-09-03 08:00
@kpitn the quick-fix in my [previous comment](https://github.com/Adyen/adyen-magento2/issues/2726#issuecomment-2317860147) will fix this issue.

Note that this issue is also easy to reproduce:
1. Place an order in the webshop using a payment method which is using an external payment page
2. Finish your payment, but do not return to the webshop yet
3. Wait a few minutes for the notifications to be processed (the order will proceed to "processing")
4. Click the "Return to webshop" button and the order is back to "pending"

**Comment by candemiralp** [comment] 2024-09-04 08:06
Hello @pmzandbergen,

Thank you for raising this question and providing a fix for it. This issue duplicates #2708 where @dimitriBouteille has already created a PR. The fix will be released soon.

Best Regards,
Can

**Comment by pmzandbergen** [comment] 2024-09-04 08:42
@candemiralp will you also implement locking, to prevent race conditions when the notification is being processed at the same time as the customer is returning to the webshop? This can occur with the current changes in #2709.

**Comment by sidalto** [comment] 2024-09-05 12:43
@candemiralp We are facing an issue that after the order is placed (Brazilian PIX payment method), we are receiving a payment canceled response, but soon after the order paid notification is received. In orders where this issue occur, we observed that the webhook response changing the order status is being processed before the authorization response.

Wrong workflow:

![imagem1](https://github.com/user-attachments/assets/5e6e4ef4-61f1-46a2-9d63-733ef1cd7992)

Correct workflow:

![imagem3](https://github.com/user-attachments/assets/a95fd7bd-a48b-4cd1-b056-764e1cebdacf)

**Closed** 2024-09-08 19:35 UTC

**Comment by pmzandbergen** [comment] 2024-09-08 20:16
> @candemiralp will you also implement locking, to prevent race conditions when the notification is being processed at the same time as the customer is returning to the webshop? This can occur with the current changes in #2709.

Should we open another issue for this case?

**Comment by candemiralp** [comment] 2024-09-12 14:11
Hello @pmzandbergen,

Thank you for raising your concerns about the fix. I will test it and get back to you.

Best Regards,
Can

**Comment by candemiralp** [comment] 2024-09-30 07:40
Hello @pmzandbergen,

Once again, thank you giving heads-up about this potential edge case. Even though, I couldn't reproduce it manually, I believe it's still possible to come up with that scenario with some automated testing tools. So, this concern is totally valid.

I've investigated implementing a locking mechanism for changing the order status and observed the following difficulties.

1. Webhook processing can be locked as it is an async operation carried out by the cron job. However, `/payments/details` endpoint is called sync during the payment flow. Therefore, it might not be feasible to lock the processes and wait for unlock.
2. To solve this challenge, some message queue can be implemented. But, that means bringing a lot of complexity to the application.
3. There is no out-of-the-box solution for locking a process on distributed multi-server environments. 

Considering those uncertainties and solving this edge case is not the highest priority right now, we will skip this implementation. However, you can create an issue as an enhancement. So that, we can pick it up once the team prioritised that task.

Best Regards,
Can
