### ISSUE TITLE
[PW-4710] Could be possibile to use the Manual review for immediate capture orders? 

### ISSUE THREAD

**Issue by mirkocesaro** [Adyen/adyen-magento2#1236] opened 2021-11-10 14:19 UTC
I noticed in the https://docs.adyen.com/plugins/magento-2/set-up-the-plugin-in-magento#manual-review section that it is not possible to use the manual review when it is configured the automatic capture.

At the moment, before processing an order, we have to check the Adyen platform to understand if there is a risk on it. 
This action is performed on all orders and it is done to prevent loss of money.

A possible solution could be to handle the manual review on the notification to set the 'Manual Review Status' when a risk is detected by Adyen and to set the 'Manual Review Accepted Status' after the notification of approval. 

In the current situation, the 'Manual Review Status' is set but for some reason, the processing status is back right after it. Is it a bug? As you can see in the following image the "Adyen holded" is my Manual Review Status, but the order's state and status are `processing`
<img width="861" alt="Screenshot " src="https://user-images.githubusercontent.com/1431255/141126004-7ba19957-3922-44f0-8526-d442c103a632.png">

Do you think is it a valid enhancement to work on? 

I also would like a confirmation that it is correct to don't perform any action when someone denies the review
<img width="794" alt="Screenshot deny" src="https://user-images.githubusercontent.com/1431255/141128992-aefedeac-7024-4077-a560-bf04d134bc1c.png">
and wait for the cancel notification.

Thanks,
Mirko

**Comment by tnaber** [comment] 2021-11-10 14:46
Hi @mirkocesaro,

This is a great suggestion. We have a ticket open for this internally which should be picked up soon. 

It is indeed correct to not perform any actions when someone denies a review. This is because the cancel or refund webhook should then be received by the plugin, this will handle the order cancellation in Magento.

Cheers,
Titus

**Comment by mirkocesaro** [comment] 2021-11-12 17:23
Hi @tnaber ,
thank you. I am checking the problem and basically, the Manual Review Status configuration uses the Magento\Sales\Model\Config\Source\Order\Status\NewStatus class, and this means that the status for the manual review is linked to the NEW state.

The problem with the immediate capture configuration is the invoice, after the creation of the invoice, Adyen module sets:
``` $invoice->getOrder()->setIsInProcess(true);```
you can see it here: \Adyen\Payment\Model\Cron::_createInvoice 

And this data on the order is used on the save method  to set the order in processing (see here \Magento\Sales\Model\ResourceModel\Order\Handler\State::check)

I am creating a PR with a fix. 

Let me know if it is ok.

Thanks,
Mirko

**Comment by Morerice** [comment] 2021-11-16 14:05
Hi @mirkocesaro 

Thanks for opening this and issue and for offering a possible solution in your PR. 

We have recently discussed if we should still create an invoice when a payment requires a manual review. In our opinions the invoice should be created once the payment which requires the manual review has been accepted.

Do you agree with this opinion or do you share a different one?

I am aware this is not exactly the issue you are talking about but because it's related to this issue and to #1225 we would value your opinion.

Best regards,
Jean

**Comment by mirkocesaro** [comment] 2021-11-16 18:24
Hi @Morerice,

I am not really sure, I think it is more correct to create the invoice and then set the manual review status when the module is configured with immediate capture.

As you can confirm to me, with the immediate capture, the transaction on Adyen is captured after the creation without waiting for the manual review. 
And basically, it is the same status that I want to see on Magento, I already captured the amount and I have to check the manual review before proceeding with the order fulfilment and sending the items to the client. 

This is an order I made and I didn't approve the manual review yet, as you can see, the capture has the same hour of the manual review 
<img width="412" alt="Screenshot 2021-11-16 at 18 11 28" src="https://user-images.githubusercontent.com/1431255/142041737-0add869a-021d-4305-b1b8-f2a4780fe62a.png">

I think is correct to proceed in this way. 

Let me know what you think.

Best regards,
Mirko

**Comment by Morerice** [comment] 2021-11-18 15:18
Hi @mirkocesaro 

Thanks for your response. I can confirm what you mentioned regarding immediate capture, in which case the payment will be technically already captured on the Adyen platform, and it will just be pending the Manual Review.

We have decided to proceed with your suggestion of the flow. However we still need to verify if your PR will affect some other edge cases of different payment methods. We already have an internal ticket to go through how all manual review webhooks are currently handled and make their processing more intuitive, so once your PR is tested, it will probably be merged around the same time of this ticket. The ticket should be picked up shortly.

In the meantime if you have any other input feel free to comment on this issue.

Thanks and regards,
Jean
Adyen

**Comment by Morerice** [comment] 2021-12-06 08:20
Hi @mirkocesaro

I have created PR #1274 to tackle this issue and also refactor the code related to case management in general. If you want to verify that this PR solves your issue, before it is released, feel free to do so. We would also appreciate any kind of feedback you might have regarding this PR.

Thanks and regards,
Jean
Adyen

**Comment by mirkocesaro** [comment] 2021-12-07 16:47
Hi @Morerice 

I tried your PR and I found a problem:
when you set the property `setIsInProcessing(false)` the order has already the `processing` status, the flag is not used anymore to check if the order needs to be updated.

The problem is raised with _authorizePayment() method when the _setPrePaymentAuthorized method set the status, the status configured could be with state new or processing, and in this last case, I found the problem.

When this happens, the method _prepareInvoice cannot set the `new` state because the order is no anymore in payment_review. And the end of the process, the manual review status (<source_model>Magento\Sales\Model\Config\Source\Order\Status\NewStatus</source_model>) is set with a state not valid.

Let me know if you need any other information.

Thanks,
Mirko

**Closed** 2021-12-16 12:40 UTC
Labels: Enhancement, Webhooks

**Comment by Morerice** [comment] 2022-02-21 08:32
This latest comment and other follow-up questions were addressed within the pull request.
