### ISSUE TITLE
Why AdyenPayment module is strongly coupled to paypal

### ISSUE THREAD

**Issue by Marwaa92** [Adyen/adyen-magento2#1862] opened 2022-12-01 19:19 UTC
Hello,

Currently I am working on a Magento 2.4.5 context,  where the module Magento_Paypal is disabled, when I go to the cart page I see this exception Message
`Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'customer_id' in 'where clause', query was: SELECT `main_table`.* FROM `paypal_billing_agreement` AS `main_table` WHERE (`customer_id` = '1285336') AND (`store_id` = '1') AND (`method_code` = 'adyen_oneclick') AND (`status` = 'active')
Exception #1 (PDOException): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'customer_id' in 'where clause'`

Why the adyen module is strongly dependent to the paypal module?
We should be able to use Adyen payment module independently of the other payment modules!

**To Reproduce**
1. Disable module Magento_Paypal 
2. Add product to cart
3. Go to cart page

**Expected behavior**
Do not have an exception on cart page

**Magento version**
2.4.5-p1

**Plugin version**
8.11.0

**Screenshots**
![image](https://user-images.githubusercontent.com/114406666/205140142-6f943226-a78c-4aef-837e-f674dde69b80.png)

**Comment by Morerice** [comment] 2022-12-02 09:29
Hi @Marwaa92,

Thanks for opening this issue and asking this question. Currently some functionality of our tokenization is using the `paypal_billing_agreement` table. We are currently planning to move all our tokenization functionality to vault in our next major version (v9), where we will then remove this dependency.

I am closing this issue as this is a duplicate of #1326

Thanks,
Jean
Adyen

**Closed by Morerice** 2022-12-02 09:29 UTC
Labels: Question

**Comment by Marwaa92** [comment] 2022-12-02 09:35
Hello  @Morerice ,

Thank you for your reply.

Do you have please any idea about  the date of the next release version V9?

Thanks,
Marwa

**Comment by Morerice** [comment] 2022-12-02 09:43
> Hello @Morerice ,
> 
> Thank you for your reply.
> 
> Do you have please any idea about the date of the next release version V9?
> 
> Thanks, Marwa

We don't have specific date set yet but we are planning to release around end of Q1/start of Q2 2023.

Regards,
Jean
Adyen
