### ISSUE TITLE
[PW-7006] Orders Stuck in a processing status after being completely invoiced and shipped

### ISSUE THREAD

**Issue by jordanvector** [Adyen/adyen-magento2#1632] opened 2022-07-28 17:38 UTC
**Describe the bug**
We have noticed on the Adyen 8.3.2 that when an order is completely invoiced and shipped correctly it is being put back into a processing status rather than a complete status like it should.  This causes a huge issue with order processing processes on the backend that depend on that status being correctly in a completed state when actually complete.

**To Reproduce**
1.  Go through typical order process with the below settings 
![Screen Shot 2022-07-28 at 1 34 30 PM (2)](https://user-images.githubusercontent.com/6155117/181601745-2e4528ac-32dd-4cca-b41c-b9b2d51522e4.png)
2.  Invoice and ship all items in the order 
3. Notice that the order status is now back to processing instead of complete

**Expected behavior**
order should be marked to complete after all items are invoiced and shipped .

**Magento version**
2.4.3

**Plugin version**
8.3.2

**Desktop (please complete the following information):**
 - OS: mac os
 - Browser edge

**Comment by jordanvector** [comment] 2022-08-01 21:04
What ends up happening is the order seems to be put back into a pending payment status for some reason.  Looking at the order that should be complete we see this status, which seems to be the only option at that point.

![Screen Shot 2022-08-01 at 4 20 42 PM (2)](https://user-images.githubusercontent.com/6155117/182246275-699c1a82-c9f8-4d39-b71b-dc53041c7ae5.png)

**Comment by RokPopov** [comment] 2022-08-02 08:05
Hi @jordanvector,

Thank you for reporting this issue with us.
Indeed, I was able to replicate the issue - it seems that the order is stuck on the status that is configured for the payment authorisation. This shouldn't be the case.
I have opened an internal ticket and we will be further investigating this.

Kind regards,
Rok,
Adyen

**Comment by jordanvector** [comment] 2022-08-02 15:00
Thank you @RokPopov I did some more testing and it appears like no change of configuration in the order processing settings resolves this issue, always seems to be bounced back into pending payment

**Comment by fahu** [comment] 2022-08-03 05:30
We experience a similar issue where the order is put back to state "new". In our case it's because we receive two notifications from Adyen:
1. Notification informing that payment is successful -> order is moved to processing
2. After a few more minutes we receive a notification informing that payment has failed -> order is moved to status "new" again.

**Comment by jordanvector** [comment] 2022-08-04 21:10
@RokPopov I have had a good look at whats happening here and I have a few thoughts and opened a PR for a fix for this

Overall the logic in the Helper/Order.php file should really be revisited. The main issue arises from updating order state in various scenarios that overall should be avoided if possible, mainly due the inability of admin users to edit order state via the admin if any issues arise. But essentially the source of this issue is that in a happy path of an order workflow, the order state is either kept in new or pending_payment (both scenarios the order on the adyen and magento side has been successfully authorized and payment captured), changing the order state to processing actually fixes this issue in both of those scenarios and magento then properly completes the order when all items are invoiced and shipped.

**Comment by RokPopov** [comment] 2022-08-08 14:09
Hi @jordanvector,

Thank you for diving into this and opening a PR with the fix. 
I wanted to let you know we appreciate your contribution and will review your PR as soon as possible.

Kind regards,
Rok,
Adyen

**Comment by RokPopov** [comment] 2022-08-24 09:09
Hi @jordanvector,

Thank you for your patience on this. I have been investigating this on the v8.3.5 and will give you the outcome of the investigation bellow:

With the usage of the default order statuses, as seen in the screenshot:
<img width="958" alt="Screen Shot 2022-08-24 at 10 54 07" src="https://user-images.githubusercontent.com/59090063/186375470-595563aa-5d54-475c-a851-44c2ee32058b.png">

The order is promoted to the correct `Complete` status after shipping:
<img width="967" alt="Screen Shot 2022-08-24 at 10 54 55" src="https://user-images.githubusercontent.com/59090063/186375664-9ef4f561-1595-4050-bff7-fc110fd756c5.png">

How this works under the hood is Magento promoting the order upon shipping by executing [this block of code](https://github.com/magento/magento2/blob/e334af14414cb763fa3083a72f08bd72de6224d0/app/code/Magento/Sales/Model/ResourceModel/Order/Handler/State.php#L41-L43). As you can see, the condition for the order to be promoted to `Complete` state is that the current state is `Processing`. In the default order status setup, this block of code gets executed and the order gets the correct status update.

However, checking your case, I can see that you have created a new `Processing` order status that you assigned to `Pending payment` or `Pending`. You are selecting this status in the dropdown for the `payment authorisation` in the admin panel. Furthermore, you are then using the `Maintain status` for `payment confirmed`. I have replicated this setup and debugging the flow upon shipping, I can see that the above code block is not entered as the first condition, for the current status to be `Processing` is not adhered. The current status at this point with your order status setup is `Pending payment` (due to a fact that you assigned a new status name to `Pending payment`). On top of that, for the next step (`payment confirmed`) you are using `Maintain status`. Therefore, Magento's own condition of the payment to be in the `Processing` status to be promoted to `Complete` status is not adhered. In conclusion, that would be an unexpected behaviour from Magento's perspective.

I tried to test another case, where I still had the `payment authorisation` set to the custom `Processing` status and used `Processing` again in the next step -> `payment confirmed`, as you can see in the screenshot bellow:
<img width="689" alt="Screen Shot 2022-08-24 at 11 04 25" src="https://user-images.githubusercontent.com/59090063/186377792-eb3075a2-c34e-439b-891f-b181731d4fd6.png">

With this setup, the order was indeed promoted to `Complete` after shipping:
<img width="1409" alt="Screen Shot 2022-08-24 at 11 05 19" src="https://user-images.githubusercontent.com/59090063/186377967-829b358b-c0ba-4192-bc12-ba0aa2926277.png">

Would you be able to test the flow without using the `Maintain status` for `payment confirmed` and see whether the problem is still persisting?
 
Thank you in advance,

Kind regards,
Rok,
Adyen

**Comment by Morerice** [comment] 2022-11-30 16:02
Closing this issue due to extended inactivity. If more information can be provided, feel free to leave a comment so that we can verify if we should re-open this issue.

Thanks,
Jean
Adyen

**Closed by Morerice** 2022-11-30 16:02 UTC
Labels: Question, Bug report
