### ISSUE TITLE
Payment methods not updated after selecting a different country when purchasing a downloadable product

### ISSUE THREAD

**Issue by CreamDevelopment** [Adyen/adyen-magento2#1994] opened 2023-03-14 13:23 UTC
**Describe the bug**
After selecting a different country in the billing address when purchasing a downloadable product, the payment methods are not updated to match the allowed payment methods for that specific country. It is only after reloading or clicking a button that the payment methods change to the allowed payment methods for that country.

**To Reproduce**
Preconditions:
Payment methods are different between countries. For instance: iDeal is activated for NL only or Bancontact is activated only for BE.

1. Add a downloadable product to the cart
2. Continue to the checkout
3. Fill in customer details and change country from (for instance) NL to BE
4. Notice that the payment methods which can be selected do not change

**Expected behavior**
The payment methods should change to the allowed payment methods for the selected country, which are configured in the Adyen user area (Settings > Checkout Settings) when purchasing a downloadable product.

**Magento version**
2.4.5

**Plugin version**
8.14.0

**Desktop**
 - OS: MacOS
 - Browser Chrome
 - Version 109.0.5414.119

**Smartphone**
 - Device: iPhone 13
 - OS: iOS 16.3.1
 - Browser Chrome
 - Version 110.0.5481.114

**Comment by candemiralp** [comment] 2023-04-24 11:10
Hello @CreamDevelopment,

Thank you for raising this issue. Currently, shipping address is being used to fetch the applicable payment methods for an order. We know that it is confusing especially for the virtual products. That behaviour is changing with the version 9 of the plugin. That individual PR also fixes the issue related to the virtual (downloadable) products.

We are attaching this Github issue to the version 9 milestone and will be sure to double check the expected behaviour before releasing.

Best Regards,
Can

**Comment by candemiralp** [comment] 2024-01-15 12:49
Hello @CreamDevelopment,

Closing this issue since it has been resolved on the new major version V9. Now, payment methods are updated according to billing address country.

Best Regards,
Can

**Closed by candemiralp** 2024-01-15 12:49 UTC
Labels: Bug report
