### ISSUE TITLE
[PW-2029] Refunds are always using base currency prices

### ISSUE THREAD

**Issue by sanderjongsma** [Adyen/adyen-magento2#689] opened 2020-04-09 15:45 UTC
**Describe the bug**
Refunds are not using the converted price. On line 72 of `Gateway/Request/RefundDataBuilder.php` the amount to refund is fetched by: `$amount = \Magento\Payment\Gateway\Helper\SubjectReader::readAmount($buildSubject);` this will always return the base total. 

The currency code is fetched from the order, this is good. So what is happening the request to be send has the proper currency in it but not the proper value when the order is placed in another currency. The creditmemo in Magento is created but not proceeded in Adyen, the response in the logging contains the following message: `[reason] => Insufficient balance on payment`

**To Reproduce**
Setup multiple stores with other currencies, place orders from different stores and try refunding them. The amounts in Adyen wil differ from the Magento amount if the order was placed by an other currency as the base currency.

**Expected behavior**
price value of the request to refund needs to be converted.

**Comment by Aleffio** [comment] 2020-04-21 09:21
Hi @sanderjongsma ,
sorry for the delay and thanks for reporting the bug,
at the moment the plugin does not allow configurations where the base currency is different from the display currency, you can check issue #456 for a similar discussion.

We are working to make this available through a configuration setting.

Kind Regards,
Alessio
Adyen

**Comment by PortalFl0w** [comment] 2020-04-22 08:29
Just wanted to join in and say we are also experiencing this issue, we like the fact that Adyen is able to charge the customer in the display currency set as it resolves some confusion customers sometimes have when they get charged a different amount to what they saw on the screen. 

Like @sanderjongsma said, when we try to refund these orders however, Adyen receives the base currency value, but the currency code is set to the display one, resulting in a partial refund for us. 

For example here, the user paid 8.69USD. The refund sent the value as the base currency one (6.99GBP) even though the currency is set to USD.

`{
   "modificationAmount" : {
  "currency" : "USD",
      "value" : 699​
   },
   "reference" : "XXXXX",
   "originalReference" : "XXXXX",
   "merchantAccount" : "XXXXX",
   "applicationInfo" : {
      "adyenLibrary" : {
         "name" : "adyen-php-api-library",
         "version" : "4.2.0"
      },
      "adyenPaymentSource" : {
         "version" : "4.5.4",
         "name" : "adyen-magento2"
      },
      "externalPlatform" : {
         "version" : "2.3.4",
         "name" : "Magento"
      }
   }
}`

Would your configuration setting also affect the refunds in the future?

**Comment by sanderjongsma** [comment] 2020-04-22 10:14
@PortalFl0w for now you can create an after plugin for the `public function build(array $buildSubject)` method in the `Gateway/Request/RefundDataBuilder.php` file.

and in the plugin do something like this: 
```
    public function afterBuild(RefundDataBuilder $subject, $result)
    {
        // skip if empty or if multiple in array (this means split payments)
        // we do not support split payments
        if (count($result['body']) < 1 || count($result['body']) > 1) {
            return $result;
        }

        $amount = $result['body'][0]['modificationAmount']['value'];
        $currency = $result['body'][0]['modificationAmount']['currency'];

        // skip convertion for base currency amounts
        if ($currency === $this->storeManager->getStore()->getBaseCurrencyCode()) {
            return $result;
        }

        // convert amount by currency string
        $convertedAmount = $this->priceCurrency->convert(
            $amount,
            null,
            $currency
        );

        // append converted amount, round it and make it an integer,
        // because the value is already the price * 100
        $result['body'][0]['modificationAmount']['value'] = (int) round($convertedAmount);

        return $result;
    }
```

This is our workaround for now

**Comment by PortalFl0w** [comment] 2020-04-22 10:46
Thanks @sanderjongsma ! I will definitely give that a go, although as it does the conversion at the time of the refund would it be possible that we conversion rate is different to when the order was placed? We update ours daily.  I might take this idea though, and make it work in our case for the time being. 

Thank you!

**Comment by edroberts** [comment] 2020-07-17 14:26
Why is this flagged as an 'enhancement'? This is a design flaw and needs to be fixed.

**Comment by floorjubbega** [comment] 2020-10-21 09:12
Duplicate of #456

**Closed by floorjubbega** 2020-10-21 09:12 UTC
Labels: Enhancement
