### ISSUE TITLE
[PW-5780] Error: Detected container element removed from DOM

### ISSUE THREAD

**Issue by s1nz** [Adyen/adyen-magento2#1204] opened 2021-10-21 14:16 UTC
**Describe the bug**
Since recent update to 7.2.0 we are constantly receiving a lot of errors, like this one in Sentry:

`Detected container element removed from DOM
@https://www.paypal.com/sdk/js?merchant-id=KMBZHYMWQFJQQ&currency=CHF&intent=capture&commit=true&vault=false&client-id=AU0Z-TP9t5_9196agaBN6ZD3UAwypdP1IX8ZYH3PcNNAQMXUTDQlChruXqQEhyI6-NKBKowN6ydkj477&integration-date=2020-02-01&components=buttons,funding-eligibility:2:104077`

and also `Error: zoid destroyed all components`.

**To Reproduce**
1. Go to https://drinks.ch/
2. Add product to your cart
3. Go to checkout
4. Open dev console
4. Fill your data on first step
5. Go to payments
6. See the error in console

**Expected behavior**
No error

**Magento version**
2.4.1

**Plugin version**
7.2.0, 7.3.0

**Screenshots**
<img width="978" alt="Screenshot 2021-10-21 at 16 15 04" src="https://user-images.githubusercontent.com/398774/138295930-a0192450-e13e-49c5-abab-623a0967e527.png">

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Browser Any

**Comment by tnaber** [comment] 2021-11-04 14:41
@s1nz, I have created an internal ticket to investigate this. I have set the priority to low as it does not seem to break any functionalities. Let me know if I am wrong and it does break stuff :)

**Comment by tnaber** [comment] 2021-11-11 10:12
@s1nz, I get a similar error on my end. To further determine where the issue is, could you provide me with the version that you were previously on?  (before upgrading to 7.2.0)

**Comment by s1nz** [comment] 2021-11-17 14:23
@tnaber The history of upgrades is 6.7.0 -> 7.0.1 -> 7.2.0 -> 7.3.0

**Comment by tnaber** [comment] 2022-05-04 14:10
Hi @s1nz,

We are not experiencing this problem anymore in our latest version. As this does not break any functionality we will leave it as it is and close this issue.
Feel free to reopen if this becomes a large problem for you.

Cheers,
Titus

**Closed by tnaber** 2022-05-04 14:10 UTC
Labels: Bug report, Priority: low, Confirmed, Progress: on hold
