### ISSUE TITLE
[ECP-8985] Credit memo is not working for the Adyen Payments

### ISSUE THREAD

**Issue by nareshanjuru** [Adyen/adyen-magento2#2511] opened 2024-02-15 08:19 UTC
Making your own contribution is easy, encouraged and greatly appreciated! We will put effort into reviewing and merging your PR quickly. For more info, please refer to the contribution guidelines: https://github.com/Adyen/adyen-magento2/blob/develop/CONTRIBUTING.md

**Describe the bug**
Placed an order using Adyen credit card.
Captured the amount from the Magento admin
While creating the credit memo getting the below error and Creditmemo failing

**Deprecated Functionality: Creation of dynamic property Adyen\Payment\Gateway\Request\RefundDataBuilder::$openInvoiceHelper is deprecated in /var/www/magento/vendor/adyen/module-payment/Gateway/Request/RefundDataBuilder.php on line 50**

**To Reproduce**
1. Place an order in the website using Adyen Credit card
2. Go to the Magento admin. Fulfill the order by doing shipment and invoice.
3. Go to the credit memo and create the credit memo and click Refund.
Deprecated Functionality: Creation of dynamic property Adyen\Payment\Gateway\Request\RefundDataBuilder::$openInvoiceHelper is deprecated in /var/www/magento/vendor/adyen/module-payment/Gateway/Request/RefundDataBuilder.php on line 50

**Expected behavior**
The system should allow the creation of the CreditMemo without any error.

**Magento version**
2.4.6-p3

**Plugin version**
9.0.7

**Screenshots**
When we are trying to create creditmemo and click refund. the below image is coming and unable to proceed further to create the credit memo.
<img width="617" alt="image" src="https://github.com/Adyen/adyen-magento2/assets/8188857/b2d9ffa9-68b8-4b31-b4c7-b7477c075ff2">

**Desktop (please complete the following information):**
All browsers

**Smartphone (please complete the following information):**
 All devices

**Additional context**

**Comment by hossam-adyen** [comment] 2024-02-19 14:37
Hi @nareshanjuru, thanks for opening this issue, I'm closing it as it's a duplicate of https://github.com/Adyen/adyen-magento2/issues/2487 and we already fixed it with this [PR](https://github.com/Adyen/adyen-magento2/pull/2507)

**Closed by hossam-adyen** 2024-02-19 14:37 UTC
Labels: Bug report
