### ISSUE TITLE
ECP-8799 [V9] Cannot refund (via Magento) with Alternative methods 

### ISSUE THREAD

**Issue by Nuranto** [Adyen/adyen-magento2#2367] opened 2023-11-27 16:16 UTC
**Describe the bug**

We cannot refund online via creditmemo creation page (only button `Refund offline` is present) for alternative payments (tested on alma and google pay.).

It works fine for adyen_cc.

**To Reproduce**
1. Try to refund an order paid with googlepay

**Expected behavior**

`Refund online` button is there.

**Magento version**
2.4.6-p3

**Plugin version**
9.0.2

**Comment by hossam-adyen** [comment] 2023-12-03 12:50
Hi @Nuranto, thanks for reporting the issue and @kdivan for pointing out what is seems to be a root cause,  I've created an internal ticket to investigate and solve the issue. You will be informed when it is done.

**Closed** 2023-12-20 09:05 UTC
Labels: Bug report
