### ISSUE TITLE
Credit card payment error  TypeError: paymentMethodsResponse.paymentMethodsExtraDetails.card is undefined

### ISSUE THREAD

**Issue by frostblogNet** [Adyen/adyen-magento2#1542] opened 2022-05-27 10:00 UTC
**Describe the bug**
Credit card payment method is not usable

**To Reproduce**
1 Add a product to the card
2. go to checkout stept 2
3. open dev console 
4. see error TypeError: paymentMethodsResponse.paymentMethodsExtraDetails.card is undefined

**Magento version**
Adobe Commerce 2.4.4

**Plugin version**
adyen/module-payment                                              8.2.3  

**Screenshots**
![grafik](https://user-images.githubusercontent.com/19548641/170675919-a966f8d5-fb55-4741-85aa-f2553b92273f.png)

**Comment by frostblogNet** [comment] 2022-05-27 10:02
Maybe this is an project specific error but it would be nice if you can give us any info what might course this issue.

Thanks

**Comment by frostblogNet** [comment] 2022-05-27 11:06
Looks like there is something missing in the response from the payment request.

![grafik](https://user-images.githubusercontent.com/19548641/170687968-390abaf8-9aa8-4518-a417-9245c0dca840.png)

**Comment by frostblogNet** [comment] 2022-05-27 11:09
Output from \Adyen\Payment\Helper\PaymentMethods Line 191

**Comment by JoostWan** [comment] 2022-05-30 06:25
Same error over here but more specific for the card icon. 

[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'paymentMethodsResponse.paymentMethodsExtraDetails.card.icon')
	(anonymous function) (adyen-cc-method.min.js:2:110)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise

[Error] Failed to load resource: the server responded with a status of 404 ()  https://checkoutshopper-test.adyen.com/checkoutshopper/images/logos/ideal/1163.svg

**Comment by JoostWan** [comment] 2022-05-30 06:50
Enabled the logo function in the backend and now it's working. 

![Screenshot 2022-05-30 at 08 50 19](https://user-images.githubusercontent.com/5435412/170933496-82d27ccc-06eb-473d-81c0-b70fd94f48b2.png)

**Comment by tnaber** [comment] 2022-05-30 12:53
Hi @JoostWan and @frostblogNet,

(First off, @JoostWan thank for helping out!)

Good to see that the problem is solved. Do you think we can close this issue or should it be turned into a feature request to provide some extra information in the plugin? (Also dependent on whether you are using a headless setup)
Let me know you think!

Cheers,
Titus

**Comment by frostblogNet** [comment] 2022-05-30 13:08
Hi @tnaber 

The solution provided by @JoostWan (Thanks for the help) is more or less a workaround. Your Extension still has issues when it is switched to title only in the backend.

**Comment by tnaber** [comment] 2022-05-30 14:35
Hi @frostblogNet,

I see, I opened a PR for it!

Cheers,
Titus

**Closed** 2022-06-01 07:44 UTC
Labels: Bug report, Priority: medium, Confirmed
