### ISSUE TITLE
[PW-6726] Refund notification stuck to processing

### ISSUE THREAD

**Issue by jonathanribas** [Adyen/adyen-magento2#1493] opened 2022-05-06 02:31 UTC
**Describe the bug**
Refund notification stuck to in processing

**To Reproduce**
1. Place an order
2. Ship
3. Refund
4. When Adyen Refund notification cron will run, credit memo will be created, order status updated but notification stay to processing at 1 and done to 0

**Expected behavior**
Adyen notification should end correctly and set to done = 1 and processing = 0 in adyen_notification table..

**Magento version**
2.4 3-p1

**Plugin version**
8.2.0 and 8.2.2

**Comment by tnaber** [comment] 2022-05-11 14:07
Hi @jonathanribas,

Thank you for opening this issue. This should indeed be set to 0 in the end. We will be investigating this and open a ticket once the issue is confirmed.

Cheers,
Titus

**Comment by Morerice** [comment] 2022-05-31 14:24
Hi @jonathanribas,

Apologies for the delay. I have managed to replicate the issue on my end. To make sure that we are experiencing the same issue, could you check the `cronjob.log` file and verify if you also have the following message? `ERROR: Unhandled order state 'closed'`

Thanks,
Jean
Adyen

**Comment by jonathanribas** [comment] 2022-05-31 23:06
Hi @Morerice, yes I can found it, I also found the following one but it's maybe due to another stuff:
`Unhandled order state 'holded'.`

**Comment by RokPopov** [comment] 2022-06-02 16:49
Hi @jonathanribas , would you be able to test this [PR](https://github.com/Adyen/adyen-magento2/pull/1557) addressing the reported issue? 

Thank you in advance,
Rok

**Comment by jonathanribas** [comment] 2022-06-05 07:52
Hi @RokPopov, unfortunately I can't test it now, sorry. 
I will have to wait for the release that incluses this fix.

**Closed** 2022-06-16 11:35 UTC
Labels: Bug report, Priority: high, Confirmed
