### ISSUE TITLE
Order in status "Payment review" when it actually has completed sucessfully

### ISSUE THREAD

**Issue by tieroom** [Adyen/adyen-magento2#744] opened 2020-06-24 08:53 UTC
**Describe the bug**
We have had a number of incidents where orders with successful credit card transactions are still listed in the magento admin as Payment review. We can see in the adyen admin that the payment was successful and even the history on the order detail page in magento (see screenshot below) says it should have changed status to processing but it never does (meaning the status in the order matrix or the status displayed at the top of the order detail page is still Payment review). The order is then not possible to process correctly.

**To Reproduce**
No idea how to reproduce, occurs intermittently.

**Expected behavior**
The order's status should change from Payment review to Processing.

**Screenshots**
[Screenshot of order history in magento admin](https://www.dropbox.com/s/6j5iowgbfxsnnmj/Sk%C3%A4rmklipp%202020-06-22%2015.17.40.png?dl=0)

**Additional context**
Occurred on both Magento 2.3.4 and 2.3.5 with Adyen module 6.1.0

**Comment by acampos1916** [comment] 2020-06-29 08:09
Helo @tieroom,

Thank you for opening this issue. Since you have no way to reproduce it consistently maybe you can share some details to try to pinpoint the problem: Are there interesting messages related to the affected orders in `var/log/adyen`?

Cheers,
Ángel

**Comment by tieroom** [comment] 2020-07-01 09:19
Hi Ángel,

In the cron log everything looks the same as a correctly processed order (at least to me it does). It even says `State is changed to  processing` despite not actually changing the status. Both the info.log and notification.log show normal authorised/completed responses. Should you want me to send full logs, let me know to which email.

Unless you have any other ideas on how to investigate, I understand this is a tricky one to move forward with and understand if you close it for now. But happy if you keep it in mind should you get more similar reports and that you have an extra look at this scenario next time you are working the relevant code.

Thanks

**Comment by acampos1916** [comment] 2020-07-06 06:32
Thanks @tieroom,

If you do find a way to reproduce it or discover something about why it could be happening don't hesitate to shoot a message. I'll close this issue for now, we'll keep an eye out for similar reports to link them here.

Best,
Ángel

**Closed by acampos1916** 2020-07-06 06:32 UTC
Labels: Bug report

**Comment by Lukas713** [comment] 2024-12-11 09:47
This is happening on our latest Magento and latest Adyen version:

Magento: 2.4.7-p2
Adyen: 9.12.0
